# Generated by Django 5.0.8 on 2025-11-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0232_remove_invoice_verifactu_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifactuBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifactuInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.CharField(blank=True, max_length=255, null=True)),
                ('verifactu_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('verifactu_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('verifactu_previous_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifactu.verifactubatch')),
                ('verifactu_previous_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_previous_invoices', to='billing.invoice')),
            ],
        ),
    ]
