# Generated by Django 5.0.8 on 2025-11-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_CuotaTotal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_FechaExpedicion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_FechaHoraHusoGenRegistro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_Huella',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_IDEmisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_ImporteTotal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_NumSerie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='hash_TipoFactura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifactuinvoice',
            name='verifactu_previous_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_previous_invoices', to='verifactu.verifactuinvoice'),
        ),
    ]
