# Generated by Django 5.0.8 on 2025-11-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0002_verifactuinvoice_hash_cuotatotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifactuinvoice',
            name='verifactu_previous_hash',
        ),
        migrations.AddField(
            model_name='verifactubatch',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifactuinvoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_invoices', to='verifactu.verifactubatch'),
        ),
    ]
