# Generated by Django 5.0.8 on 2025-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0003_remove_verifactuinvoice_verifactu_previous_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifactubatch',
            name='response',
            field=models.CharField(blank=True, null=True),
        ),
    ]
