# Generated by Django 5.0.8 on 2025-11-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0004_alter_verifactubatch_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifactubatch',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='message',
            field=models.CharField(blank=True, null=True),
        ),
    ]
