# Generated by Django 5.0.8 on 2025-11-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0006_verifactuinvoicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifactuinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='cancelled_response',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='cancelled_response_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifactuinvoice',
            name='invoice_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
