# Generated by Django 5.0.8 on 2025-12-02 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0243_remove_invoice_verifactu_invoice'),
        ('verifactu', '0007_verifactuinvoice_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifactuinvoicelog',
            name='verifactu_invoice',
        ),
        migrations.RemoveField(
            model_name='verifactuinvoicelog',
            name='user',
        ),
        migrations.CreateModel(
            name='VerifactuNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, null=True)),
                ('verifactu_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('verifactu_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_IDEmisor', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_NumSerie', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_FechaExpedicion', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_TipoFactura', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_CuotaTotal', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_ImporteTotal', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_Huella', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_FechaHoraHusoGenRegistro', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_invoices', to='verifactu.verifactubatch')),
                ('cancelled_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelling_notification', to='verifactu.verifactunotification')),
                ('verifactu_previous_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifactu.verifactunotification')),
            ],
        ),
        migrations.CreateModel(
            name='VerifactuNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('field_name', models.TextField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('operation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verifactu_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifactu_notification_logs', to='verifactu.verifactunotification')),
            ],
        ),
        migrations.DeleteModel(
            name='VerifactuInvoice',
        ),
        migrations.DeleteModel(
            name='VerifactuInvoiceLog',
        ),
    ]
