# Generated by Django 5.0.8 on 2025-12-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0008_remove_verifactuinvoicelog_verifactu_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifactunotification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_notifications', to='verifactu.verifactubatch'),
        ),
    ]
