# Generated by Django 5.0.8 on 2025-12-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifactu', '0009_alter_verifactunotification_batch'),
    ]

    operations = [
        # -----------------------------
        # 3️⃣ Create trigger function (shared)
        # -----------------------------
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION audit_table_changes()
        RETURNS trigger AS $$
        DECLARE
            app_user TEXT := current_setting('myapp.user_id', true);
        BEGIN
            IF TG_OP = 'INSERT' THEN
                IF TG_TABLE_NAME = 'billing_invoice' THEN
                    INSERT INTO billing_invoice_audit(operation, new_data, app_user)
                    VALUES ('I', row_to_json(NEW), app_user);
                ELSIF TG_TABLE_NAME = 'verifactu_verifactunotification' THEN
                    INSERT INTO verifactu_verifactunotification_audit(operation, new_data, app_user)
                    VALUES ('I', row_to_json(NEW), app_user);
                END IF;
                RETURN NEW;

            ELSIF TG_OP = 'UPDATE' THEN
                IF TG_TABLE_NAME = 'billing_invoice' THEN
                    INSERT INTO billing_invoice_audit(operation, old_data, new_data, app_user)
                    VALUES ('U', row_to_json(OLD), row_to_json(NEW), app_user);
                ELSIF TG_TABLE_NAME = 'verifactu_verifactunotification' THEN
                    INSERT INTO verifactu_verifactunotification_audit(operation, old_data, new_data, app_user)
                    VALUES ('U', row_to_json(OLD), row_to_json(NEW), app_user);
                END IF;
                RETURN NEW;

            ELSIF TG_OP = 'DELETE' THEN
                IF TG_TABLE_NAME = 'billing_invoice' THEN
                    INSERT INTO billing_invoice_audit(operation, old_data, app_user)
                    VALUES ('D', row_to_json(OLD), app_user);
                ELSIF TG_TABLE_NAME = 'verifactu_verifactunotification' THEN
                    INSERT INTO verifactu_verifactunotification_audit(operation, old_data, app_user)
                    VALUES ('D', row_to_json(OLD), app_user);
                END IF;
                RETURN OLD;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
        """),

        # -----------------------------
        # 4️⃣ Create trigger for billing_invoice
        # -----------------------------
        migrations.RunSQL("""
        DROP TRIGGER IF EXISTS billing_invoice_audit_trigger ON billing_invoice;
        CREATE TRIGGER billing_invoice_audit_trigger
        AFTER INSERT OR UPDATE OR DELETE ON billing_invoice
        FOR EACH ROW EXECUTE FUNCTION audit_table_changes();
        """),

        # -----------------------------
        # 5️⃣ Create trigger for verifactu_verifactunotification
        # -----------------------------
        migrations.RunSQL("""
        DROP TRIGGER IF EXISTS verifactu_verifactunotification_audit_trigger ON verifactu_verifactunotification;
        CREATE TRIGGER verifactu_verifactunotification_audit_trigger
        AFTER INSERT OR UPDATE OR DELETE ON verifactu_verifactunotification
        FOR EACH ROW EXECUTE FUNCTION audit_table_changes();
        """),
    ]
