# Generated by Django 5.0.4 on 2024-06-21 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_current_status', to='service.connectionstatus')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_previous_status', to='service.connectionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
