# Generated by Django 5.0.4 on 2024-07-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
        ('service', '0014_clusterobservation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logconnection',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_current_status', to='service.connectionrequeststatus')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_previous_status', to='service.connectionrequeststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
