# Generated by Django 5.0.4 on 2024-07-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_logconnection_observation_logconnectionrequest'),
        ('service', '0018_remove_meter_supply_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logconnectionrequest',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='logconnectionrequest',
            name='previous_status',
        ),
        migrations.RemoveField(
            model_name='logconnectionrequest',
            name='user',
        ),
        migrations.CreateModel(
            name='LogConnectionRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_current_status', to='service.connectionrequeststatus')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionrequest')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_previous_status', to='service.connectionrequeststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_current_status', to='service.connectionstatus')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connection')),
                ('previous_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_previous_status', to='service.connectionstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LogConnection',
        ),
        migrations.DeleteModel(
            name='LogConnectionRequest',
        ),
    ]
