# Generated by Django 5.0.4 on 2024-07-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_remove_logconnectionrequest_current_status_and_more'),
        ('service', '0018_remove_meter_supply_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logconnectionrequeststatus',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='service.connectionrequeststatus'),
        ),
        migrations.AlterField(
            model_name='logconnectionrequeststatus',
            name='previous_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='service.connectionrequeststatus'),
        ),
        migrations.AlterField(
            model_name='logconnectionrequeststatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logconnectionstatus',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='service.connectionstatus'),
        ),
        migrations.AlterField(
            model_name='logconnectionstatus',
            name='previous_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='service.connectionstatus'),
        ),
        migrations.AlterField(
            model_name='logconnectionstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LogClusterNozzleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='service.clusternozzlestatus')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.clusternozzle')),
                ('previous_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='service.clusternozzlestatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogClusterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='service.clusterstatus')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.cluster')),
                ('previous_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='service.clusterstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
