# Generated by Django 5.0.8 on 2024-10-08 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_logsupplypointchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('activate', 'Activació'), ('deactivate', 'Baixa'), ('person', 'Canvi de persona'), ('address', "Canvi d'adreça")], max_length=50)),
                ('field_changed', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('previous_related_id', models.IntegerField(blank=True, null=True)),
                ('current_related_id', models.IntegerField(blank=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
