# Generated by Django 5.0.8 on 2025-01-20 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0137_contract_total_persons_contractrequest_total_persons'),
        ('logger', '0011_logbailstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogContractTotalMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_total_persons', models.IntegerField(blank=True, null=True)),
                ('current_total_persons', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
