# Generated by Django 5.0.8 on 2025-01-21 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0139_bonification_end_at_bonification_start_at_and_more'),
        ('logger', '0012_logcontracttotalmembers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogContractBonificationsVariablesChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
                ('current_bonification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_bonification', to='contract.bonification')),
                ('current_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_variable', to='contract.variable')),
                ('previous_bonification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_bonification', to='contract.bonification')),
                ('previous_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_variable', to='contract.variable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
