# Generated by Django 5.0.8 on 2025-01-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_logcontractbonificationsvariableschange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logcontractbonificationsvariableschange',
            old_name='contract',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='logcontracttotalmembers',
            old_name='contract',
            new_name='object',
        ),
    ]
