# Generated by Django 5.0.8 on 2025-01-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0146_contractrequest_contract_file_template'),
        ('logger', '0014_rename_contract_logcontractbonificationsvariableschange_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogContractExpiredBonificationsVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expired_bonification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_expired_bonification', to='contract.bonification')),
                ('expired_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_expired_bonification', to='contract.variable')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
            ],
        ),
    ]
