# Generated by Django 5.0.8 on 2025-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0015_logcontractexpiredbonificationsvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcontractexpiredbonificationsvariables',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
