# Generated by Django 5.0.8 on 2025-03-12 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0098_claimrequest_check_without_debt'),
        ('contract', '0159_contractrequest_debt_management'),
        ('logger', '0016_logcontractexpiredbonificationsvariables_expiring_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogClaimRequestContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_debt_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_debt_management', to='contract.contractdebtmanagement')),
                ('deleted_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_deleted_contract', to='contract.contract')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.claimrequest')),
                ('previous_debt_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_debt_management', to='contract.contractdebtmanagement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
