# Generated by Django 5.0.8 on 2025-03-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0017_logclaimrequestcontractchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logclaimrequestcontractchange',
            name='previous_debt_management',
        ),
    ]
