# Generated by Django 5.0.8 on 2025-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0018_remove_logclaimrequestcontractchange_previous_debt_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='logclaimrequestcontractchange',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
