# Generated by Django 5.0.8 on 2025-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0020_loginvoicechangestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
