# Generated by Django 5.0.8 on 2025-03-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0113_deliquencyrequest_endowment_date'),
        ('contract', '0159_contractrequest_debt_management'),
        ('logger', '0021_alter_logclaimrequestcontractchange_amount_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDeliquencyRequestUnendowment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.deliquencyrequest')),
                ('previous_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='contract.contract')),
                ('previous_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='billing.invoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
