# Generated by Django 5.0.8 on 2025-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0113_deliquencyrequest_endowment_date'),
        ('contract', '0159_contractrequest_debt_management'),
        ('logger', '0022_logdeliquencyrequestunendowment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdeliquencyrequestunendowment',
            name='previous_contract',
        ),
        migrations.RemoveField(
            model_name='logdeliquencyrequestunendowment',
            name='previous_invoice',
        ),
        migrations.AddField(
            model_name='logdeliquencyrequestunendowment',
            name='previous_contracts',
            field=models.ManyToManyField(blank=True, related_name='log_previous_contracts', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='logdeliquencyrequestunendowment',
            name='previous_invoices',
            field=models.ManyToManyField(blank=True, related_name='log_previous_invoices', to='billing.invoice'),
        ),
    ]
