# Generated by Django 5.0.8 on 2025-03-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0113_deliquencyrequest_endowment_date'),
        ('logger', '0023_remove_logdeliquencyrequestunendowment_previous_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdeliquencyrequestunendowment',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.deliquencyrequest'),
        ),
    ]
