# Generated by Django 5.0.8 on 2025-03-27 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0115_walletmanagementstatus_walletmanagement_status'),
        ('contract', '0159_contractrequest_debt_management'),
        ('logger', '0024_alter_logdeliquencyrequestunendowment_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogDeliquencyRequestUnendowment',
            new_name='LogDeliquencyRequestDisendowment',
        ),
    ]
