# Generated by Django 5.0.8 on 2025-04-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0025_rename_logdeliquencyrequestunendowment_logdeliquencyrequestdisendowment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogDeliquencyRequestDisendowment',
        ),
    ]
