# Generated by Django 5.0.8 on 2025-04-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0130_claimrequest_previous_step_due_date'),
        ('logger', '0026_delete_logdeliquencyrequestdisendowment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logclaimrequestcontractchange',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='billing.claimrequeststatus'),
        ),
        migrations.AddField(
            model_name='logclaimrequestcontractchange',
            name='previous_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='billing.claimrequeststatus'),
        ),
    ]
