# Generated by Django 5.0.8 on 2025-04-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0133_claimrequestpayment_is_excluded_and_more'),
        ('contract', '0159_contractrequest_debt_management'),
        ('logger', '0027_logclaimrequestcontractchange_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='logclaimrequestcontractchange',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='logclaimrequestcontractchange',
            name='observation',
        ),
        migrations.AddField(
            model_name='logclaimrequestcontractchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='current_debt_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractdebtmanagement'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status_logs', to='billing.claimrequeststatus'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='deleted_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.claimrequest'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_status_logs', to='billing.claimrequeststatus'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
