# Generated by Django 5.0.8 on 2025-04-23 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0136_commitmentdeposit_holder'),
        ('logger', '0027_logclaimrequestcontractchange_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCommitmentDepositMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('used_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='billing.commitmentdepositstatus')),
                ('new_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_new_payment', to='billing.paymentcommitment')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.commitmentdeposit')),
                ('paid_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_paid_invoice', to='billing.invoice')),
                ('previous_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='billing.commitmentdepositstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
