# Generated by Django 5.0.8 on 2025-04-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0001_initial'),
        ('logger', '0028_rename_timestamp_logclaimrequestcontractchange_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status_logs', to='claimrequest.claimrequeststatus'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claimrequest.claimrequest'),
        ),
        migrations.AlterField(
            model_name='logclaimrequestcontractchange',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_status_logs', to='claimrequest.claimrequeststatus'),
        ),
    ]
