# Generated by Django 5.0.8 on 2025-04-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0136_commitmentdeposit_holder'),
        ('logger', '0028_logcommitmentdepositmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcommitmentdepositmovement',
            name='paid_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_paid_invoice', to='billing.invoice'),
        ),
    ]
