# Generated by Django 5.0.8 on 2025-04-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0136_commitmentdeposit_holder'),
        ('logger', '0029_alter_logcommitmentdepositmovement_paid_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcommitmentdepositmovement',
            name='new_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_new_payment', to='billing.paymentcommitment'),
        ),
    ]
