# Generated by Django 5.0.8 on 2025-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0141_paymentcommitment_is_guide'),
        ('logger', '0030_alter_logcommitmentdepositmovement_new_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommitmentdepositmovement',
            name='new_invoices',
            field=models.ManyToManyField(blank=True, related_name='log_new_invoices', to='billing.invoice'),
        ),
    ]
