# Generated by Django 5.0.8 on 2025-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0029_alter_logclaimrequestcontractchange_current_status_and_more'),
        ('logger', '0031_logcommitmentdepositmovement_new_invoices'),
    ]

    operations = [
    ]
