# Generated by Django 5.0.8 on 2025-04-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0161_alter_contract_communication_type'),
        ('logger', '0032_merge_20250428_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommitmentdepositmovement',
            name='current_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_payment_type', to='contract.paymenttype'),
        ),
        migrations.AddField(
            model_name='logcommitmentdepositmovement',
            name='previous_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_payment_type', to='contract.paymenttype'),
        ),
    ]
