# Generated by Django 5.0.8 on 2025-04-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0033_logcommitmentdepositmovement_current_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcommitmentdepositmovement',
            name='current_payment_type',
        ),
        migrations.RemoveField(
            model_name='logcommitmentdepositmovement',
            name='previous_payment_type',
        ),
    ]
