# Generated by Django 5.0.8 on 2025-04-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0150_paymentcommitment_payment_bank_final_and_more'),
        ('logger', '0034_remove_logcommitmentdepositmovement_current_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommitmentdepositmovement',
            name='new_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_new_wallet', to='billing.payment'),
        ),
    ]
