# Generated by Django 5.0.8 on 2025-05-09 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_alter_fraud_detection_date'),
        ('logger', '0036_logpaymentstatuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFraudStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_current_status', to='fraud.fraudstatus')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fraud.fraud')),
                ('previous_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_previous_status', to='fraud.fraudstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
