# Generated by Django 5.0.8 on 2025-05-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0161_alter_invoicelineitem_line_item_type_and_more'),
        ('logger', '0037_logfraudstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcommitmentdepositmovement',
            name='paid_invoice_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_paid_payment', to='billing.payment'),
        ),
    ]
