# Generated by Django 5.0.8 on 2025-05-21 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0039_logincidentstatus'),
        ('notification', '0010_incidentobservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogIncidentStatus',
            new_name='LogIncidentStatusChange',
        ),
    ]
