# Generated by Django 5.0.8 on 2025-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0041_logcommunicationprocessstatuschange_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogSupplyPointRequestStatus',
        ),
    ]
