# Generated by Django 5.0.8 on 2025-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0042_delete_logsupplypointrequeststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcontractchange',
            name='action',
            field=models.CharField(choices=[('activate', 'Activació'), ('deactivate', 'Baixa'), ('person', 'Canvi de persona'), ('address', "Canvi d'adreça"), ('communication_type', 'Canvi de tipus de comunicació')], max_length=50),
        ),
    ]
