# Generated by Django 5.0.8 on 2025-10-29 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0221_invoice_is_general'),
        ('logger', '0043_alter_logcontractchange_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInvoiceDataChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_address', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('current_payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
