# Generated by Django 5.0.8 on 2026-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0044_loginvoicedatachange'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpaymentstatuschange',
            name='used_payment_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
