# Generated by Django 5.0.8 on 2026-04-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0045_logpaymentstatuschange_used_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupplypointchange',
            name='action',
            field=models.CharField(choices=[('activate', 'Activació'), ('deactivate', 'Baixa'), ('meter', 'Canvi de comptador'), ('address', "Canvi d'adreça"), ('connection', "Canvi d'escomesa"), ('property', 'Canvi de propietat')], max_length=50),
        ),
    ]
