# Generated by Django 5.0.8 on 2026-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0047_logjoinedpaymentstatuschange'),
        ('logger', '0047_logreadingchange'),
    ]

    operations = [
    ]
