# Generated by Django 5.0.8 on 2026-05-27 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_communicationusetype_communication_readings_and_more'),
        ('logger', '0048_merge_20260518_1033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCommunicationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_used_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('current_used_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_used_phones', models.CharField(blank=True, max_length=255, null=True)),
                ('current_used_phones', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_used_addresses', models.CharField(blank=True, max_length=255, null=True)),
                ('current_used_addresses', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('current_types', models.ManyToManyField(blank=True, related_name='log_current_use_types', to='communication.messagetype')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communication')),
                ('previous_types', models.ManyToManyField(blank=True, related_name='log_previous_use_types', to='communication.messagetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
