# Generated by Django 5.0.8 on 2026-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0048_merge_20260518_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginvoicedatachange',
            name='current_iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginvoicedatachange',
            name='previous_iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
