# Generated by Django 5.0.8 on 2026-05-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0049_logcommunicationchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='current_used_addresses',
            new_name='current_used_addresse',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='current_used_emails',
            new_name='current_used_email',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='current_used_phones',
            new_name='current_used_phone',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='previous_used_addresses',
            new_name='previous_used_addresse',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='previous_used_emails',
            new_name='previous_used_email',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='previous_used_phones',
            new_name='previous_used_phone',
        ),
    ]
