# Generated by Django 5.0.8 on 2026-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0050_rename_current_used_addresses_logcommunicationchange_current_used_addresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='current_used_addresse',
            new_name='current_used_address',
        ),
        migrations.RenameField(
            model_name='logcommunicationchange',
            old_name='previous_used_addresse',
            new_name='previous_used_address',
        ),
    ]
