# Generated by Django 5.0.8 on 2026-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0050_logcontractphones'),
        ('logger', '0051_rename_current_used_addresse_logcommunicationchange_current_used_address_and_more'),
    ]

    operations = [
    ]
