# Generated by Django 5.0.8 on 2026-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0053_logpriceratechange_logproductchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpriceratechange',
            name='line_item_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
