# Generated by Django 5.0.8 on 2025-01-17 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('found', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('found_field', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
