# Generated by Django 5.0.8 on 2024-12-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0124_remove_contract_cnae_contract_cnaes_and_more'),
        ('pricing', '0026_delete_lineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('customer_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_token_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('address_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('city_country_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type_fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_bank_fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_iban_fixed', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sended', models.BooleanField(default=False)),
                ('sended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('name_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('description_fixed', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_fixed', models.IntegerField(blank=True, null=True)),
                ('price_unit_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_price_fixed', models.FloatField(blank=True, null=True)),
                ('total_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('line_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.lineitemtype')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.tax')),
            ],
        ),
    ]
