# Generated by Django 5.0.8 on 2024-12-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('contract', '0126_merge_20241212_0839'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='address_fixed',
            new_name='address_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='city_country_fixed',
            new_name='customer_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_fixed',
            new_name='customer_token_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_confirm',
            new_name='is_confirmed',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_sended',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_token_fixed',
            new_name='location_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_bank_fixed',
            new_name='payment_bank_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_iban_fixed',
            new_name='payment_iban_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_type_fixed',
            new_name='payment_type_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sended_at',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='subtotal_fixed',
            new_name='subtotal_final',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_fixed',
            new_name='total_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='description_fixed',
            new_name='description_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='name_fixed',
            new_name='name_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='price_unit_fixed',
            new_name='price_unit_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='quantity_fixed',
            new_name='quantity_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='tax_percent_fixed',
            new_name='tax_percent_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='tax_price_fixed',
            new_name='tax_price_final',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='total_fixed',
            new_name='total_final',
        ),
        migrations.AddField(
            model_name='invoice',
            name='serie_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.paymenttype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.invoiceserie'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_estimated', models.BooleanField(default=False)),
                ('alert_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meter')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.readingalert')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.readingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meter')),
            ],
        ),
    ]
