# Generated by Django 5.0.8 on 2024-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceserie_readingalert_readingbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
