# Generated by Django 5.0.8 on 2024-12-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_title_final'),
        ('contract', '0126_merge_20241212_0839'),
        ('pricing', '0029_tax'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.taxes'),
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='is_estimated',
            new_name='is_control',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='alert_notes',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reading',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReadingBatchReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_estimated', models.BooleanField(default=False)),
                ('alert_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.readingalert')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.readingbatch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meter')),
            ],
        ),
        migrations.DeleteModel(
            name='ReadingPending',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
