# Generated by Django 5.0.8 on 2024-12-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoicelineitem_tax_and_more'),
        ('pricing', '0030_remove_lineitemtype_taxes_lineitemtype_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.tax'),
        ),
    ]
