# Generated by Django 5.0.8 on 2024-12-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoicelineitem_tax'),
        ('contract', '0127_remove_contract_price_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingbatchreading',
            name='is_estimated',
        ),
        migrations.RemoveField(
            model_name='readingbatchreading',
            name='reading_date',
        ),
        migrations.RemoveField(
            model_name='readingbatchreading',
            name='reading_value',
        ),
        migrations.AddField(
            model_name='reading',
            name='is_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingbatchreading',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.reading'),
        ),
        migrations.AlterField(
            model_name='readingbatchreading',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.readingbatch'),
        ),
        migrations.AlterField(
            model_name='readingbatchreading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
