# Generated by Django 5.0.8 on 2024-12-17 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_readingbatchreading_is_estimated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.readingalert'),
        ),
        migrations.AddField(
            model_name='reading',
            name='alert_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.readingbatch'),
        ),
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReadingBatchReading',
        ),
    ]
