# Generated by Django 5.0.8 on 2024-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_reading_alert_reading_alert_notes_reading_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
