# Generated by Django 5.0.8 on 2024-12-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_company_invoice_exploitation_payment_token_and_more'),
        ('contract', '0127_remove_contract_price_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
