# Generated by Django 5.0.8 on 2024-12-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_reading_contract'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.meter'),
        ),
    ]
