# Generated by Django 5.0.8 on 2024-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoicebatch_invoice_invoice_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
