# Generated by Django 5.0.8 on 2024-12-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='price_unit_final',
            new_name='price_unit',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='tax_percent_final',
            new_name='tax_percent',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='tax_price_final',
            new_name='tax_price',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='total_final',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='quantity_final',
            new_name='units',
        ),
    ]
