# Generated by Django 5.0.8 on 2024-12-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_invoicelineitem_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='description_final',
            new_name='description',
        ),
    ]
