# Generated by Django 5.0.8 on 2024-12-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_rename_description_final_invoicelineitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='name_final',
            new_name='name',
        ),
    ]
