# Generated by Django 5.0.8 on 2024-12-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_rename_name_final_invoicelineitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='type',
            field=models.CharField(choices=[('ROUTE', 'Ruta'), ('DATE', 'Data')], default='DATE'),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.readingbatchstatus'),
        ),
    ]
