# Generated by Django 5.0.8 on 2024-12-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_rename_name_final_invoicelineitem_name'),
        ('pricing', '0056_rename_proration_lineitemtype_is_prorated'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.pricerate'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='price_rate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.product'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
