# Generated by Django 5.0.8 on 2024-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_readingbatchstatus_readingbatch_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingroute',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
    ]
