# Generated by Django 5.0.8 on 2024-12-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_invoicelineitem_price_rate_and_more'),
        ('pricing', '0056_rename_proration_lineitemtype_is_prorated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.lineitemtype'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.product'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.tax'),
        ),
    ]
