# Generated by Django 5.0.8 on 2024-12-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_readingroute_is_control'),
        ('order', '0012_order_contract_termination_request'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingroute',
            name='reading_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_routes', to='billing.readingbatch'),
        ),
        migrations.AlterField(
            model_name='readingroute',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.operator'),
        ),
        migrations.AlterField(
            model_name='readingroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.route'),
        ),
    ]
