# Generated by Django 5.0.8 on 2024-12-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_invoicelineitem_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice'),
        ),
    ]
