# Generated by Django 5.0.8 on 2024-12-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_invoicelineitem_invoice'),
        ('billing', '0020_readingroute_reading_batch_and_more'),
    ]

    operations = [
    ]
