# Generated by Django 5.0.8 on 2025-01-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_merge_20241224_1244'),
        ('contract', '0128_alter_contractterminationrequest_status_and_more'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='previous_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.reading'),
        ),
        migrations.AddField(
            model_name='reading',
            name='supply_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypoint'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.exploitation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoicebatch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoiceserie'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.readingalert'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='billing.readingbatch'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.meter'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='billing.readingroute'),
        ),
    ]
