# Generated by Django 5.0.8 on 2025-01-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_reading_previous_reading_reading_supply_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='calculated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
