# Generated by Django 5.0.8 on 2025-01-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_invoicetemplate_invoicelineitem_company_and_more'),
        ('billing', '0023_reading_calculated_value'),
    ]

    operations = [
    ]
