# Generated by Django 5.0.8 on 2025-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_merge_20250113_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='price_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
