# Generated by Django 5.0.8 on 2025-01-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_invoicelineitem_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingbatch',
            name='status',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.readingbatchstatus'),
        ),
    ]
