# Generated by Django 5.0.8 on 2025-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_invoicelineitem_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consumption_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
