# Generated by Django 5.0.8 on 2025-01-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_invoice_consumption_invoice_consumption_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.reading'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reading_last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_last', to='billing.reading'),
        ),
    ]
