# Generated by Django 5.0.8 on 2025-01-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_invoice_consumption_invoice_consumption_days'),
        ('billing', '0027_alter_readingbatch_status'),
    ]

    operations = [
    ]
