# Generated by Django 5.0.8 on 2025-01-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_readingbatch_status'),
        ('billing', '0027_invoice_reading_invoice_reading_last'),
    ]

    operations = [
    ]
