# Generated by Django 5.0.8 on 2025-01-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_merge_20250116_1451'),
        ('billing', '0028_merge_20250117_0830'),
    ]

    operations = [
    ]
