# Generated by Django 5.0.8 on 2025-01-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_invoice_reading_invoice_reading_last'),
        ('billing', '0028_merge_20250116_1451'),
    ]

    operations = [
    ]
