# Generated by Django 5.0.8 on 2025-01-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_merge_20250117_1046'),
        ('billing', '0029_merge_20250117_1051'),
    ]

    operations = [
    ]
