# Generated by Django 5.0.8 on 2025-01-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_merge_20250120_1310'),
        ('contract', '0141_variabletype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequest'),
        ),
    ]
