# Generated by Django 5.0.8 on 2025-01-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_invoice_contract_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_registration',
            field=models.BooleanField(default=False),
        ),
    ]
