# Generated by Django 5.0.8 on 2025-01-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_invoice_is_registration'),
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbank'),
        ),
    ]
