# Generated by Django 5.0.8 on 2025-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_invoice_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
