# Generated by Django 5.0.8 on 2025-01-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_readingbatch_is_excluded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceBatch',
            new_name='BillingBatch',
        ),
    ]
