# Generated by Django 5.0.8 on 2025-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_rename_invoicebatch_billingbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='consumption_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
