# Generated by Django 5.0.8 on 2025-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_invoicetype_invoice_type_final_payment_payment_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='split_payments',
            field=models.ManyToManyField(blank=True, to='billing.payment'),
        ),
    ]
