# Generated by Django 5.0.8 on 2025-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_payment_is_split_payment_split_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
