# Generated by Django 5.0.8 on 2025-02-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_invoice_is_paid_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
