# Generated by Django 5.0.8 on 2025-02-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_payment_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
