# Generated by Django 5.0.8 on 2025-02-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_reading_consumption_days'),
        ('billing', '0041_invoice_is_late'),
    ]

    operations = [
    ]
