# Generated by Django 5.0.8 on 2025-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_merge_20250205_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_batch',
            new_name='batch',
        ),
    ]
