# Generated by Django 5.0.8 on 2025-02-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_merge_20250204_1340'),
        ('billing', '0043_paymentstatus_remove_payment_is_late_and_more'),
    ]

    operations = [
    ]
