# Generated by Django 5.0.8 on 2025-02-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_rename_invoice_batch_invoice_batch'),
        ('billing', '0044_merge_20250205_1124'),
    ]

    operations = [
    ]
