# Generated by Django 5.0.8 on 2025-02-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_merge_20250205_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paymentstatus'),
        ),
    ]
