# Generated by Django 5.0.8 on 2025-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_remove_invoice_is_late_remove_invoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='surcharge',
            field=models.ManyToManyField(blank=True, to='billing.invoice'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoices', models.ManyToManyField(blank=True, related_name='messages', to='billing.invoice')),
            ],
        ),
    ]
