# Generated by Django 5.0.8 on 2025-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_merge_20250205_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingbatch',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
