# Generated by Django 5.0.8 on 2025-02-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_invoice_surcharge_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='surcharge',
            new_name='surcharges',
        ),
    ]
