# Generated by Django 5.0.8 on 2025-02-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_merge_20250205_1126'),
        ('billing', '0047_rename_surcharge_invoice_surcharges'),
    ]

    operations = [
    ]
