# Generated by Django 5.0.8 on 2025-02-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0048_merge_20250205_1423'),
        ('billing', '0048_merge_20250205_1525'),
    ]

    operations = [
    ]
