# Generated by Django 5.0.8 on 2025-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_merge_20250206_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSEPALine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('payments', models.ManyToManyField(blank=True, related_name='sepa_lines', to='billing.payment')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSEPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lines', models.ManyToManyField(blank=True, related_name='sepas', to='billing.documentsepaline')),
            ],
        ),
    ]
