# Generated by Django 5.0.8 on 2025-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0050_documentsepaline_documentsepa'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
