# Generated by Django 5.0.8 on 2025-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0052_invoicestatus_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='persons_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='responsible_consumption',
            field=models.BooleanField(default=True),
        ),
    ]
