# Generated by Django 5.0.8 on 2025-02-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_merge_20250206_0826'),
        ('billing', '0053_invoice_persons_final_and_more'),
    ]

    operations = [
    ]
