# Generated by Django 5.0.8 on 2025-02-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_billingbatchstatus_alter_invoice_batch_and_more'),
        ('billing', '0055_alter_invoice_address_final_and_more'),
    ]

    operations = [
    ]
