# Generated by Django 5.0.8 on 2025-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0056_merge_20250206_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_swift_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
