# Generated by Django 5.0.8 on 2025-02-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0057_biller_billing_billingbatchtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='period_type',
            field=models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('mensual', 'Mensual')], default='trimestral'),
        ),
        migrations.AddField(
            model_name='billingbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingbatchtemplate'),
        ),
    ]
