# Generated by Django 5.0.8 on 2025-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0057_invoice_payment_swift_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
