# Generated by Django 5.0.8 on 2025-02-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_payment_payment_swift'),
        ('documentmanager', '0007_alter_document_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsepa',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document'),
        ),
    ]
