# Generated by Django 5.0.8 on 2025-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_biller_period_type_billingbatch_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='initial_month',
            field=models.CharField(choices=[('jan', 'Gener'), ('feb', 'Febrer'), ('mar', 'Març'), ('apr', 'Abril'), ('may', 'Maig'), ('jun', 'Juny'), ('jul', 'Juliol'), ('aug', 'Agost'), ('sep', 'Setembre'), ('oct', 'Octubre'), ('nov', 'Novembre'), ('dec', 'Desembre')], default='jan'),
        ),
    ]
