# Generated by Django 5.0.8 on 2025-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_documentsepa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
