# Generated by Django 5.0.8 on 2025-02-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_payment_is_anomaly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_anomaly',
            new_name='is_excluded',
        ),
    ]
