# Generated by Django 5.0.8 on 2025-02-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0061_rename_is_anomaly_payment_is_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serie_final',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
