# Generated by Django 5.0.8 on 2025-02-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_alter_invoice_serie_final'),
        ('pricing', '0076_alter_productorigin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('GRAPHIC', 'Gràfic')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to='pricing.productorigin')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.messagetemplate'),
        ),
    ]
