# Generated by Django 5.0.8 on 2025-02-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0063_message_end_at_message_message_type_message_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoicetemplate'),
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
