# Generated by Django 5.0.8 on 2025-02-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0064_alter_message_template_delete_messagetemplate'),
        ('pricing', '0076_alter_productorigin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_templates', to='pricing.productorigin'),
        ),
    ]
