# Generated by Django 5.0.8 on 2025-02-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0065_invoicetemplate_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.JSONField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('eq', 'Equal'), ('ne', 'Not Equal'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('ge', 'Greater or Equal'), ('le', 'Less or Equal'), ('in', 'In'), ('ni', 'Not In'), ('is_true', 'Is True'), ('is_false', 'Is False'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], default='eq')),
                ('formula', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.message')),
            ],
        ),
    ]
