# Generated by Django 5.0.8 on 2025-02-18 13:53

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0066_messagecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_file_template',
            field=models.FileField(blank=True, null=True, upload_to=billing.models.invoice_request_upload_to),
        ),
        migrations.AlterField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='billing.invoicetemplate'),
        ),
        migrations.AlterField(
            model_name='messagecondition',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='billing.message'),
        ),
    ]
