# Generated by Django 5.0.8 on 2025-02-19 15:25

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0067_invoice_invoice_file_template_alter_message_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file_template',
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='invoice_file_template',
            field=models.FileField(blank=True, null=True, upload_to=billing.models.invoice_request_upload_to),
        ),
    ]
