# Generated by Django 5.0.8 on 2025-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0069_remove_invoicetemplate_invoice_file_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='file_template',
            field=models.FileField(blank=True, null=True, upload_to='billing/templates/'),
        ),
    ]
