# Generated by Django 5.0.8 on 2025-02-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_biller_initial_month'),
        ('billing', '0070_invoicetemplate_file_template'),
    ]

    operations = [
    ]
