# Generated by Django 5.0.8 on 2025-02-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0070_invoicetemplate_file_template'),
        ('documentmanager', '0007_alter_document_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='file_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document'),
        ),
    ]
