# Generated by Django 5.0.8 on 2025-02-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_merge_20250220_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingbatch',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billing'),
        ),
        migrations.AlterField(
            model_name='billingbatchtemplate',
            name='biller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_batch_templates', to='billing.biller'),
        ),
    ]
