# Generated by Django 5.0.8 on 2025-02-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_alter_invoicetemplate_file_template'),
        ('billing', '0071_merge_20250220_0846'),
    ]

    operations = [
    ]
