# Generated by Django 5.0.8 on 2025-02-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_merge_20250221_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsepa',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='sepa_document', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='billingbatchtemplate',
            name='biller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_batch_templates', to='billing.biller'),
        ),
    ]
