# Generated by Django 5.0.8 on 2025-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_billingbatch_billing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingbatch',
            name='task_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
