# Generated by Django 5.0.8 on 2025-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0073_documentsepa_invoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsepa',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='sepa_documents', to='billing.invoice'),
        ),
    ]
