# Generated by Django 5.0.8 on 2025-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0075_rejectmotive_invoice_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsepa',
            name='msgId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
