# Generated by Django 5.0.8 on 2025-02-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0076_documentsepa_msgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.rejectmotive'),
        ),
        migrations.AlterField(
            model_name='documentsepa',
            name='msgId',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
