# Generated by Django 5.0.8 on 2025-02-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0074_billingstatus_alter_billingbatch_billing_and_more'),
        ('billing', '0077_payment_reject_alter_documentsepa_msgid'),
    ]

    operations = [
    ]
