# Generated by Django 5.0.8 on 2025-02-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0077_payment_reject_alter_documentsepa_msgid'),
        ('service', '0063_connectionrequest_address_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connection'),
        ),
    ]
