# Generated by Django 5.0.8 on 2025-02-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0078_invoice_connection'),
        ('billing', '0078_merge_20250228_0942'),
    ]

    operations = [
    ]
