# Generated by Django 5.0.8 on 2025-02-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0079_merge_20250228_1123'),
        ('contract', '0153_contract_remittance_date_and_more'),
        ('coredata', '0049_auto_20250130_1446'),
        ('service', '0063_connectionrequest_address_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IBAN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbank', verbose_name='General Payment Bank')),
                ('company_iban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.companybank', verbose_name='General Payment Bank')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype', verbose_name='General Payment Type')),
            ],
        ),
    ]
