# Generated by Django 5.0.8 on 2025-03-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0080_generalpayment'),
        ('coredata', '0049_auto_20250130_1446'),
        ('service', '0065_connectionrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='connection_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionrequest'),
        ),
        migrations.AlterField(
            model_name='generalpayment',
            name='IBAN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbank', verbose_name='General Payment Person'),
        ),
        migrations.AlterField(
            model_name='generalpayment',
            name='company_iban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.companybank', verbose_name='General Payment Company'),
        ),
    ]
