# Generated by Django 5.0.8 on 2025-03-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0081_invoice_connection_request_alter_generalpayment_iban_and_more'),
        ('service', '0065_connectionrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_company_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.companybank'),
        ),
    ]
