# Generated by Django 5.0.8 on 2025-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_generalpayment_accounting_office_generalpayment_dir3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
