# Generated by Django 5.0.8 on 2025-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0084_invoice_payment_type_token_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_is_juridic',
            field=models.BooleanField(default=False),
        ),
    ]
