# Generated by Django 5.0.8 on 2025-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0085_invoice_customer_is_juridic'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
