# Generated by Django 5.0.8 on 2025-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0086_invoice_country_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='city_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_email_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_tlf_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='postal_code_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='province_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='serie_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
