# Generated by Django 5.0.8 on 2025-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0087_invoice_city_final_invoice_customer_email_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
