# Generated by Django 5.0.8 on 2025-03-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0088_invoiceclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoiceclass'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_class_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
