# Generated by Django 5.0.8 on 2025-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0090_claimdocumenttype_claimrequeststatus_claimsteptype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstep',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
