# Generated by Django 5.0.8 on 2025-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0091_claimstep_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimstep',
            name='type',
        ),
        migrations.AddField(
            model_name='claimstep',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
