# Generated by Django 5.0.8 on 2025-03-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0092_remove_claimstep_type_claimstep_name'),
        ('order', '0016_merge_20250304_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimStepType',
        ),
        migrations.RemoveField(
            model_name='claimstep',
            name='order',
        ),
        migrations.AddField(
            model_name='claimstep',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordertype'),
        ),
    ]
