# Generated by Django 5.0.8 on 2025-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0093_delete_claimsteptype_remove_claimstep_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
