# Generated by Django 5.0.8 on 2025-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0094_claimstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstep',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('WORK', 'Hábils'), ('NATURAL', 'Naturals')], default='WORK', max_length=255, null=True),
        ),
    ]
