# Generated by Django 5.0.8 on 2025-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0095_claimstep_duration_type'),
        ('contract', '0159_contractrequest_debt_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='contracts',
            field=models.ManyToManyField(blank=True, related_name='claims', to='contract.contract'),
        ),
    ]
