# Generated by Django 5.0.8 on 2025-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0096_claimrequest_contracts'),
        ('contract', '0159_contractrequest_debt_management'),
        ('service', '0066_merge_20250304_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='client_types',
            field=models.ManyToManyField(blank=True, related_name='claims', to='contract.contractclienttype'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='debt_managements',
            field=models.ManyToManyField(blank=True, related_name='claims', to='contract.contractdebtmanagement'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='claims', to='contract.contractstatus'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='use_types',
            field=models.ManyToManyField(blank=True, related_name='claims', to='contract.contractusetype'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='claims', to='service.routezone'),
        ),
    ]
