# Generated by Django 5.0.8 on 2025-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0097_claimrequest_client_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='check_without_debt',
            field=models.BooleanField(default=False),
        ),
    ]
