# Generated by Django 5.0.8 on 2025-03-13 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0098_claimrequest_check_without_debt'),
        ('service', '0071_remove_company_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='excluded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billing'),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='billings', to='service.route'),
        ),
        migrations.AddField(
            model_name='billingbatch',
            name='excluded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingbatch'),
        ),
        migrations.AddField(
            model_name='billingbatch',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='excluded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.readingbatch'),
        ),
        migrations.AddField(
            model_name='readingroute',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_routes', to='billing.billing'),
        ),
    ]
