# Generated by Django 5.0.8 on 2025-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0099_billing_excluded_from_billing_is_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='manually_modified',
            field=models.BooleanField(default=False),
        ),
    ]
