# Generated by Django 5.0.8 on 2025-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0100_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
