# Generated by Django 5.0.8 on 2025-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0101_invoicestatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='irrecoverable_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
