# Generated by Django 5.0.8 on 2025-03-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0102_invoice_irrecoverable_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='irrecoverable_reason',
            new_name='reason',
        ),
    ]
