# Generated by Django 5.0.8 on 2025-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0103_rename_irrecoverable_reason_invoice_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currently_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
