# Generated by Django 5.0.8 on 2025-03-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0104_invoice_currently_paid'),
        ('documentmanager', '0007_alter_document_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document'),
        ),
    ]
