# Generated by Django 5.0.8 on 2025-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0105_invoice_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='previous_step_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
