# Generated by Django 5.0.8 on 2025-03-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0100_invoicelineitem_manually_added_and_more'),
        ('billing', '0105_invoice_invoice_file'),
    ]

    operations = [
    ]
