# Generated by Django 5.0.8 on 2025-03-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0106_claimrequest_previous_step_date'),
        ('billing', '0106_merge_20250318_1420'),
    ]

    operations = [
    ]
