# Generated by Django 5.0.8 on 2025-03-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0107_merge_20250319_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manually_modified',
            field=models.BooleanField(default=False),
        ),
    ]
