# Generated by Django 5.0.8 on 2025-03-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0107_merge_20250319_0925'),
        ('service', '0071_remove_company_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('total_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supply_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypoint')),
            ],
        ),
    ]
