# Generated by Django 5.0.8 on 2025-03-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0108_invoice_manually_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='billing.invoice'),
        ),
    ]
