# Generated by Django 5.0.8 on 2025-03-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0108_estimatedbag'),
        ('coredata', '0059_merge_20250319_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedbag',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.person'),
        ),
    ]
