# Generated by Django 5.0.8 on 2025-03-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0109_estimatedbag_holder'),
        ('service', '0071_remove_company_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedbag',
            name='supply_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_bag', to='service.supplypoint'),
        ),
    ]
