# Generated by Django 5.0.8 on 2025-03-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0110_alter_estimatedbag_supply_point'),
        ('contract', '0159_contractrequest_debt_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliquencyRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliquencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('endowment_date', models.DateField(blank=True, null=True)),
                ('contracts', models.ManyToManyField(blank=True, related_name='delinquency_requests', to='contract.contract')),
                ('invoices', models.ManyToManyField(blank=True, related_name='delinquency_requests', to='billing.invoice')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.deliquencyrequeststatus')),
            ],
        ),
    ]
