# Generated by Django 5.0.8 on 2025-03-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0109_reading_invoice'),
        ('billing', '0110_alter_estimatedbag_supply_point'),
    ]

    operations = [
    ]
