# Generated by Django 5.0.8 on 2025-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0111_deliquencyrequeststatus_deliquencyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliquencyrequest',
            name='endowment_date',
        ),
    ]
