# Generated by Django 5.0.8 on 2025-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0112_remove_deliquencyrequest_endowment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliquencyrequest',
            name='endowment_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
