# Generated by Django 5.0.8 on 2025-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0111_merge_20250326_1427'),
        ('billing', '0113_deliquencyrequest_endowment_date'),
    ]

    operations = [
    ]
