# Generated by Django 5.0.8 on 2025-03-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0113_deliquencyrequest_endowment_date'),
        ('contract', '0159_contractrequest_debt_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WalletManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('total_import', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_import_cancelled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('bails', models.ManyToManyField(blank=True, related_name='wallets', to='contract.bail')),
                ('payments', models.ManyToManyField(blank=True, related_name='wallets', to='billing.payment')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.walletmanagementtype')),
            ],
        ),
    ]
