# Generated by Django 5.0.8 on 2025-03-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0115_walletmanagementstatus_walletmanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmanagement',
            name='deliquency_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.deliquencyrequest'),
        ),
    ]
