# Generated by Django 5.0.8 on 2025-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0117_walletmanagement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmanagement',
            name='total_import',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='walletmanagement',
            name='total_import_cancelled',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
