# Generated by Django 5.0.8 on 2025-03-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0118_alter_walletmanagement_total_import_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliquencyrequest',
            name='invoices',
        ),
        migrations.AddField(
            model_name='deliquencyrequest',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='delinquency_requests', to='billing.payment'),
        ),
    ]
