# Generated by Django 5.0.8 on 2025-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0119_remove_deliquencyrequest_invoices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='invoices',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='claims', to='billing.payment'),
        ),
    ]
