# Generated by Django 5.0.8 on 2025-03-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0120_remove_claimrequest_invoices_claimrequest_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='amount',
        ),
    ]
