# Generated by Django 5.0.8 on 2025-03-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0114_merge_20250327_1115'),
        ('billing', '0121_remove_claimrequest_amount'),
    ]

    operations = [
    ]
