# Generated by Django 5.0.8 on 2025-04-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0122_merge_20250331_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_invoices', to='billing.invoice'),
        ),
    ]
