# Generated by Django 5.0.8 on 2025-04-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0123_invoice_parent_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='surcharges',
        ),
    ]
