# Generated by Django 5.0.8 on 2025-04-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0124_remove_invoice_surcharges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletmanagement',
            name='bails',
        ),
        migrations.RemoveField(
            model_name='walletmanagement',
            name='deliquency_request',
        ),
        migrations.RemoveField(
            model_name='walletmanagement',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='walletmanagement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='walletmanagement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='walletmanagement',
            name='user',
        ),
        migrations.DeleteModel(
            name='WalletManagementStatus',
        ),
        migrations.DeleteModel(
            name='WalletManagementType',
        ),
        migrations.DeleteModel(
            name='WalletManagement',
        ),
    ]
