# Generated by Django 5.0.8 on 2025-04-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0125_remove_walletmanagement_bails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.paymentstatus'),
        ),
    ]
