# Generated by Django 5.0.8 on 2025-04-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0126_paymentstatus_description_alter_payment_status'),
        ('logger', '0026_delete_logdeliquencyrequestdisendowment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliquencyRequest',
        ),
        migrations.DeleteModel(
            name='DeliquencyRequestStatus',
        ),
    ]
