# Generated by Django 5.0.8 on 2025-04-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0127_delete_deliquencyrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_split',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='split_payments',
        ),
    ]
