# Generated by Django 5.0.8 on 2025-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0129_commitmentdepositstatus_paymentcommitmentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='previous_step_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
