# Generated by Django 5.0.8 on 2025-04-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0130_claimrequest_previous_step_due_date'),
        ('contract', '0159_contractrequest_debt_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='contracts',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='payments',
        ),
        migrations.CreateModel(
            name='ClaimRequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.claimrequest')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to='contract.contract')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to='billing.payment')),
            ],
        ),
    ]
