# Generated by Django 5.0.8 on 2025-04-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0131_invoicewarning_invoice_warning'),
        ('billing', '0131_remove_claimrequest_contracts_and_more'),
    ]

    operations = [
    ]
