# Generated by Django 5.0.8 on 2025-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0132_merge_20250415_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='simplified',
            field=models.BooleanField(default=False),
        ),
    ]
