# Generated by Django 5.0.8 on 2025-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0132_merge_20250415_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequestpayment',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimrequestpayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimrequestpayment',
            name='is_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
