# Generated by Django 5.0.8 on 2025-04-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0132_merge_20250415_1038'),
    ]

    operations = [
        # This is an empty migration.
    ]
