# Generated by Django 5.0.8 on 2025-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0133_remove_paymentcommitment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='days_next_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
