# Generated by Django 5.0.8 on 2025-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0133_claimrequestpayment_is_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstep',
            name='action_date_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
