# Generated by Django 5.0.8 on 2025-04-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0134_claimstep_action_date_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimstep',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='client_types',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='debt_managements',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='exploitation',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='step',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='use_types',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='claimrequestpayment',
            name='claim_request',
        ),
        migrations.RemoveField(
            model_name='claimrequestpayment',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='claimrequestpayment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='claimstep',
            name='next_step',
        ),
        migrations.RemoveField(
            model_name='claimstep',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='commitmentdeposit',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='commitmentdeposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentcommitment',
            name='commitment_deposit',
        ),
        migrations.RemoveField(
            model_name='paymentcommitment',
            name='status',
        ),
        migrations.DeleteModel(
            name='ClaimDocumentType',
        ),
    ]
