# Generated by Django 5.0.8 on 2025-04-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0134_commitmentdeposit_days_next_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcommitment',
            old_name='due_date',
            new_name='payment_date',
        ),
    ]
