# Generated by Django 5.0.8 on 2025-04-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0135_rename_due_date_paymentcommitment_payment_date'),
        ('coredata', '0061_alter_city_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.person'),
        ),
    ]
