# Generated by Django 5.0.8 on 2025-04-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0135_remove_claimstep_document_type_and_more'),
        ('logger', '0029_alter_logclaimrequestcontractchange_current_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimRequestStatus',
        ),
        migrations.DeleteModel(
            name='ClaimRequest',
        ),
        migrations.DeleteModel(
            name='ClaimRequestPayment',
        ),
        migrations.DeleteModel(
            name='ClaimStep',
        ),
        migrations.DeleteModel(
            name='CommitmentDeposit',
        ),
        migrations.DeleteModel(
            name='PaymentCommitment',
        ),
    ]
