# Generated by Django 5.0.8 on 2025-04-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0136_commitmentdeposit_holder'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='paymentcommitment',
            name='currently_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
