# Generated by Django 5.0.8 on 2025-04-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0133_invoice_simplified'),
        ('billing', '0136_delete_claimrequeststatus_delete_claimrequest_and_more'),
    ]

    operations = [
    ]
