# Generated by Django 5.0.8 on 2025-04-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0137_merge_20250425_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('remaining_to_share', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('invoices', models.ManyToManyField(blank=True, related_name='payment_commitments', to='billing.invoice')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.commitmentdepositstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('commitment_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_commitments', to='billing.commitmentdeposit')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paymentcommitmentstatus')),
            ],
        ),
    ]
