# Generated by Django 5.0.8 on 2025-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0138_commitmentdepositobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
