# Generated by Django 5.0.8 on 2025-04-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0139_paymentcommitment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentdeposit',
            name='holder',
        ),
    ]
