# Generated by Django 5.0.8 on 2025-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0140_remove_commitmentdeposit_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
