# Generated by Django 5.0.8 on 2025-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0138_commitmentdeposit_paymentcommitment'),
        ('billing', '0141_paymentcommitment_is_guide'),
    ]

    operations = [
    ]
