# Generated by Django 5.0.8 on 2025-04-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0142_merge_20250428_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='days_next_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='currently_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcommitment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_commitments', to='billing.paymentcommitmentstatus'),
        ),
    ]
