# Generated by Django 5.0.8 on 2025-04-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0143_commitmentdeposit_days_next_payment_and_more'),
        ('coredata', '0063_remove_person_commitment_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitment_deposits', to='coredata.person'),
        ),
    ]
