# Generated by Django 5.0.8 on 2025-04-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0144_commitmentdeposit_holder'),
        ('contract', '0161_alter_contract_communication_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentdeposit',
            name='holder',
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitment_deposits', to='contract.contract'),
        ),
    ]
