# Generated by Django 5.0.8 on 2025-04-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0145_remove_commitmentdeposit_holder_and_more'),
        ('contract', '0161_alter_contract_communication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype'),
        ),
    ]
