# Generated by Django 5.0.8 on 2025-05-06 10:43

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0146_commitmentdeposit_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=billing.models.reading_document_upload_to)),
            ],
        ),
    ]
