# Generated by Django 5.0.8 on 2025-04-30 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0147_remove_commitmentdeposit_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commitment_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.commitmentdeposit'),
        ),
    ]
