# Generated by Django 5.0.8 on 2025-04-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0148_payment_commitment_deposit'),
        ('coredata', '0063_remove_person_commitment_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbank'),
        ),
    ]
