# Generated by Django 5.0.8 on 2025-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0149_paymentcommitment_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='payment_bank_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='payment_swift_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
