# Generated by Django 5.0.8 on 2025-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0150_paymentcommitment_payment_bank_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsepa',
            name='commitment_deposits',
            field=models.ManyToManyField(blank=True, related_name='sepa_documents', to='billing.commitmentdeposit'),
        ),
    ]
