# Generated by Django 5.0.8 on 2025-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0151_documentsepa_commitment_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='customer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='customer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
