# Generated by Django 5.0.8 on 2025-04-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0152_paymentcommitment_customer_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcommitment',
            name='customer_final',
        ),
        migrations.RemoveField(
            model_name='paymentcommitment',
            name='customer_token_final',
        ),
    ]
