# Generated by Django 5.0.8 on 2025-04-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0153_remove_paymentcommitment_customer_final_and_more'),
        ('documentmanager', '0013_alter_document_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentmanager.document'),
        ),
    ]
