# Generated by Django 5.0.8 on 2025-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0154_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
