# Generated by Django 5.0.8 on 2025-05-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0147_readingdocument'),
        ('billing', '0155_payment_sent_date'),
    ]

    operations = [
    ]
