# Generated by Django 5.0.8 on 2025-05-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0156_merge_0147_readingdocument_0155_payment_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='billing.readingdocument'),
        ),
    ]
