# Generated by Django 5.0.8 on 2025-05-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0157_reading_document'),
        ('contract', '0162_contractterminationrequest_claim_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract_termination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractterminationrequest'),
        ),
    ]
