# Generated by Django 5.0.8 on 2025-05-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0159_alter_invoice_contract'),
        ('contract', '0162_contractterminationrequest_claim_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
