# Generated by Django 5.0.8 on 2025-05-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0160_alter_invoice_contract'),
        ('pricing', '0077_remove_pricerate_calculation_remove_pricerate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='pricing.lineitemtype'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='pricing.product'),
        ),
    ]
