# Generated by Django 5.0.8 on 2025-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0161_alter_invoicelineitem_line_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentdeposit',
            name='address_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='customer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='customer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='location_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentdeposit',
            name='persons_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
