# Generated by Django 5.0.8 on 2025-05-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0159_alter_invoicelineitem_line_item_type_and_more'),
        ('billing', '0162_commitmentdeposit_address_final_and_more'),
    ]

    operations = [
    ]
