# Generated by Django 5.0.8 on 2025-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0163_merge_20250522_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
