# Generated by Django 5.0.8 on 2025-05-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0164_payment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
    ]
