# Generated by Django 5.0.8 on 2025-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0165_remove_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
