# Generated by Django 5.0.8 on 2025-05-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0166_payment_bank_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_token',
        ),
    ]
