# Generated by Django 5.0.8 on 2025-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0169_paymentremittancestatus_paymentremittance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reject_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
