# Generated by Django 5.0.8 on 2025-06-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0170_payment_reject_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='reading_route',
        ),
        migrations.DeleteModel(
            name='ReadingRoute',
        ),
    ]
