# Generated by Django 5.0.8 on 2025-06-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0171_remove_reading_reading_route_delete_readingroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingbatchtemplate',
            name='biller',
        ),
    ]
