# Generated by Django 5.0.8 on 2025-06-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0171_rejectmotivetype_rejectmotive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectmotive',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejects', to='billing.rejectmotivetype'),
        ),
    ]
