# Generated by Django 5.0.8 on 2025-06-27 07:24

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0172_alter_rejectmotive_type'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPaymentSepaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('template', models.FileField(blank=True, null=True, upload_to=billing.models.sepa_template_upload_to)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document')),
                ('general_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepa_document', to='billing.generalpayment')),
            ],
        ),
    ]
