# Generated by Django 5.0.8 on 2025-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0172_remove_billingbatchtemplate_biller'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billiing_archived',
            field=models.BooleanField(default=False),
        ),
    ]
