# Generated by Django 5.0.8 on 2025-06-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0173_billing_billiing_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billing'),
        ),
    ]
