# Generated by Django 5.0.8 on 2025-06-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0174_invoice_billing'),
        ('service', '0080_remove_route_batch_template_route_biller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingBatchTemplate',
            new_name='ReadingBatchTemplate',
        ),
        migrations.RemoveField(
            model_name='billingbatch',
            name='template',
        ),
    ]
