# Generated by Django 5.0.8 on 2025-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0175_rename_billingbatchtemplate_readingbatchtemplate_and_more'),
        ('service', '0081_route_reading_batch_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='reading_batches', to='service.route'),
        ),
    ]
