# Generated by Django 5.0.8 on 2025-06-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0173_generalpaymentsepadocument'),
        ('billing', '0176_readingbatch_routes'),
    ]

    operations = [
    ]
