# Generated by Django 5.0.8 on 2025-07-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0177_merge_20250630_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingdocument',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='billing.readingbatch'),
        ),
    ]
