# Generated by Django 5.0.8 on 2025-07-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0178_readingdocument_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='billing.billing'),
        ),
    ]
