# Generated by Django 5.0.8 on 2025-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0179_reading_billing'),
        ('communication', '0012_communication_always_attach'),
        ('contract', '0176_contractterminationrequest_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='communication_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationprocess'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contract.contract'),
        ),
    ]
