# Generated by Django 5.0.8 on 2025-07-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0180_alter_invoice_contract'),
        ('billing', '0180_billing_communication_process_alter_invoice_contract'),
    ]

    operations = [
    ]
