# Generated by Django 5.0.8 on 2025-07-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0180_billing_communication_process_alter_invoice_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='budget_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
