# Generated by Django 5.0.8 on 2025-07-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0181_invoice_budget_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='reading_last',
        ),
        migrations.AddField(
            model_name='invoice',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='billing.reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
    ]
