# Generated by Django 5.0.8 on 2025-07-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0182_remove_invoice_reading_remove_invoice_reading_last_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='billing.reading'),
        ),
    ]
