# Generated by Django 5.0.8 on 2025-07-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0181_merge_20250717_0746'),
        ('billing', '0183_invoicelineitem_reading'),
    ]

    operations = [
    ]
