# Generated by Django 5.0.8 on 2025-07-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0184_merge_20250717_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
