# Generated by Django 5.0.8 on 2025-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0185_alter_invoice_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
