# Generated by Django 5.0.8 on 2025-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0186_alter_invoicelineitem_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
