# Generated by Django 5.0.8 on 2025-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0187_payment_is_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
