# Generated by Django 5.0.8 on 2025-07-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0188_alter_invoicelineitem_total'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='piggy_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contract.piggybank'),
        ),
    ]
