# Generated by Django 5.0.8 on 2025-07-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0189_invoice_piggy_bank'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
