# Generated by Django 5.0.8 on 2025-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0190_payment_contract_payment_customer_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='return_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
