# Generated by Django 5.0.8 on 2025-07-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0191_invoice_return_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refactored_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
