# Generated by Django 5.0.8 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0192_invoice_refactored_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='leak_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
