# Generated by Django 5.0.8 on 2025-07-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0187_readeralert'),
        ('billing', '0193_reading_leak_value'),
    ]

    operations = [
    ]
