# Generated by Django 5.0.8 on 2025-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0195_invoicesuppressionreason_invoice_suppressed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
