# Generated by Django 5.0.8 on 2025-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0195_invoicesuppressionreason_invoice_suppressed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='currently_paid',
            new_name='left_to_pay',
        ),
    ]
