# Generated by Django 5.0.8 on 2025-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0196_invoice_is_suppressed'),
        ('billing', '0196_rename_currently_paid_invoice_left_to_pay_and_more'),
    ]

    operations = [
    ]
