# Generated by Django 5.0.8 on 2025-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0197_merge_20250728_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpayment',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalpayment',
            name='record',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
