# Generated by Django 5.0.8 on 2025-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0198_generalpayment_command_generalpayment_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='command_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='record_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
