# Generated by Django 5.0.8 on 2025-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0199_invoice_command_final_invoice_record_final'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='contract',
        ),
        migrations.AddField(
            model_name='reading',
            name='contracts',
            field=models.ManyToManyField(blank=True, related_name='readings', to='contract.contract'),
        ),
    ]
