# Generated by Django 5.0.8 on 2025-07-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0200_remove_reading_contract_reading_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='invoice',
        ),
    ]
