# Generated by Django 5.0.8 on 2025-07-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0201_remove_reading_invoice'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='contracts',
        ),
        migrations.AddField(
            model_name='reading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
