# Generated by Django 5.0.8 on 2025-07-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0202_remove_reading_contracts_reading_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedBagMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('movement_date', models.DateField(blank=True, null=True)),
                ('is_positive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='billing.estimatedbag')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_bag_movements', to='billing.reading')),
            ],
        ),
    ]
