# Generated by Django 5.0.8 on 2025-07-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0203_estimatedbagmovement'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedbag',
            name='holder',
        ),
        migrations.AddField(
            model_name='estimatedbag',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
