# Generated by Django 5.0.8 on 2025-07-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0205_alter_estimatedbag_supply_point'),
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedbag',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_bags', to='contract.contract'),
        ),
    ]
