# Generated by Django 5.0.8 on 2025-07-31 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0206_alter_estimatedbag_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedbagmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_bag_movements', to='billing.invoice'),
        ),
    ]
