# Generated by Django 5.0.8 on 2025-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0207_estimatedbagmovement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='consumption_bag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
