# Generated by Django 5.0.8 on 2025-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0208_invoice_consumption_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
