# Generated by Django 5.0.8 on 2025-07-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0209_reading_is_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='is_modified',
        ),
    ]
