# Generated by Django 5.0.8 on 2025-07-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0210_remove_reading_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='estimated_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
