# Generated by Django 5.0.8 on 2025-07-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0211_reading_estimated_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedbagmovement',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_bag_movements', to='billing.reading'),
        ),
    ]
