# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0212_alter_estimatedbagmovement_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Billing', 'verbose_name_plural': 'Billings'},
        ),
        migrations.AlterModelOptions(
            name='billingbatch',
            options={'verbose_name': 'Billing Batch', 'verbose_name_plural': 'Billing Batches'},
        ),
        migrations.AlterModelOptions(
            name='commitmentdeposit',
            options={'verbose_name': 'Commitment Deposit', 'verbose_name_plural': 'Commitment Deposits'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
        migrations.AlterModelOptions(
            name='readingbatch',
            options={'verbose_name': 'Reading Batch', 'verbose_name_plural': 'Reading Batches'},
        ),
    ]
