# Generated by Django 5.0.8 on 2025-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0213_alter_billing_options_alter_billingbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
