# Generated by Django 5.0.8 on 2025-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0213_alter_billing_options_alter_billingbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='include_telecontrol',
            field=models.BooleanField(default=False),
        ),
    ]
