# Generated by Django 5.0.8 on 2025-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0214_invoice_payer_final_invoice_payer_token_final_and_more'),
        ('billing', '0214_readingbatch_include_telecontrol'),
    ]

    operations = [
    ]
