# Generated by Django 5.0.8 on 2025-10-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0215_merge_20251002_0921'),
        ('contract', '0194_merge_20251007_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentdeposit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitment_deposits', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='estimatedbag',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_bags', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
