# Generated by Django 5.0.8 on 2025-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0217_remotereadingalert_reading_remote_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
