# Generated by Django 5.0.8 on 2025-10-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0218_alter_invoicelineitem_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
