# Generated by Django 5.0.8 on 2025-10-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0219_alter_invoicelineitem_units'),
        ('billing', '0219_invoicesequence'),
    ]

    operations = [
    ]
