# Generated by Django 5.0.8 on 2025-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0220_merge_20251020_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
