# Generated by Django 5.0.8 on 2025-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0221_invoice_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='include_manual',
            field=models.BooleanField(default=False),
        ),
    ]
