# Generated by Django 5.0.8 on 2025-11-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0222_readingbatch_include_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentdeposit',
            name='remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='commitmentdeposit',
            name='remaining_to_share',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='commitmentdeposit',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
