# Generated by Django 5.0.8 on 2025-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0223_alter_commitmentdeposit_remaining_and_more'),
        ('contract', '0201_recalculate_search_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='general_contracts',
            field=models.ManyToManyField(blank=True, related_name='general_invoices', to='contract.contract'),
        ),
    ]
