# Generated by Django 5.0.8 on 2025-11-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0224_invoice_general_contracts'),
        ('contract', '0201_recalculate_search_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='contract.contract'),
        ),
    ]
