# Generated by Django 5.0.8 on 2025-11-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0225_invoicelineitem_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sent_at',
            new_name='send_at',
        ),
    ]
