# Generated by Django 5.0.8 on 2025-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0226_rename_sent_at_invoice_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
