# Generated by Django 5.0.8 on 2025-11-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0227_payment_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='send_at',
        ),
    ]
