# Generated by Django 5.0.8 on 2025-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0228_remove_payment_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serie_final',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
