# Generated by Django 5.0.8 on 2025-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0229_alter_invoice_serie_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentdeposit',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
