# Generated by Django 5.0.8 on 2025-11-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0230_alter_commitmentdeposit_token_alter_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='verifactu_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verifactu_previous_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verifactu_previous_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifactu_previous_invoices', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verifactu_qr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
