# Generated by Django 5.0.8 on 2025-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0230_alter_commitmentdeposit_token_alter_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
