# Generated by Django 5.0.8 on 2025-11-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0231_invoice_verifactu_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='verifactu_hash',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verifactu_previous_hash',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verifactu_previous_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verifactu_qr',
        ),
    ]
