# Generated by Django 5.0.8 on 2025-11-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0231_reading_is_close'),
        ('service', '0092_exploitation_supply_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='fix_meters',
            field=models.ManyToManyField(blank=True, related_name='reading_batches', to='service.meter'),
        ),
    ]
