# Generated by Django 5.0.8 on 2025-11-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0232_remove_invoice_verifactu_hash_and_more'),
        ('verifactu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='verifactu_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifactu.verifactuinvoice'),
        ),
    ]
