# Generated by Django 5.0.8 on 2025-11-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0231_reading_is_close'),
        ('billing', '0233_invoice_verifactu_invoice'),
    ]

    operations = [
    ]
