# Generated by Django 5.0.8 on 2025-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0232_readingbatch_fix_meters'),
        ('billing', '0234_merge_20251119_1423'),
    ]

    operations = [
    ]
