# Generated by Django 5.0.8 on 2025-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0235_merge_20251119_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='assign_readings_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='estimating_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
