# Generated by Django 5.0.8 on 2025-11-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0236_readingbatch_assign_readings_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedbagmovement',
            name='estimated_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.estimatedbag'),
        ),
    ]
