# Generated by Django 5.0.8 on 2025-11-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0237_alter_estimatedbagmovement_estimated_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedbagmovement',
            name='estimated_bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='billing.estimatedbag'),
        ),
        migrations.AlterField(
            model_name='estimatedbagmovement',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_bag_movements', to='billing.reading'),
        ),
    ]
