# Generated by Django 5.0.8 on 2025-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0239_bankrnddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
