# Generated by Django 5.0.8 on 2025-12-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0241_invoicelog'),
        ('billing', '0241_payment_is_active'),
    ]

    operations = [
    ]
