# Generated by Django 5.0.8 on 2025-12-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0242_merge_0241_invoicelog_0241_payment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='verifactu_invoice',
        ),
    ]
