# Generated by Django 5.0.8 on 2025-12-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0243_remove_invoice_verifactu_invoice'),
        ('verifactu', '0008_remove_verifactuinvoicelog_verifactu_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='verifactu_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifactu.verifactunotification'),
        ),
    ]
