# Generated by Django 5.0.8 on 2025-12-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0244_invoice_verifactu_notification'),
        ('service', '0093_exploitation_accountant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremittance',
            name='company_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.companybank'),
        ),
    ]
