# Generated by Django 5.0.8 on 2025-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0245_paymentremittance_company_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
