# Generated by Django 5.0.8 on 2025-12-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0246_invoicelineitem_interval'),
        ('pricing', '0093_adjustment_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='pricing.adjustment')),
            ],
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='adjustments',
            field=models.ManyToManyField(blank=True, related_name='line_items', to='billing.appliedadjustment'),
        ),
    ]
