# Generated by Django 5.0.8 on 2025-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0247_appliedadjustment_invoicelineitem_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='end_stretch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
