# Generated by Django 5.0.8 on 2025-12-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0248_invoicelineitem_end_stretch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='billing.reading'),
        ),
    ]
