# Generated by Django 5.0.8 on 2025-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0248_invoicelineitem_end_stretch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedadjustment',
            name='is_minimum',
            field=models.BooleanField(default=False),
        ),
    ]
