# Generated by Django 5.0.8 on 2025-12-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0249_appliedadjustment_is_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedadjustment',
            name='is_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
