# Generated by Django 5.0.8 on 2025-12-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0249_reading_copied_from'),
        ('billing', '0250_appliedadjustment_is_vulnerable'),
    ]

    operations = [
    ]
