# Generated by Django 5.0.8 on 2025-12-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0251_merge_20251219_1112'),
        ('billing', '0251_merge_20251219_1119'),
    ]

    operations = [
    ]
