# Generated by Django 5.0.8 on 2026-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0252_merge_20251219_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
