# Generated by Django 5.0.8 on 2026-01-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0253_invoice_billing_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
