# Generated by Django 5.0.8 on 2026-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0254_invoice_billing_period_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serie_final',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
