# Generated by Django 5.0.8 on 2026-01-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0255_alter_invoice_serie_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='real_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
