# Generated by Django 5.0.8 on 2026-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0256_reading_real_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremittance',
            name='desired_send_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
