# Generated by Django 5.0.8 on 2026-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0257_paymentremittance_desired_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingbatch',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingbatch',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingbatch',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
