# Generated by Django 5.0.8 on 2026-02-24 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0257_paymentremittance_desired_send_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('movement_date', models.DateField(blank=True, null=True)),
                ('payment_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('is_positive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_current_status', to='billing.paymentstatus')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='billing.payment')),
                ('previous_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_previous_status', to='billing.paymentstatus')),
                ('reject_motive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.rejectmotive')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
