# Generated by Django 5.0.8 on 2026-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0258_billingbatch_due_date_billingbatch_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
