# Generated by Django 5.0.8 on 2026-02-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0258_paymentmovement'),
        ('contract', '0208_remove_contract_contract_search_vector_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmovement',
            name='payment_type_name',
        ),
        migrations.RemoveField(
            model_name='paymentmovement',
            name='payment_type_token',
        ),
        migrations.AddField(
            model_name='paymentmovement',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype'),
        ),
    ]
