# Generated by Django 5.0.8 on 2026-03-04 12:51

from django.db import migrations


def add_high_billing_warning(apps, schema_editor):
    InvoiceWarning = apps.get_model('billing', 'InvoiceWarning')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    # Create the InvoiceWarning
    warning, created = InvoiceWarning.objects.get_or_create(
        pk=6,
        defaults={
            'token': '6',
            'name': 'Import de facturació massa alt',
            'color': '#ff9800',
            'description': 'L\'import total de la factura supera el 150% de la mitjana del contracte',
            'is_default': False,
            'position': 6
        }
    )
    
    # Reset sequence to avoid ID conflicts
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT setval(pg_get_serial_sequence('coredata_configproject', 'id'), (SELECT MAX(id) FROM coredata_configproject));")

    # Create or update the ConfigProject setting
    ConfigProject.objects.update_or_create(
        token='invoice_warning_high_amount',
        defaults={
            'name': 'Token Invoice Warning High Amount',
            'value': '6'
        }
    )

def remove_high_billing_warning(apps, schema_editor):
    InvoiceWarning = apps.get_model('billing', 'InvoiceWarning')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    InvoiceWarning.objects.filter(token=6).delete()
    ConfigProject.objects.filter(token='invoice_warning_high_amount').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0259_billing_send_at'),
        ('coredata', '0001_initial'), # Adjust if coredata has other relevant dependencies
    ]

    operations = [
        migrations.RunPython(add_high_billing_warning, remove_high_billing_warning),
    ]
