# Generated by Django 5.0.8 on 2026-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0259_remove_paymentmovement_payment_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmovement',
            name='is_positive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
