# Generated by Django 5.0.8 on 2026-02-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0260_alter_paymentmovement_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmovement',
            name='payoff_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payoff_movements', to='billing.invoice'),
        ),
    ]
