# Generated by Django 5.0.8 on 2026-02-25 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0261_paymentmovement_payoff_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmovement',
            name='payment_remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.paymentremittance'),
        ),
    ]
