# Generated by Django 5.0.8 on 2026-03-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0260_add_high_billing_amount_warning'),
        ('billing', '0262_paymentmovement_payment_remittance'),
    ]

    operations = [
    ]
