# Generated by Django 5.0.8 on 2026-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0263_merge_20260312_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
    ]
