# Generated by Django 5.0.8 on 2026-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0264_reading_is_revised'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremittance',
            name='pending_changes',
            field=models.BooleanField(default=False),
        ),
    ]
