# Generated by Django 5.0.8 on 2026-03-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0265_paymentremittance_pending_changes'),
        ('contract', '0211_add_configproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequest'),
        ),
        migrations.AddField(
            model_name='reading',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
