# Generated by Django 5.0.8 on 2026-03-30 06:44

from django.db import migrations, models


def add_new_token_config(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    if not ConfigProject.objects.filter(token='payment_remittance_status_processing_token').exists():
        ConfigProject.objects.create(
            token='payment_remittance_status_processing_token',
            name='Token de PaymentRemittanceStatus processant',
            value='2',
            file=None
        )
    if not ConfigProject.objects.filter(token='reading_estimate_limit_percentage').exists():
        ConfigProject.objects.create(
            token='reading_estimate_limit_percentage',
            name='Limit per crear una lectura estimada',
            value='33',
            file=None
        )
    PaymentRemittanceStatus = apps.get_model('billing', 'PaymentRemittanceStatus')
    if not PaymentRemittanceStatus.objects.filter(token='2').exists():
        PaymentRemittanceStatus.objects.create(
            token='2',
            name='Processant fitxer',
            color='orange',
            position=3,
            is_default=False
        )
class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0266_reading_contract_request_reading_is_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremittance',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(add_new_token_config),
    ]
