# Generated by Django 5.0.8 on 2026-04-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0268_add_confirmed_payment_commitment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='billing_missing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_batch', to='billing.billing'),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='missing_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='missing_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
