# Generated by Django 5.0.8 on 2026-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0268_add_confirmed_payment_commitment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmovement',
            name='payment_origin',
            field=models.CharField(blank=True, choices=[('box_office', 'Box Office'), ('post_office', 'Post Office')], max_length=20, null=True),
        ),
    ]
