# Generated by Django 5.0.8 on 2026-04-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0269_paymentmovement_payment_origin'),
        ('billing', '0269_readingbatch_billing_missing_and_more'),
    ]

    operations = [
    ]
