# Generated by Django 5.0.8 on 2026-04-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0270_merge_20260410_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='modified_readings',
            field=models.ManyToManyField(blank=True, related_name='original_readings', to='billing.reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='billing.reading'),
        ),
    ]
