# Generated by Django 5.0.8 on 2026-04-20 11:54

import django.db.models.deletion
from django.db import migrations, models

from billing.management.commands.feat_relate_modified_readings import relate_modified_readings
from billing.management.commands.fix_no_meter_readings import fix_no_meter_readings_estimation

def run_fix_modified_readings_relation(apps, schema_editor):
    try:
        relate_modified_readings(apps=apps)
        fix_no_meter_readings_estimation(apps=apps)
    except Exception as e:
        print(e)
        return
    
class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0271_reading_modified_readings_alter_reading_copied_from'),
        # Garanteix que contract_contract tingui registration_date; el RunPython usa apps.get_model
        # per no demanar columnes de models.py posteriors (p.ex. termination_date a 0218).
        ('contract', '0216_contract_registration_date_and_more'),
    ]

    operations = [
        migrations.RunPython(run_fix_modified_readings_relation),
    ]
