# Generated by Django 5.0.8 on 2026-04-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0272_alter_reading_modified_original_relations'),
        ('coredata', '0096_personpiggybank_person_piggy_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='coredata.person'),
        ),
    ]
