# Generated by Django 5.0.8 on 2026-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0273_payment_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
