# Generated by Django 5.0.8 on 2026-05-13

from django.db import migrations


def add_low_consumption_alert(apps, schema_editor):
    ReadingAlert = apps.get_model('billing', 'ReadingAlert')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    # Create the ReadingAlert
    alert, created = ReadingAlert.objects.get_or_create(
        pk=6,
        defaults={
            'token': '6',
            'name': 'reading_alert_low_consumption',
            'color': 'cyan',
            'is_default': False,
            'position': 6
        }
    )
    
    # Reset sequence to avoid ID conflicts
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT setval(pg_get_serial_sequence('coredata_configproject', 'id'), (SELECT MAX(id) FROM coredata_configproject));")
        cursor.execute("SELECT setval(pg_get_serial_sequence('billing_readingalert', 'id'), (SELECT MAX(id) FROM billing_readingalert));")

    # Create or update the ConfigProject setting
    ConfigProject.objects.update_or_create(
        token='reading_alert_low_consumption',
        defaults={
            'name': 'Unusually low reading',
            'value': '6'
        }
    )

def remove_low_consumption_alert(apps, schema_editor):
    ReadingAlert = apps.get_model('billing', 'ReadingAlert')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    ReadingAlert.objects.filter(token='6').delete()
    ConfigProject.objects.filter(token='reading_alert_low_consumption').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0274_invoice_is_excluded'),
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_low_consumption_alert, remove_low_consumption_alert),
    ]
