# Generated by Django 5.0.8 on 2026-05-13

from django.db import migrations


def update_names_to_tokens(apps, schema_editor):
    ReadingAlert = apps.get_model('billing', 'ReadingAlert')

    # ReadingAlert mapping
    reading_alerts = {
        1: 'reading_alert_turn',
        2: 'reading_alert_zero',
        3: 'reading_alert_negative',
        4: 'reading_alert_estimated',
        5: 'reading_alert_unusual',
        6: 'reading_alert_low_consumption'
    }
    for pk, token_name in reading_alerts.items():
        ReadingAlert.objects.filter(pk=pk).update(name=token_name)


def revert_names_to_defaults(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0275_add_low_consumption_reading_alert'),
    ]

    operations = [
        migrations.RunPython(update_names_to_tokens, revert_names_to_defaults),
    ]
