# Generated by Django 5.0.8 on 2026-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0275_joinedpaymentstatus_joinedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedpayment',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
