# Generated by Django 5.0.8 on 2026-05-14

from django.db import migrations


def revert_invoice_names(apps, schema_editor):
    InvoiceStatus = apps.get_model('billing', 'InvoiceStatus')
    InvoiceClass = apps.get_model('billing', 'InvoiceClass')

    # InvoiceStatus mapping
    invoice_statuses = {
        1: 'Pre-factura',
        2: 'Pagada',
        3: 'Vençuda',
        5: 'Confirmada',
        6: 'Morositat',
        7: 'En compromís',
        8: 'Enviada',
        9: 'Irrecuperable',
        10: 'Anul·lada',
        11: 'Parcialment Irrecuperable',
        12: 'Abonament',
    }
    for pk, default_name in invoice_statuses.items():
        InvoiceStatus.objects.filter(pk=pk).update(name=default_name)

    # Delete pk=13 if it was added
    InvoiceStatus.objects.filter(pk=13).delete()

    # InvoiceClass mapping
    invoice_classes = {
        1: 'Original',
        2: 'Original rectificativa',
        3: 'Original recapitulativa',
        4: 'Duplicat original',
        5: 'Duplicat rectificativa',
        6: 'Duplicat recapitulativa'
    }
    for pk, default_name in invoice_classes.items():
        InvoiceClass.objects.filter(pk=pk).update(name=default_name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0276_update_alert_status_class_names_to_tokens'),
    ]

    operations = [
        migrations.RunPython(revert_invoice_names, noop),
    ]
