# Generated by Django 5.0.8 on 2026-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0276_joinedpayment_total_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedpayment',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
