# Generated by Django 5.0.8 on 2026-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0277_revert_invoice_status_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='custom_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
