# Generated by Django 5.0.8 on 2026-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0277_joinedpayment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedpayment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
