# Generated by Django 5.0.8 on 2026-05-07 10:22

from django.db import migrations, models

def add_status_configs(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    # joined_payment_status_paid_token
    if not ConfigProject.objects.filter(token='joined_payment_status_paid_token').exists():
        ConfigProject.objects.create(
            token='joined_payment_status_paid_token',
            name='Token de JoinedPaymentStatus de Pagat',
            value='0',
        )
        
    # joined_payment_status_cancelled_token
    if not ConfigProject.objects.filter(token='joined_payment_status_cancelled_token').exists():
        ConfigProject.objects.create(
            token='joined_payment_status_cancelled_token',
            name='Token de JoinedPaymentStatus de Anul·lat',
            value='-2',
        )

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0278_joinedpayment_is_active'),
    ]

    operations = [
        migrations.RunPython(add_status_configs),
    ]
