# Generated by Django 5.0.8 on 2026-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0279_joinedpayment_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedpayment',
            name='customer_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joinedpayment',
            name='customer_token_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
