# Generated by Django 5.0.8 on 2026-05-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0280_joinedpayment_customer_final_and_more'),
        ('contract', '0219_remove_generalinvoice_address_send_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinedpayment',
            old_name='payment_bank',
            new_name='payment_type_name',
        ),
        migrations.RemoveField(
            model_name='joinedpayment',
            name='payment_swift',
        ),
        migrations.AlterField(
            model_name='joinedpayment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype'),
        ),
    ]
