# Generated by Django 5.0.8 on 2026-05-12 06:00

import django.db.models.deletion
from django.db import migrations, models

def add_stats_configs(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    # stats_consumption_threshold
    if not ConfigProject.objects.filter(token='joined_payment_status_expired_token').exists():
        ConfigProject.objects.create(
            token='joined_payment_status_expired_token',
            name='Token de JoinedPaymentStatus de Vencut',
            value='-1',
            file='Statistics'
        )
        
    # stats_days_threshold
    if not ConfigProject.objects.filter(token='joined_payment_status_pending_token').exists():
        ConfigProject.objects.create(
            token='joined_payment_status_pending_token',
            name='Token de JoinedPaymentStatus de Pendent',
            value='1',
            file='Statistics'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0281_rename_payment_bank_joinedpayment_payment_type_name_and_more'),
    ]

    operations = [
        migrations.RunPython(add_stats_configs),
    ]
