# Generated by Django 5.0.8 on 2026-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0277_revert_invoice_status_class_names'),
        ('billing', '0283_joinedpaymentobservation'),
    ]

    operations = [
    ]
