# Generated by Django 5.0.8 on 2026-05-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0278_invoicelineitem_custom_order'),
        ('billing', '0284_merge_20260518_1033'),
    ]

    operations = [
    ]
