# Generated by Django 5.0.8 on 2026-05-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0285_merge_20260518_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['custom_order', 'id']},
        ),
    ]
