# Generated by Django 5.0.8 on 2026-05-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0278_readingdocument_template'),
        ('billing', '0286_alter_invoicelineitem_options'),
    ]

    operations = [
    ]
