# Generated by Django 5.0.8 on 2026-05-18 13:28

from django.db import migrations
from billing.utils.basic_fix_utils import cancel_payments_in_cancelled_commitments


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0287_merge_20260518_1528'),
    ]

    operations = [
        migrations.RunPython(cancel_payments_in_cancelled_commitments),
    ]
