# Generated by Django 5.0.8 on 2026-05-20 08:00

from django.db import migrations
from billing.utils.basic_fix_utils import fix_commitment_deposit_tokens


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0288_fix_commitment_payments_cancelled'),
    ]

    operations = [
        migrations.RunPython(fix_commitment_deposit_tokens),
    ]
