# Generated by Django 5.0.8 on 2026-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0289_fix_commitment_deposits_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_origin',
            field=models.CharField(blank=True, choices=[('box_office', 'Box Office'), ('post_office', 'Post Office')], max_length=20, null=True),
        ),
    ]
