# Generated by Django 5.0.8 on 2026-05-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0290_payment_payment_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_origin',
            new_name='payment_origin_choice',
        ),
    ]
