# Generated by Django 5.0.8 on 2026-06-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0291_rename_payment_origin_payment_payment_origin_choice'),
        ('coredata', '0107_person_e_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.person'),
        ),
    ]
