# Generated by Django 5.0.8 on 2026-06-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0292_invoice_person'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRemittanceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentmanager.document')),
                ('payments', models.ManyToManyField(blank=True, related_name='remittances_returns', to='billing.payment')),
            ],
        ),
    ]
