# Generated by Django 5.0.8 on 2026-06-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0294_paymentremittancereturn_returned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('PRE_INVOICE', 'Pre-invoice Generation'), ('DEFINITIVE_INVOICE', 'Definitive Invoice Generation')], max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='billing.billing')),
            ],
            options={
                'verbose_name': 'Billing Queue',
                'verbose_name_plural': 'Billing Queues',
                'ordering': ['created_at'],
            },
        ),
    ]
