# Generated by Django 5.0.8 on 2026-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0294_paymentremittancereturn_returned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='budget_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
