# Generated by Django 5.0.8 on 2026-06-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0295_billingqueue'),
        ('billing', '0295_invoice_budget_comment'),
    ]

    operations = [
    ]
