# Generated by Django 5.0.8 on 2026-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0296_merge_0295_billingqueue_0295_invoice_budget_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingqueue',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingqueue',
            name='task_type',
            field=models.CharField(choices=[('PRE_INVOICE', 'Pre-invoice Generation'), ('DEFINITIVE_INVOICE', 'Definitive Invoice Generation'), ('REGENERATE_PDFS', 'Regeneració de PDFs de factures'), ('WINCEN_EXPORT', 'Exportació fitxer WinCen')], max_length=50),
        ),
    ]
