# Generated by Django 5.0.8 on 2026-06-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0297_add_file_url_to_billing_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDocumentNotFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reading_value', models.IntegerField(blank=True, null=True)),
                ('reading_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('is_control', models.BooleanField(default=False)),
                ('leak_value', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('reading_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_found_readings', to='billing.readingdocument')),
            ],
        ),
    ]
