# Generated by Django 5.0.8 on 2026-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0299_billingqueue_invoices_documents_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
