# Generated by Django 5.0.8 on 2026-07-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0301_readingdocument_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='consumption_bag',
            new_name='real_consumption',
        ),
    ]
