# Generated by Django 5.0.8 on 2026-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0302_rename_consumption_bag_invoice_real_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentremittance',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
