# Generated by Django 5.0.8 on 2026-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0304_invoicecategory_invoice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecategory',
            name='serie_digit_av',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígit de sèrie (AV)'),
        ),
        migrations.AddField(
            model_name='invoicecategory',
            name='serie_digit_mv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígit de sèrie (MV)'),
        ),
    ]
