# Generated by Django 5.0.8 on 2026-07-27 09:09
#
# billing_reading te ~1M files: els indexs es creen CONCURRENTLY per no bloquejar
# escriptures (lectures/facturacio) durant el desplegament. CREATE INDEX CONCURRENTLY
# no pot anar dins una transaccio, per aixo atomic=False i SeparateDatabaseAndState
# (l'estat de Django s'actualitza igual, nomes canvia com s'executa el SQL real).

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('billing', '0305_invoicecategory_serie_digit_av_and_more'),
        ('contract', '0232_contract_debt_view_relation'),
        ('lecturapp', '0004_set_token_expiration_dates'),
        ('service', '0116_exploitation_companies'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='reading',
                    index=models.Index(fields=['supply_point', 'meter', 'contract', '-reading_date'], name='reading_prev_contract_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS reading_prev_contract_idx ON billing_reading (supply_point_id, meter_id, contract_id, reading_date DESC);',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS reading_prev_contract_idx;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='reading',
                    index=models.Index(fields=['supply_point', 'meter', '-reading_date'], name='reading_prev_no_contract_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS reading_prev_no_contract_idx ON billing_reading (supply_point_id, meter_id, reading_date DESC);',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS reading_prev_no_contract_idx;',
                ),
            ],
        ),
    ]
