# Generated by Django 5.0.8 on 2026-08-04 09:56

from django.db import migrations

def add_new_invoice_payment_status(apps, schema_editor):
    try:
        InvoiceStatus = apps.get_model('billing', 'InvoiceStatus')
        PaymentStatus = apps.get_model('billing', 'PaymentStatus')
        ConfigProject = apps.get_model('coredata', 'ConfigProject')
        InvoiceStatus.objects.get_or_create(
            token='-7',
            name='Anul·lada',
            color=None,
            description='Factura anul·lada, sense cap moviment registrat',
        )
        PaymentStatus.objects.get_or_create(
            token='-7',
            name='Anul·lat',
            color=None,
            description='Pagament anul·lat, sense cap moviment registrat',
        )
        ConfigProject.objects.get_or_create(
            token='invoice_status_dropped_token',
            name='Token Invoice Status Dropped',
            value='-7',
        )
        ConfigProject.objects.get_or_create(
            token='payment_status_dropped_token',
            name='Token Payment Status Dropped',
            value='-7',
        )
    except Exception as e:
        print("Unable to add new invoice and payment status: ", e)

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0306_reading_reading_prev_contract_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(add_new_invoice_payment_status),
    ]
