# Generated by Django 5.0.8 on 2026-08-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0307_add_new_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpayment',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
