# Generated by Django 5.0.8 on 2026-08-05 08:08

from django.db import migrations

def move_mandate_to_general_payment(apps, schema_editor):
    try:
        Contract = apps.get_model('contract', 'Contract')
        GeneralPayment = apps.get_model('billing', 'GeneralPayment')
        payments_to_update = []
        for contract in Contract.objects.filter(mandate_id__isnull=False):
            contract.payment.mandate_id = contract.mandate_id
            payments_to_update.append(contract.payment)
        GeneralPayment.objects.bulk_update(payments_to_update, ['mandate_id'])
    except Exception as e:
        print(f"Error moving mandate to general payment: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0308_generalpayment_mandate_id'),
    ]

    operations = [
        migrations.RunPython(move_mandate_to_general_payment),
    ]
