# Generated by Django 5.0.8 on 2026-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0310_generalpaymentmandatelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpaymentmandatelog',
            old_name='mandate_id',
            new_name='new_mandate_id',
        ),
        migrations.AddField(
            model_name='generalpaymentmandatelog',
            name='previous_mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
