# Generated by Django 5.0.8 on 2026-08-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0311_rename_mandate_id_generalpaymentmandatelog_new_mandate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpaymentmandatelog',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_logs', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='generalpaymentmandatelog',
            name='general_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_logs', to='billing.generalpayment'),
        ),
    ]
