# Generated by Django 5.0.8 on 2026-08-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0312_alter_generalpaymentmandatelog_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpaymentmandatelog',
            name='contract',
        ),
    ]
