# Generated by Django 5.0.8 on 2026-08-10 08:10

from django.db import migrations

def add_generate_sii_report(apps, schema_editor):
    try:
        ReportType = apps.get_model('statistics', 'ReportType')
        billing_report_type = ReportType.objects.get(token='billing')
        AvailableReport = apps.get_model('statistics', 'AvailableReport')
        AvailableReport.objects.get_or_create(
            name='(SII) Subministre Informació Inmediata',
            description='(SII) Subministre Informació Inmediata',
            function_name='sii_report',
            download_button_name='Descarregar fitxer XML',
            required_fields="['start_date', 'end_date', 'exploitation_id']",
            section=billing_report_type,
            is_active=False,
        )
    except Exception as e:
        print(f"Error adding SII report: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0313_remove_generalpaymentmandatelog_contract'),
    ]

    operations = [
        migrations.RunPython(add_generate_sii_report),
    ]
