# Generated by Django 5.0.8 on 2026-08-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0315_invoice_used_aca_configaca'),
        ('contract', '0238_add_none_communication_type_choice'),
        ('pricing', '0102_remove_lineitemtype_name_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configaca',
            name='contract_use_types',
            field=models.ManyToManyField(blank=True, related_name='aca_contract_use_types', to='contract.contractusetype'),
        ),
        migrations.AddField(
            model_name='configaca',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='aca_price_rates', to='pricing.pricerate'),
        ),
        migrations.AddField(
            model_name='configaca',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='aca_products', to='pricing.product'),
        ),
        migrations.AddField(
            model_name='configaca',
            name='variable_types',
            field=models.ManyToManyField(blank=True, related_name='aca_variable_types', to='contract.variabletype'),
        ),
    ]
