# Generated by Django 5.0.8 on 2026-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0316_configaca_contract_use_types_configaca_price_rates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='last_task_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='last_task_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
