# Generated by Django 5.0.8 on 2026-08-17 09:29

from django.db import migrations


def add_config_aca_alta(apps, schema_editor):
    try:
        ConfigProject = apps.get_model('coredata', 'ConfigProject')
        new_config, created = ConfigProject.objects.get_or_create(
            token='contract_use_aca_alta_tokens',
            name='Tokens de Tarifes per use_aca ALTA (separats per |)',
        )
        new_config.value = 'CAN-ALTA'
        new_config.save()
    except Exception as e:
        print(f"Error adding Config Aca Alta: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0317_reading_batch_last_task_errors'),
    ]

    operations = [
        migrations.RunPython(add_config_aca_alta),
    ]
