# Generated by Django 5.0.8 on 2026-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0318_config_aca_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
