# Generated by Django 5.0.8 on 2026-09-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0319_invoice_reviewed'),
        ('claimrequest', '0033_claimrequeststeptemplate_group_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedpayment',
            name='claim_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_payments', to='claimrequest.claimrequest'),
        ),
    ]
