# Generated by Django 5.0.4 on 2024-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_connectionrequest_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
