# Generated by Django 5.0.4 on 2024-07-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_routezone_route_route_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='dma',
        ),
    ]
