# Generated by Django 5.0.4 on 2024-07-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_route_dma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusternozzle',
            old_name='usage_destination',
            new_name='destination',
        ),
    ]
