
# Generated by Django 5.0.4 on 2024-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_usage_destination_clusternozzle_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeposition',
            name='zone',
        ),
    ]
