# Generated by Django 5.0.4 on 2024-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_tank_connection_flow_rate_connection_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/'),
        ),
    ]
