# Generated by Django 5.0.4 on 2024-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_tank_connection_flow_rate_connection_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointobservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
