# Generated by Django 5.0.4 on 2024-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_supplypointobservation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterobservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connectionobservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connectionrequestobservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
