# Generated by Django 5.0.4 on 2024-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_clusterobservation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequeststatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meterstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplypointstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
