# Generated by Django 5.0.4 on 2024-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_clusterstatus_color_connectionrequeststatus_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusternozzlestatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
