# Generated by Django 5.0.4 on 2024-07-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_connectionrequest_blueprint'),
        ('service', '0012_clusternozzlestatus_color'),
    ]

    operations = [
    ]
