# Generated by Django 5.0.4 on 2024-07-11 07:16

import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_merge_20240710_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterobservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.clusterstatus'),
        ),
        migrations.AddField(
            model_name='clusterobservation',
            name='statusName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionobservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionstatus'),
        ),
        migrations.AddField(
            model_name='connectionobservation',
            name='statusName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequestobservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionrequeststatus'),
        ),
        migrations.AddField(
            model_name='connectionrequestobservation',
            name='statusName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplypointobservation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointstatus'),
        ),
        migrations.AddField(
            model_name='supplypointobservation',
            name='statusName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=service.models.report_file_upload_to),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to=service.models.blueprint_upload_to),
        ),
    ]
