# Generated by Django 5.0.4 on 2024-07-10 06:56

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_merge_20240709_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to=service.models.blueprint_upload_to),
        ),
    ]
