# Generated by Django 5.0.4 on 2024-07-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_connectionrequest_blueprint'),
        ('service', '0014_clusterobservation_status_and_more'),
    ]

    operations = [
    ]
