# Generated by Django 5.0.4 on 2024-07-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_merge_20240711_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterobservation',
            old_name='statusName',
            new_name='status_name',
        ),
        migrations.RenameField(
            model_name='connectionobservation',
            old_name='statusName',
            new_name='status_name',
        ),
        migrations.RenameField(
            model_name='connectionrequestobservation',
            old_name='statusName',
            new_name='status_name',
        ),
        migrations.RenameField(
            model_name='supplypointobservation',
            old_name='statusName',
            new_name='status_name',
        ),
    ]
