# Generated by Django 5.0.4 on 2024-07-16 12:44

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_rename_statusname_clusterobservation_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=service.models.Company.logo_file_upload_to),
        ),
    ]
