# Generated by Django 5.0.4 on 2024-07-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='supply_point',
        ),
    ]
