# Generated by Django 5.0.4 on 2024-07-19 12:12

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_meter_supply_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=service.models.Company.logo_file_upload_to),
        ),
    ]
