# Generated by Django 5.0.4 on 2024-08-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_supplypointrequeststatus_supplypointrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusternozzle',
            name='split_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='service.clusternozzle'),
        ),
    ]
