# Generated by Django 5.0.4 on 2024-08-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_clusternozzle_split_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='service.routezone', verbose_name='RouteZone'),
        ),
        migrations.AlterField(
            model_name='routeposition',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='service.route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='supplypoint',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_points', to='service.property', verbose_name='Property'),
        ),
    ]
