# Generated by Django 5.0.4 on 2024-08-08 08:22

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_city_token_province_country'),
        ('service', '0022_alter_route_route_zone_alter_routeposition_route_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplypointrequest',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='supplypointrequest',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='supplypointrequest',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='supplypointrequest',
            name='address_street_number',
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_points_request_address', to='coredata.address'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='contract',
            field=models.FileField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupplyPointRequestDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('supply_point_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_files', to='service.supplypointrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPointRequestObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('status_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointrequeststatus')),
                ('supplypoint_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='service.supplypointrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
