# Generated by Django 5.0.8 on 2024-08-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_supplypointrequest_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.cluster'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='cluster_nozzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.clusternozzle'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connection'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.exploitation'),
        ),
    ]
