# Generated by Django 5.0.8 on 2024-08-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_supplypointrequest_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_point_requests', to='service.meter'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_point_requests', to='service.route'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='route_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_point_requests', to='service.routeposition'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointsource', verbose_name='SupplyPoint Source'),
        ),
        migrations.AddField(
            model_name='supplypointrequest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointtype', verbose_name='SupplyPoint Type'),
        ),
    ]
