# Generated by Django 5.0.8 on 2024-08-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_supplypointrequest_meter_supplypointrequest_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypointrequest',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
