# Generated by Django 5.0.8 on 2024-08-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_alter_supplypointrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_point_requests', to='service.property'),
        ),
    ]
