# Generated by Django 5.0.8 on 2024-09-03 06:52

import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_supplypointrequest_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPointRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('supply_point_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='service.supplypointrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='SupplyPointRequestDocumentation',
        ),
    ]
