# Generated by Django 5.0.8 on 2024-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_supplypointrequestdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPointRequestDocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
