# Generated by Django 5.0.8 on 2024-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_supplypointrequestdocumenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequestdocumenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
