# Generated by Django 5.0.8 on 2024-09-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_supplypointrequestdocumenttype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequestdocument',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplypointrequestdocument',
            name='supply_point_request_document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='service.supplypointrequestdocumenttype'),
            preserve_default=False,
        ),
    ]
