# Generated by Django 5.0.8 on 2024-09-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_city_token_province_country'),
        ('service', '0031_supplypointrequestdocument_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeposition',
            name='address_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.city'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='address_postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.postalcode'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='address_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.street'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='address_street_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.streetnumber'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
