# Generated by Django 5.0.8 on 2024-09-12 08:33

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_routeposition_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypointrequestdocument',
            name='file',
            field=models.FileField(blank=True, null=True),
        ),
    ]
