# Generated by Django 5.0.8 on 2024-09-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_alter_supplypointrequestdocument_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplypointrequest',
            old_name='supplyPoint',
            new_name='supply_point',
        ),
        migrations.CreateModel(
            name='SupplyCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_end', models.DateTimeField(auto_now=True, null=True)),
                ('supply_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypoint')),
            ],
        ),
    ]
