# Generated by Django 5.0.8 on 2024-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_rename_supplypoint_supplypointrequest_supply_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='cadastral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
