# Generated by Django 5.0.8 on 2024-09-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_supplypointrequest_cadastral'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointplacement', verbose_name='SupplyPoint Placement'),
        ),
    ]
