# Generated by Django 5.0.8 on 2024-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_supplycutstatus_supplycutobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycut',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
