# Generated by Django 5.0.8 on 2024-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_supplycut_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycut',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplycut',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
