# Generated by Django 5.0.8 on 2024-09-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_supplypointrequest_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypointrequest',
            name='supply_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointsupplytype', verbose_name='SupplyPoint SupplyType'),
        ),
    ]
