# Generated by Django 5.0.8 on 2024-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_alter_supplycut_date_end_alter_supplycut_date_start'),
        ('service', '0037_supplypointrequest_supply_type'),
    ]

    operations = [
    ]
