# Generated by Django 5.0.8 on 2024-09-20 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_merge_20240920_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycut',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplycutstatus', verbose_name='SupplyCut Status'),
        ),
    ]
