# Generated by Django 5.0.8 on 2024-09-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_connectioninstallationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
