# Generated by Django 5.0.8 on 2024-09-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0041_connectionrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='installation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectioninstallationtype', verbose_name='Installation Type'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='code_gis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='diameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectiondiameter', verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.exploitation'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='flow_rate',
            field=models.CharField(blank=True, help_text='Cabal nominal (m3/h)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='installation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectioninstallationtype', verbose_name='Installation Type'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionmaterial', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.tank', verbose_name='Tank'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectiontype', verbose_name='Connection Type'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionusetype', verbose_name='Connection Use Type'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='valve_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionvalvetype', verbose_name='Valve Type'),
        ),
    ]
