# Generated by Django 5.0.8 on 2024-09-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_connection_installation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='dma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.dma'),
        ),
    ]
