# Generated by Django 5.0.8 on 2024-09-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0043_connectionrequest_dma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusternozzle',
            name='split_from',
        ),
    ]
