# Generated by Django 5.0.8 on 2024-10-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_remove_clusternozzle_split_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='service.connection'),
        ),
    ]
