# Generated by Django 5.0.8 on 2024-10-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0045_alter_cluster_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypoint',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_points', to='service.connection'),
        ),
    ]
