# Generated by Django 5.0.8 on 2024-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_alter_supplypoint_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeposition',
            name='reader_observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
