# Generated by Django 5.0.8 on 2024-11-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0051_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='service.property'),
        ),
    ]
