# Generated by Django 5.0.8 on 2025-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='digits',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
