# Generated by Django 5.0.8 on 2025-01-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0053_meter_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_property',
            field=models.BooleanField(default=False),
        ),
    ]
