# Generated by Django 5.0.8 on 2025-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0054_meter_is_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypoint',
            name='is_potable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplypoint',
            name='supply_point_childs',
            field=models.ManyToManyField(blank=True, to='service.supplypoint'),
        ),
    ]
