# Generated by Django 5.0.8 on 2025-01-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_supplypoint_is_potable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplypoint',
            old_name='supply_point_childs',
            new_name='supply_point_children',
        ),
    ]
