# Generated by Django 5.0.8 on 2025-02-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_biller_period_type_billingbatch_template'),
        ('service', '0056_rename_supply_point_childs_supplypoint_supply_point_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='batch_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='billing.billingbatchtemplate'),
        ),
    ]
