# Generated by Django 5.0.8 on 2025-02-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0058_supplycutcause_supplycut_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplycutcause',
            name='position',
        ),
    ]
