# Generated by Django 5.0.8 on 2025-02-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0059_remove_supplycutcause_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplycutcause',
            name='is_default',
        ),
    ]
