# Generated by Django 5.0.8 on 2025-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0060_remove_supplycutcause_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybank',
            name='is_sepa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companybank',
            name='sepa_cred_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
