# Generated by Django 5.0.8 on 2025-02-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0057_route_batch_template'),
        ('service', '0061_companybank_is_sepa_companybank_sepa_cred_identifier'),
    ]

    operations = [
    ]
