# Generated by Django 5.0.8 on 2025-02-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0049_auto_20250130_1446'),
        ('service', '0062_merge_20250220_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='address_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_requests_billing', to='coredata.personaddress', verbose_name='Contract Billing Address'),
        ),
    ]
