# Generated by Django 5.0.8 on 2025-02-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0080_generalpayment'),
        ('coredata', '0049_auto_20250130_1446'),
        ('service', '0063_connectionrequest_address_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.generalpayment', verbose_name='Connection Payment'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='address_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_requests_billing', to='coredata.personaddress', verbose_name='Connection Billing Address'),
        ),
    ]
