# Generated by Django 5.0.8 on 2025-02-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0064_connectionrequest_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.company'),
        ),
    ]
