# Generated by Django 5.0.8 on 2025-03-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0061_metermanufacturer_metermodel'),
        ('service', '0065_connectionrequest_company'),
    ]

    operations = [
    ]
