# Generated by Django 5.0.8 on 2025-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0066_merge_20250304_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
