# Generated by Django 5.0.8 on 2025-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0067_alter_meter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
