# Generated by Django 5.0.8 on 2025-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0068_alter_meter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
