# Generated by Django 5.0.8 on 2025-03-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0069_meter_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
