# Generated by Django 5.0.8 on 2025-03-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0070_company_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='token',
        ),
    ]
