# Generated by Django 5.0.8 on 2025-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0071_remove_company_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplycut',
            name='supply_point',
        ),
        migrations.AddField(
            model_name='supplycut',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='supply_cuts', to='service.supplypoint'),
        ),
    ]
