# Generated by Django 5.0.8 on 2025-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0072_remove_supplycut_supply_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycut',
            name='supply_points',
            field=models.ManyToManyField(blank=True, null=True, related_name='supply_cuts', to='service.supplypoint'),
        ),
    ]
