# Generated by Django 5.0.8 on 2025-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0073_alter_supplycut_supply_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycut',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='supply_cuts', to='service.supplypoint'),
        ),
    ]
