# Generated by Django 5.0.8 on 2025-06-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0074_alter_supplycut_supply_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_send_service', models.CharField(blank=True, choices=[('smtp', 'SMTP'), ('gmail', 'Gmail')], max_length=255, null=True)),
                ('mail_send_smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_send_smtp_port', models.IntegerField(blank=True, null=True)),
                ('mail_send_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('mail_send_user', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_configs', to='service.company')),
            ],
        ),
    ]
