# Generated by Django 5.0.8 on 2025-06-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0075_companyconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyconfig',
            old_name='key',
            new_name='token',
        ),
    ]
