# Generated by Django 5.0.8 on 2025-06-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0076_rename_key_companyconfig_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_configs', to='service.companyconfig'),
        ),
    ]
