# Generated by Django 5.0.8 on 2025-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0042_delete_logsupplypointrequeststatus'),
        ('service', '0077_remove_companyconfig_company_company_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplypointrequestdocument',
            name='supply_point_request',
        ),
        migrations.RemoveField(
            model_name='supplypointrequestobservation',
            name='supplypoint_request',
        ),
        migrations.RemoveField(
            model_name='supplypointrequestdocument',
            name='supply_point_request_document_type',
        ),
        migrations.RemoveField(
            model_name='supplypointrequestobservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplypointrequestobservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupplyPointRequest',
        ),
        migrations.DeleteModel(
            name='SupplyPointRequestDocument',
        ),
        migrations.DeleteModel(
            name='SupplyPointRequestDocumentType',
        ),
        migrations.DeleteModel(
            name='SupplyPointRequestStatus',
        ),
        migrations.DeleteModel(
            name='SupplyPointRequestObservation',
        ),
    ]
