# Generated by Django 5.0.8 on 2025-06-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0078_remove_supplypointrequestdocument_supply_point_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplypoint',
            name='supply_postal_code',
        ),
        migrations.RemoveField(
            model_name='supplypoint',
            name='supply_street',
        ),
        migrations.RemoveField(
            model_name='supplypoint',
            name='supply_street_number',
        ),
    ]
