# Generated by Django 5.0.8 on 2025-06-25 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0172_remove_billingbatchtemplate_biller'),
        ('service', '0079_remove_supplypoint_supply_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='batch_template',
        ),
        migrations.AddField(
            model_name='route',
            name='biller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='billing.biller'),
        ),
    ]
