# Generated by Django 5.0.8 on 2025-06-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0175_rename_billingbatchtemplate_readingbatchtemplate_and_more'),
        ('service', '0080_remove_route_batch_template_route_biller'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='reading_batch_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='billing.readingbatchtemplate'),
        ),
    ]
