# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0082_meterlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'verbose_name': 'Connection Request', 'verbose_name_plural': 'Connection Requests'},
        ),
        migrations.AlterModelOptions(
            name='exploitation',
            options={'verbose_name': 'Exploitation', 'verbose_name_plural': 'Exploitations'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': 'Meter', 'verbose_name_plural': 'Meters'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='supplycut',
            options={'verbose_name': 'Supply Cut', 'verbose_name_plural': 'Supply Cuts'},
        ),
        migrations.AlterModelOptions(
            name='supplypoint',
            options={'verbose_name': 'Supply Point', 'verbose_name_plural': 'Supply Points'},
        ),
    ]
