# Generated by Django 5.0.8 on 2025-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0083_alter_cluster_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycut',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplycut',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
