# Generated by Django 5.0.8 on 2025-09-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0084_alter_supplycut_date_end_alter_supplycut_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='supply_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointsupplytype', verbose_name='SupplyPoint SupplyType'),
        ),
    ]
