# Generated by Django 5.0.8 on 2025-09-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0085_connection_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='supply_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypointsupplytype', verbose_name='SupplyType'),
        ),
    ]
