# Generated by Django 5.0.8 on 2025-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0086_alter_connection_supply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='has_remote_reading',
            field=models.BooleanField(default=False),
        ),
    ]
