# Generated by Django 5.0.8 on 2025-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0087_meter_has_remote_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='barcode_ident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
