# Generated by Django 5.0.8 on 2025-11-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0090_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='service.companytype'),
        ),
    ]
