# Generated by Django 5.0.8 on 2026-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0093_exploitation_accountant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeposition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
