# Generated by Django 5.0.8 on 2026-02-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0093_exploitation_accountant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybank',
            name='barcode_cif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
