# Generated by Django 5.0.8 on 2026-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0086_returnreason'),
        ('service', '0094_add_name_to_route_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeposition',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='route_positions', to='coredata.address'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='properties_m2m',
            field=models.ManyToManyField(blank=True, related_name='route_positions_m2m', to='service.property'),
        ),
        migrations.AddField(
            model_name='routeposition',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='route_positions', to='service.supplypoint'),
        ),
    ]
