# Generated by Django 5.0.8 on 2026-02-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0094_companybank_barcode_cif'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_main_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_secondary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
