# Generated by Django 5.0.8 on 2026-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0095_add_m2m_to_route_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeposition',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='routeposition',
            name='properties_m2m',
        ),
        migrations.RemoveField(
            model_name='routeposition',
            name='supply_points',
        ),
    ]
