# Generated by Django 5.0.8 on 2026-02-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0095_company_invoice_footer_text_and_more'),
        ('service', '0096_remove_m2m_from_route_position'),
    ]

    operations = [
    ]
