# Generated by Django 5.0.8 on 2026-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0097_merge_20260225_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='address_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
