# Generated by Django 5.0.8 on 2026-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0099_exploitation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='mail_send_contact_footer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
