# Generated by Django 5.0.8 on 2026-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0100_companyconfig_mail_send_contact_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_protection_law_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
