# Generated by Django 5.0.8 on 2026-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0101_company_data_protection_law_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='use_SSL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='use_TLS',
            field=models.BooleanField(default=False),
        ),
    ]
