# Generated by Django 5.0.8 on 2026-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0102_companyconfig_use_ssl_companyconfig_use_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='use_SSL',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='use_TLS',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
