# Generated by Django 5.0.8 on 2026-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0103_alter_companyconfig_use_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
