# Generated by Django 5.0.8 on 2026-06-03 06:23

from django.db import migrations, models


def make_default_company(apps, schema_editor):
    Company = apps.get_model('service', 'Company')
    # Use try-except to get ConfigProject from coredata
    try:
        ConfigProject = apps.get_model('coredata', 'ConfigProject')
        config = ConfigProject.objects.filter(token='main_company_token').first()
        if config and config.value:
            vat_val = config.value.strip()
            Company.objects.filter(vat=vat_val).update(is_default=True)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0105_alter_company_contact_phone_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(make_default_company, reverse_code=migrations.RunPython.noop),
    ]
