# Generated by Django 5.0.8 on 2026-06-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0027_fix_finalized_processes_status'),
        ('service', '0106_company_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfigEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_send_user', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_send_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_config_emails', to='service.companyconfig')),
                ('use_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationusetype', verbose_name='Connection Use Type')),
            ],
        ),
    ]
