# Generated by Django 5.0.8 on 2026-06-09 06:17

from django.db import migrations


def move_email_to_company_config_email(apps, schema_editor):
    try:
        CompanyConfig = apps.get_model('service', 'CompanyConfig')
        CompanyConfigEmail = apps.get_model('service', 'CompanyConfigEmail')
        CommunicationUseType = apps.get_model('communication', 'CommunicationUseType')
        use_type = CommunicationUseType.objects.filter(is_default=True).first()
        for company_config in CompanyConfig.objects.all():
            CompanyConfigEmail.objects.create(
                company_config=company_config,
                mail_send_user=company_config.mail_send_user,
                mail_send_mail=company_config.mail_send_mail,
                use_type=use_type,
                is_default=True,
            )
    except Exception as e:
        print(f"Error moving email to company config email: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('service', '0107_companyconfigemail'),
    ]

    operations = [
        migrations.RunPython(move_email_to_company_config_email),
    ]
