# Generated by Django 5.0.8 on 2026-06-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0108_move_companyconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='mail_send_mail',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='mail_send_user',
        ),
    ]
