# Generated by Django 5.0.8 on 2026-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0111_add_cluster_documentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='has_ever_been_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter',
            name='remote_reading_type',
            field=models.CharField(blank=True, choices=[('SMART_METERING', 'Smart Metering'), ('AGBAR', 'Agbar')], default='AGBAR', max_length=255, null=True),
        ),
    ]
