# Generated by Django 5.0.8 on 2026-06-23 10:38

from django.db import migrations

def set_has_ever_been_remote(apps, schema_editor):
    Meter = apps.get_model('service', 'Meter')
    meters = Meter.objects.filter(has_remote_reading=True)
    meters.update(has_ever_been_remote=True)

class Migration(migrations.Migration):

    dependencies = [
        ('service', '0112_meter_has_ever_been_remote_meter_remote_reading_type'),
    ]

    operations = [
        migrations.RunPython(set_has_ever_been_remote),
    ]
