# Generated by Django 5.0.8 on 2026-06-29 10:42

from django.db import migrations, models

def change_remote_reading_type(apps, schema_editor):
    Meter = apps.get_model('service', 'Meter')
    meters = Meter.objects.filter(remote_reading_type='AGBAR')
    meters.update(remote_reading_type='OTHER')

class Migration(migrations.Migration):

    dependencies = [
        ('service', '0113_set_has_ever_been_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='remote_reading_type',
            field=models.CharField(blank=True, choices=[('SMART_METERING', 'Smart Metering'), ('OTHER', 'Other')], default='OTHER', max_length=255, null=True),
        ),
        migrations.RunPython(change_remote_reading_type),
    ]
