# Generated by Django 5.0.8 on 2026-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0112_add_smart_metering_authentication_token'),
        ('service', '0114_alter_meter_remote_reading_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='routeposition',
            index=models.Index(fields=['route', 'position'], name='service_rou_route_i_120d6c_idx'),
        ),
    ]
