# Generated by Django 5.0.8 on 2026-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0118_add_company_text_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='force_manual_reading',
            field=models.BooleanField(default=False),
        ),
    ]
