# Generated by Django 5.0.8 on 2026-09-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0119_meter_force_manual_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycut',
            name='exec_end',
            field=models.DateTimeField(
                blank=True,
                help_text='Fi real del tall (Giswater exec_end). Es seta en finalitzar el mincut.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='exec_start',
            field=models.DateTimeField(
                blank=True,
                help_text='Inici real del tall (Giswater exec_start). Es seta en arrencar el mincut.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='source',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('giswater', 'Giswater')],
                default='manual',
                help_text='Origen del tall. Els de Giswater s\'activen/desactiven per exec_*; els manuals, per date_*.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='supplycut',
            name='date_end',
            field=models.DateTimeField(
                blank=True,
                help_text='Previsió de fi del tall (Giswater forecast_end).',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='supplycut',
            name='date_start',
            field=models.DateTimeField(
                blank=True,
                help_text="Previsió d'inici del tall (Giswater forecast_start). Data que es comunica als abonats.",
                null=True,
            ),
        ),
    ]
