# Generated by Django 5.0.8 on 2026-09-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0131_personlog'),
        ('service', '0120_supplycut_exec_dates_and_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('match_type', models.CharField(choices=[('payer_bank', 'Entitat del pagador'), ('foreign', 'IBAN estranger'), ('default', 'Per defecte')], default='payer_bank', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_routings', to='coredata.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_routings', to='service.company')),
                ('company_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='service.companybank')),
            ],
            options={
                'verbose_name': 'Company Bank Routing',
                'verbose_name_plural': 'Company Bank Routings',
            },
        ),
        migrations.AddConstraint(
            model_name='companybankrouting',
            constraint=models.UniqueConstraint(condition=models.Q(('match_type', 'payer_bank')), fields=('company', 'bank'), name='unique_company_payer_bank_routing'),
        ),
        migrations.AddConstraint(
            model_name='companybankrouting',
            constraint=models.UniqueConstraint(condition=models.Q(('match_type', 'payer_bank'), _negated=True), fields=('company', 'match_type'), name='unique_company_special_routing'),
        ),
    ]
