# Generated by Django 5.0.8 on 2026-09-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0122_supply_cut_status_closed_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycut',
            name='cause_raw',
            field=models.CharField(blank=True, help_text='Ultim valor cru del motiu provinent de Giswater (anl_cause).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='mincut_cause_token',
            field=models.CharField(blank=True, help_text='Token del catàleg de motiu del PA assignat al sincronitzar.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='mincut_state_token',
            field=models.CharField(blank=True, help_text="Token del catàleg d'estat del PA assignat al sincronitzar.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='requires_review',
            field=models.BooleanField(default=False, help_text="Cal revisio manual: l'estat/motiu de Giswater no s'ha pogut assignar a cap cataleg del PA."),
        ),
        migrations.AddField(
            model_name='supplycut',
            name='state_raw',
            field=models.CharField(blank=True, help_text="Ultim valor cru de l'estat provinent de Giswater (state).", max_length=255, null=True),
        ),
    ]
