# Generated by Django 5.0.8 on 2026-10-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0126_move_supply_code_to_company'),
        ('service', '0128_supply_cut_status_planificat'),
    ]

    operations = [
    ]
