# Generated by Django 5.0.8

import django.db.models.deletion
from django.db import migrations, models


def _table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def create_integration_tables_if_missing(apps, schema_editor):
    """
    Bases ja migrades amb les migracions antigues d'integrations poden tenir
    les taules creades sense tenir registrada aquesta 0001 squasheada.

    Fem servir els models reals (no el registry històric) perquè amb
    SeparateDatabaseAndState els CreateModel només són a state_operations i
    encara no existeixen a from_state.apps quan corre aquest RunPython.
    """
    from django.apps import apps as global_apps

    models_to_create = (
        global_apps.get_model("integrations", "IntegrationRequestLog"),
        global_apps.get_model("integrations", "ContractSigningSession"),
    )
    for model in models_to_create:
        if not _table_exists(schema_editor, model._meta.db_table):
            schema_editor.create_model(model)


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("integrations", "0002_contractsigningsession"),
        ("integrations", "0003_contractsigningsession_contract_request"),
    ]

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_integration_tables_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
        migrations.CreateModel(
            name="IntegrationRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractSigningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=36, unique=True)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("signing_url", models.URLField(blank=True, max_length=500)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=50)),
                ("callback_url", models.URLField(blank=True, max_length=500)),
                ("email_sent", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_sessions",
                        to="contract.contractrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
            ],
        ),
    ]
