"""
Django settings for customers project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import re
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="Unsafe-default-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

# SECURITY WARNING: update this when you have the production host

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DOMAIN_MEDIA = config("DOMAIN_MEDIA", default="")

# Trust the X-Forwarded-Proto header set by the reverse proxy (nginx/traefik in Docker).
# Without this, Django sees the internal HTTP connection and generates http:// URLs.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

DOCUMENT_MANAGER_BASE_PATH = config("DOCUMENT_MANAGER_PATH", default=BASE_DIR)
DOCUMENT_STORAGE_PATH = os.path.join(DOCUMENT_MANAGER_BASE_PATH, "media", "documents")

allowed_hosts_str = config("ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(",")]
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=['172.24.119.18','127.0.0.1'])

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="http://").split(",")


FTP_HOST = config("FTP_HOST", default="")
FTP_USER = config("FTP_USER", default="")
FTP_PASSWORD = config("FTP_PASSWORD", default="")

PFX_PASS = config("PFX_PASS", default="")
PFX_PATH = config("PFX_PATH", default="")

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="")
AWS_REGION = config("AWS_REGION", default="")
AWS_LOCATION = config("AWS_LOCATION", default="")

ALFRESCO_BASE_URL = config("ALFRESCO_BASE_URL", default="")
ALFRESCO_USERNAME = config("ALFRESCO_USERNAME", default="")
ALFRESCO_PASSWORD = config("ALFRESCO_PASSWORD", default="")

AZURE_ACCOUNT_URL = config("AZURE_ACCOUNT_URL", default="")
AZURE_ACCOUNT_NAME = config("AZURE_ACCOUNT_NAME", default="")
AZURE_ACCOUNT_KEY = config("AZURE_ACCOUNT_KEY", default="")
AZURE_CONTAINER_NAME = config("AZURE_CONTAINER_NAME", default="")

CLOUD_BUCKET_NAME = config("CLOUD_BUCKET_NAME", default="")

ENV = config("ENV", default="")
LANGUAGE = config("LANGUAGE", default="ca")

VERIFACTU_ENABLED = config("VERIFACTU_ENABLED", default=False, cast=bool)
# Verifactu SOAP Configuration
VERIFACTU_WSDL_URL = config("VERIFACTU_WSDL_URL", default="")
VERIFACTU_CERT_FILE_PATH = config("VERIFACTU_CERT_FILE_PATH", default=None)
VERIFACTU_CERT_KEY = config("VERIFACTU_CERT_KEY", default=None)
VERIFACTU_SOAP_TIMEOUT = config("VERIFACTU_SOAP_TIMEOUT", default=30, cast=int)
VERIFACTU_VERIFY_SSL = config("VERIFACTU_VERIFY_SSL", default=True, cast=bool)
VERIFACTU_SERVICE_NAME = config("VERIFACTU_SERVICE_NAME", default=None)
VERIFACTU_PORT_NAME = config("VERIFACTU_PORT_NAME", default=None)
VERIFACTU_URL_VALIDATOR = config("VERIFACTU_URL_VALIDATOR", default=None)
VERIFACTU_NIF = config("VERIFACTU_NIF", default=None)
# Bloc `SistemaInformatico` dels registres: identifica el fabricant del programari (no el client)
# i la instal·lació. `VERIFACTU_NUMERO_INSTALACION` ha de ser propi de cada instal·lació.
VERIFACTU_SISTEMA_INFORMATICO = {
    "NombreRazon": config("VERIFACTU_SISTEMA_NOMBRE_RAZON", default="Aigües de Vic Enginyeria i Tecnologia S.L"),
    "NIF": config("VERIFACTU_SISTEMA_NIF", default="B10721355"),
    "NombreSistemaInformatico": config("VERIFACTU_SISTEMA_NOMBRE", default="Aqua customers"),
    "IdSistemaInformatico": config("VERIFACTU_SISTEMA_ID", default="77"),
    "Version": config("VERIFACTU_SISTEMA_VERSION", default="1.0.03"),
    "NumeroInstalacion": config("VERIFACTU_NUMERO_INSTALACION", default="383"),
    "TipoUsoPosibleSoloVerifactu": "S",
    "TipoUsoPosibleMultiOT": "S",
    "IndicadorMultiplesOT": "S",
}

DOCUMENT_MANAGER_SERVICES = {
    "contract": config("DOCUMENT_MANAGER_CONTRACT", default="hdd"),
    "billing": config("DOCUMENT_MANAGER_BILLING", default="hdd"),
    "template": config("DOCUMENT_MANAGER_TEMPLATES", default="hdd"),
    "fraud": config("DOCUMENT_MANAGER_FRAUD", default="hdd"),
    "statistics": config("DOCUMENT_MANAGER_STATISTICS", default="hdd"),
    "order": config("DOCUMENT_MANAGER_ORDER", default="hdd"),
    "communication": config("DOCUMENT_MANAGER_COMMUNICATION", default="hdd"),
    "connection": config("DOCUMENT_MANAGER_CONNECTION", default="hdd"),
}

# Application definition
OWN_APPS = [
    "coredata",
    "service",
    "contract",
    "order",
    "logger",
    "pricing",
    "billing",
    "search",
    "documentmanager",
    "notification",
    "statistics",
    "claimrequest",
    "fraud",
    "communication",
    "lecturapp",
    "got",
    "ov",
    "verifactu",
    "watchdog",
    "integrations",
]

EXTRA_APPS = [
    "rest_framework",
    "rest_framework.authtoken",  # Ensure this is included
    "corsheaders",
    "django_filters",
]

# Apps només per a ús intern, que no es pugen al repositori (p. ex. `importexport`, eines de
# càrrega de dades de clients). S'activen des del .env amb una llista separada per comes:
#   LOCAL_OWN_APPS=importexport
#   LOCAL_EXTRA_APPS=debug_toolbar
# Si una app local té `urls.py`, es munta a `/<app>/` (vegeu customers/urls.py).
LOCAL_OWN_APPS = config("LOCAL_OWN_APPS", default="", cast=Csv())
LOCAL_EXTRA_APPS = config("LOCAL_EXTRA_APPS", default="", cast=Csv())


def _check_local_apps(apps):
    from importlib.util import find_spec

    missing = [app for app in apps if find_spec(app.split(".")[0]) is None]
    if missing:
        raise ImproperlyConfigured(
            f"LOCAL_OWN_APPS/LOCAL_EXTRA_APPS inclou apps que no existeixen en aquesta còpia: {', '.join(missing)}"
        )
    return apps


OWN_APPS += _check_local_apps(LOCAL_OWN_APPS)
EXTRA_APPS += _check_local_apps(LOCAL_EXTRA_APPS)


INSTALLED_APPS = (
    [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django.contrib.postgres",
        "django.contrib.sites",
        "django_extensions",
        "msgraphbackend",
    ]
    + EXTRA_APPS
    + OWN_APPS
)
SITE_ID = 1
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n language detection
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Ha d'anar abans dels middlewares d'usuari actual: resol l'usuari del token DRF
    "ov.middleware.RestrictOVUserMiddleware",
    "order.middleware.CurrentUserMiddleware",
    "contract.middleware.UserMiddleware",
    "logger.middleware.PostRequestLoggingMiddleware",  # Custom middleware for logging POST requests
    "coredata.middleware.SetPostgresUserMiddleware",
]

ROOT_URLCONF = "customers.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "ov", "templates"),
        ],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": [
                "coredata.utils.template_utils.PersonalizedFilesystemLoader",
                "coredata.utils.template_utils.PersonalizedAppDirectoriesLoader",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [
                "billing.templatetags.billing_filters",
            ],
        },
    },
]



# Email backend: SMTP per defecte; sobreescrivible via .env
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)

# Microsoft Graph (Office365/Outlook) - només s'aplica si l'EMAIL_BACKEND ho indica
if EMAIL_BACKEND == "msgraphbackend.MSGraphBackend":
    MSGRAPH_TENANT_ID = config("MSGRAPH_TENANT_ID", default="")
    MSGRAPH_CLIENT_ID = config("MSGRAPH_CLIENT_ID", default="")
    MSGRAPH_CLIENT_SECRET = config("MSGRAPH_CLIENT_SECRET", default="")
    MSGRAPH_USER_ID = config("MSGRAPH_USER_ID", default="")  # Optional



EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST = config("EMAIL_HOST", default="localhost")
EMAIL_PORT = config("EMAIL_PORT", default=25, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

SMS_APP_URL = config("SMS_APP_URL", default="")
SMS_API_KEY = config("SMS_API_KEY", default="")

customers01 = config("EMAIL_PASSWORD_01", default="")



WSGI_APPLICATION = "customers.wsgi.application"

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
INSTALLED_APPS += ["django_celery_results"]
INSTALLED_APPS += ["celery_progress"]

CELERY_TRACK_STARTED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DATABASE_NAME", default="avsis-customers"),
        "USER": config("DATABASE_USER", default="avsis"),
        "PASSWORD": config("DATABASE_PASSWORD", default="avsis"),
        "HOST": config("DATABASE_HOST", default="localhost"),
        "PORT": config("DATABASE_PORT", cast=int, default=5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE", default=config("LANGUAGE", default="ca"))  # Fallback to LANGUAGE if set

LANGUAGES = [
    ('ca', 'Català'),
    ('es', 'Español'),
    ('gl', 'Galego'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = "Europe/Madrid"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Cache (e.g. for contract list first page). Uses local memory by default.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}

# Optional: contract list first-page cache TTL in seconds (default 300 = 5 min)
CONTRACT_LIST_CACHE_TIMEOUT = config("CONTRACT_LIST_CACHE_TIMEOUT", default=1500, cast=int)

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # "format" is a business query parameter in the OV download endpoints
    # (?format=pdf|csv|zip) and in reading-batch downloads, so DRF must not
    # hijack it for renderer content negotiation (otherwise ?format=csv raises
    # NotFound). Renderer selection keeps working via Accept headers/suffixes.
    "URL_FORMAT_OVERRIDE": None,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# Optional: Add REST Framework Token Authentication settings if needed
REST_FRAMEWORK.update(
    {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "rest_framework.authentication.TokenAuthentication",
        ),
    }
)

CORS_ALLOW_ALL_ORIGINS = True

# CORS Headers Configuration
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-app-token",  # Allow x-app-token header for lecturapp authentication
]
import os

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
        "post_file": {
            "level": "INFO",
            "class": "customers.logging_handlers.PerPostFileHandler",
            "log_dir": LOG_DIR,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "faker": {"level": "ERROR"},
        "matplotlib": {"level": "WARNING"},
        "django.utils.autoreload": {"level": "WARNING"},
        "post_requests": {
            "handlers": ["post_file", "console"],  # file per-post + console output
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

INVOICE_LANGUAGE = os.getenv("INVOICE_LANGUAGE", "ca")  # Default to 'ca' if not set


# GMAO Figueres
# # GMAO S3 Configuration (external bucket for GMAO files)
# GMAO_AWS_ACCESS_KEY = config("GMAO_AWS_ACCESS_KEY", default="")
# GMAO_AWS_SECRET_KEY = config("GMAO_AWS_SECRET_KEY", default="")
# GMAO_AWS_S3_BUCKET = config("GMAO_AWS_S3_BUCKET", default="")
# GMAO_AWS_S3_URL = config("GMAO_AWS_S3_URL", default="")
# GMAO_AWS_S3_SIGNING_REGION = config("GMAO_AWS_S3_SIGNING_REGION", default="eu-west-1")

# RabbitMQ Configuration
RABBITMQ_ENABLED = config("RABBITMQ_ENABLED", default=False, cast=bool)
RABBITMQ_URL = config("RABBITMQ_URL", default="amqp://guest:guest@localhost:5672//")

# Optional: when empty, the GMAO integration keeps the legacy single-queue behaviour
INSTANCE_UID = config("INSTANCE_UID", default="").strip()

if INSTANCE_UID and not re.fullmatch(r"[A-Za-z0-9._-]{1,64}", INSTANCE_UID):
    raise ImproperlyConfigured(
        f"INSTANCE_UID '{INSTANCE_UID}' is invalid: allowed characters are "
        "letters, digits, '.', '_' and '-' (max 64)."
    )

# Exchange and queue names
RABBIT_IN_EXCHANGE = config("RABBIT_IN_EXCHANGE", default="gmao-events-exchange")
RABBIT_IN_QUEUE_PREFIX = config(
    "RABBIT_IN_QUEUE", default="gmao-events"
)  # We CONSUME from here
RABBIT_IN_QUEUE = (
    f"{RABBIT_IN_QUEUE_PREFIX}-{INSTANCE_UID}" if INSTANCE_UID else RABBIT_IN_QUEUE_PREFIX
)
RABBIT_IN_ROUTING_KEY = INSTANCE_UID if INSTANCE_UID else RABBIT_IN_QUEUE_PREFIX
RABBIT_OUT_QUEUE = config("RABBIT_OUT_QUEUE", default="crm-events")  # We PRODUCE to here

GMAO_HOST = config("GMAO_HOST", default="http://localhost:8000/")

GISWATER_BASE_URL = config("GISWATER_BASE_URL", default="")
GISWATER_TOKEN = config("GISWATER_TOKEN", default="")
GISWATER_TIMEOUT = config("GISWATER_TIMEOUT", default=30, cast=int)
GISWATER_KEYCLOAK_URL = config("GISWATER_KEYCLOAK_URL", default="")
GISWATER_REALM = config("GISWATER_REALM", default="")
GISWATER_CLIENT_ID = config("GISWATER_CLIENT_ID", default="")
GISWATER_CLIENT_SECRET = config("GISWATER_CLIENT_SECRET", default="")
# HTTP Basic Auth (fallback si GISWATER_KEYCLOAK_URL està buit)
GISWATER_USERNAME = config("GISWATER_USERNAME", default="")
GISWATER_PASSWORD = config("GISWATER_PASSWORD", default="")
GISWATER_SYNC_CONNECS_ENABLED = config(
    "GISWATER_SYNC_CONNECS_ENABLED", default=False, cast=bool
)
GISWATER_SYNC_CONNECS_HOUR = config("GISWATER_SYNC_CONNECS_HOUR", default=3, cast=int)
GISWATER_SYNC_CONNECS_MINUTE = config(
    "GISWATER_SYNC_CONNECS_MINUTE", default=0, cast=int
)

SIGNING_BASE_URL = config("SIGNING_BASE_URL", default="")
SIGNING_API_KEY = config("SIGNING_API_KEY", default="")
SIGNING_CALLBACK_URL = config("SIGNING_CALLBACK_URL", default="")
SIGNING_TIMEOUT = config("SIGNING_TIMEOUT", default=30, cast=int)
SIGN_CALLBACK_API_KEY = config("SIGN_CALLBACK_API_KEY", default="")

# Sondeig de les sessions d'Aqua360 Sign: alternativa al webhook `session.signed`
# per a les instal·lacions on Sign no pot arribar al backend (IP privada), i xarxa
# de seguretat per als callbacks perduts. Vegeu integrations/outbound/signing/polling.py.
SIGNING_POLL_ENABLED = config("SIGNING_POLL_ENABLED", default=False, cast=bool)
SIGNING_POLL_MINUTES = config("SIGNING_POLL_MINUTES", default=10, cast=int)

ODOO_BASE_URL = config("ODOO_BASE_URL", default="")
ODOO_API_KEY = config("ODOO_API_KEY", default="")
ODOO_TIMEOUT = config("ODOO_TIMEOUT", default=30, cast=int)
ODOO_PUSH_ENABLED = config("ODOO_PUSH_ENABLED", default=False, cast=bool)
ODOO_PUSH_INVOICES = config("ODOO_PUSH_INVOICES", default=True, cast=bool)
ODOO_PUSH_PAYMENTS = config("ODOO_PUSH_PAYMENTS", default=True, cast=bool)

SMART_METERING_API_URL = config("SMART_METERING_API_URL", default="")
SMART_METERING_API_AUTH_PARAM = config("SMART_METERING_API_AUTH_PARAM", default="Authorization")
SMART_METERING_API_TIMEOUT = config("SMART_METERING_API_TIMEOUT", default=30, cast=int)
SMART_METERING_API_MARGIN = config("SMART_METERING_API_MARGIN", default=5, cast=int)