# Generated by Django 5.0.8 on 2024-10-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricerate_exploitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerateitem',
            name='price_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rate_items', to='pricing.priceinterval'),
        ),
    ]
