# Generated by Django 5.0.8 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pricerateitem_price_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrange',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingrange',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='boe_date',
            field=models.DateField(blank=True, null=True, verbose_name='BOE Date'),
        ),
    ]
