# Generated by Django 5.0.8 on 2024-10-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_billingrange_end_alter_billingrange_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerateitem',
            name='billing_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rate_items', to='pricing.billingrange'),
        ),
    ]
