# Generated by Django 5.0.8 on 2024-11-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_pricerateitem_billing_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerateitem',
            name='billing_range',
        ),
        migrations.RemoveField(
            model_name='pricerateitem',
            name='price_interval',
        ),
        migrations.RemoveField(
            model_name='pricerateitem',
            name='price_rate',
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='fourth_stretch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='third_stretch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='billing_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='pricing.billingrange'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='calculation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='price_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='pricing.priceinterval'),
        ),
        migrations.AddField(
            model_name='pricerateitem',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
