# Generated by Django 5.0.8 on 2024-11-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_remove_pricerateitem_billing_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIntervalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('limit', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='first_stretch',
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='fourth_stretch',
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='second_stretch',
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='third_stretch',
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='units',
            field=models.CharField(choices=[('m3', 'm3'), ('dm', 'diametre')], default='m3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.product'),
        ),
        migrations.AlterField(
            model_name='pricerate',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(choices=[('add', 'Addition'), ('dec', 'Decrease'), ('ptg', 'Percentage')], default='ptg')),
                ('fixed_price', models.FloatField(blank=True, null=True)),
                ('proportional_price', models.FloatField(blank=True, null=True)),
                ('fixed_interval', models.FloatField(blank=True, null=True)),
                ('custom_interval_percentage', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='pricing.priceinterval')),
                ('price_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.pricerate')),
            ],
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='price_interval_items',
            field=models.ManyToManyField(blank=True, related_name='price_intervals', to='pricing.priceintervalitem'),
        ),
        migrations.DeleteModel(
            name='PriceRateItem',
        ),
    ]
