# Generated by Django 5.0.8 on 2024-11-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_priceintervalitem_remove_priceinterval_first_stretch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinterval',
            name='price_interval_items',
        ),
        migrations.AddField(
            model_name='priceintervalitem',
            name='price_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_interval_items', to='pricing.priceinterval'),
        ),
    ]
