# Generated by Django 5.0.8 on 2024-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_remove_priceinterval_price_interval_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('aigua', 'Aigua'), ('contracte', 'Contracte'), ('lectura', 'Lectura'), ('altres', 'Altres')], default='aigua'),
        ),
    ]
