# Generated by Django 5.0.8 on 2024-11-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0120_merge_20241126_0819'),
        ('pricing', '0010_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='bonification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.bonificationtype'),
        ),
    ]
