# Generated by Django 5.0.8 on 2024-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_adjustment_bonification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_rate',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='products',
            field=models.ManyToManyField(related_name='price_rates', to='pricing.product'),
        ),
    ]
