# Generated by Django 5.0.8 on 2024-11-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_remove_product_price_rate_pricerate_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerate',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='price_rates', to='pricing.product'),
        ),
    ]
