# Generated by Django 5.0.8 on 2024-11-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_alter_pricerate_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='products',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='pricing.product'),
        ),
    ]
