# Generated by Django 5.0.8 on 2024-11-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_remove_pricerate_products_pricerate_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='bonification_type',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='price_rate',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='billing_range',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='price_interval',
        ),
        migrations.AddField(
            model_name='billingrange',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_ranges', to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='operation',
            field=models.CharField(choices=[('add', 'Suma'), ('dec', 'Resta'), ('ptg', 'Percentatge')], default='ptg'),
        ),
        migrations.AlterField(
            model_name='billingrange',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_ranges', to='pricing.publication'),
        ),
        migrations.CreateModel(
            name='LineItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('proporcional_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.CharField(choices=[('consumreal', 'Consum Real'), ('adjestimacio', 'Adjustament per estimació'), ('adjre', 'Adjustament per re...'), ('altres', 'Altres adjustaments')], default='consumreal')),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_period', models.CharField(blank=True, max_length=255, null=True)),
                ('taxes', models.CharField(choices=[('IvA', 'I.V.A. Alt'), ('IvE', 'I.V.A. Exempt'), ('IvM', 'I.V.A. Mitjà'), ('IvB', 'I.V.A. Baix'), ('IgA', 'IGIC Alt'), ('IgE', 'IGIC Exempt'), ('IgM', 'IGIC Mitjà'), ('IgB', 'IGIC Baix')], default='IvB')),
                ('is_active', models.BooleanField(default=True)),
                ('billing_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.billingrange')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.lineitem')),
                ('price_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.priceinterval')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.lineitemtype'),
        ),
    ]
