# Generated by Django 5.0.8 on 2024-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_remove_adjustment_bonification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtype',
            name='billing_period',
            field=models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quatrimestral', 'Quadrimestral'), ('mensual', 'Mensual'), ('diaria', 'Diaria')], default='mensual'),
        ),
    ]
