# Generated by Django 5.0.8 on 2024-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_alter_lineitemtype_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinterval',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='proporcional_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PriceIntervalItem',
        ),
    ]
