# Generated by Django 5.0.8 on 2024-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_priceinterval_price_priceinterval_proporcional_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtype',
            name='billing_period',
            field=models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('mensual', 'Mensual'), ('diaria', 'Diaria')], default='mensual'),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='quantity',
            field=models.CharField(choices=[('consumreal', 'Consum Real'), ('adjestimacio', 'Adjustament per estimació'), ('adjre', 'Adjustament'), ('altres', 'Altres adjustaments')], default='consumreal'),
        ),
    ]
