# Generated by Django 5.0.8 on 2024-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_alter_lineitemtype_billing_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIntervalStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('proporcional_price', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(choices=[('m3', 'm3'), ('dm', 'diametre')], default='m3')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='priceinterval',
            old_name='price',
            new_name='demographic_coefficient',
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='proporcional_price',
        ),
        migrations.RemoveField(
            model_name='priceinterval',
            name='units',
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='price_interval_stretches',
            field=models.ManyToManyField(blank=True, related_name='price_intervals', to='pricing.priceintervalstretch'),
        ),
    ]
