# Generated by Django 5.0.8 on 2024-12-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_priceintervalstretch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinterval',
            name='price_interval_stretches',
        ),
        migrations.AddField(
            model_name='priceintervalstretch',
            name='price_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_interval_stretches', to='pricing.priceinterval'),
        ),
        migrations.AddField(
            model_name='priceintervalstretch',
            name='stretch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
