# Generated by Django 5.0.8 on 2024-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_remove_priceinterval_price_interval_stretches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceintervalstretch',
            name='end_stretch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceintervalstretch',
            name='start_stretch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
