# Generated by Django 5.0.8 on 2024-12-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_priceintervalstretch_end_stretch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='billing_period_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='quantity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
