# Generated by Django 5.0.8 on 2024-12-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_lineitemtype_billing_period_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('mensual', 'Mensual'), ('diaria', 'Diaria')], default='mensual')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('consumreal', 'Consum Real'), ('adjestimacio', 'Adjustament per estimació'), ('adjre', 'Adjustament'), ('altres', 'Altres adjustaments')], default='consumreal')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('IvA', 'I.V.A. Alt'), ('IvE', 'I.V.A. Exempt'), ('IvM', 'I.V.A. Mitjà'), ('IvB', 'I.V.A. Baix'), ('IgA', 'IGIC Alt'), ('IgE', 'IGIC Exempt'), ('IgM', 'IGIC Mitjà'), ('IgB', 'IGIC Baix')], default='IvB')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lineitemtype',
            name='billing_period_name',
        ),
        migrations.RemoveField(
            model_name='lineitemtype',
            name='line_item',
        ),
        migrations.RemoveField(
            model_name='lineitemtype',
            name='quantity_name',
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='billing_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.billingperiod'),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.quantity'),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.taxes'),
        ),
    ]
