# Generated by Django 5.0.8 on 2024-12-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0024_billingperiod_quantity_taxes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingperiod',
            name='position',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='position',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='position',
        ),
    ]
