# Generated by Django 5.0.8 on 2024-12-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_remove_billingperiod_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
