# Generated by Django 5.0.8 on 2024-12-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_remove_billingperiod_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerate',
            name='billing_range_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='pricing.billingrange'),
        ),
    ]
