# Generated by Django 5.0.8 on 2024-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_delete_lineitem'),
        ('pricing', '0026_pricerate_billing_range_active'),
    ]

    operations = [
    ]
