# Generated by Django 5.0.8 on 2024-12-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_merge_20241212_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceintervalstretch',
            name='start_stretch',
        ),
    ]
