# Generated by Django 5.0.8 on 2024-12-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemtype',
            name='taxes',
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.tax'),
        ),
    ]
