# Generated by Django 5.0.8 on 2024-12-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoicelineitem_tax'),
        ('pricing', '0030_remove_lineitemtype_taxes_lineitemtype_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxes',
        ),
    ]
