# Generated by Django 5.0.8 on 2024-12-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0127_remove_contract_price_rate_and_more'),
        ('pricing', '0031_delete_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('add', 'Suma'), ('dec', 'Resta'), ('ptg', 'Percentatge')], default='ptg')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('consum_real', 'Consum Real'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Futa')], default='consum_real')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='custom_interval_percentage',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='fixed_interval',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='price_interval',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='proportional_price',
        ),
        migrations.AddField(
            model_name='adjustment',
            name='variable_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='contract.variabletype'),
        ),
        migrations.CreateModel(
            name='AdjustmentInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('price_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.priceinterval')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='adjustment_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.adjustmentinterval'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.adjustmentoperation'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='variable_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.variablecalculation'),
        ),
    ]
