# Generated by Django 5.0.8 on 2024-12-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0127_remove_contract_price_rate_and_more'),
        ('pricing', '0032_adjustmentoperation_variablecalculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='bonification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='contract.bonification'),
        ),
        migrations.AlterField(
            model_name='adjustmentoperation',
            name='token',
            field=models.CharField(choices=[('min', 'Minim'), ('max', 'Màxim'), ('ptg', 'Percentatge'), ('addInt', 'Suma Interval')], default='ptg'),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_type', to='pricing.variablecalculation'),
        ),
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('consum_real', 'Consum Real'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita')], default='consum_real'),
        ),
    ]
