# Generated by Django 5.0.8 on 2024-12-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_adjustment_bonification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='line_item_type',
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='adjustments',
            field=models.ManyToManyField(blank=True, related_name='line_item_type', to='pricing.adjustment'),
        ),
    ]
