# Generated by Django 5.0.8 on 2024-12-17 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_remove_adjustment_line_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentinterval',
            name='price_interval',
        ),
        migrations.AddField(
            model_name='adjustmentinterval',
            name='price_interval_stretch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.priceintervalstretch'),
        ),
    ]
