# Generated by Django 5.0.8 on 2024-12-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0127_remove_contract_price_rate_and_more'),
        ('pricing', '0035_remove_adjustmentinterval_price_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='bonification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='contract.bonificationtype'),
        ),
    ]
