# Generated by Django 5.0.8 on 2024-12-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0036_alter_adjustment_bonification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtype',
            name='billing_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_types', to='pricing.billingrange'),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='price_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_types', to='pricing.priceinterval'),
        ),
    ]
