# Generated by Django 5.0.8 on 2024-12-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0037_alter_lineitemtype_billing_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='bonification',
        ),
    ]
