# Generated by Django 5.0.8 on 2024-12-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0038_remove_adjustment_bonification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableFixedPriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('demographic_coefficient', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='variable_fixed_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_types', to='pricing.variablefixedpriceinterval'),
        ),
        migrations.CreateModel(
            name='VariableFixedPriceIntervalStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('proporcional_price', models.FloatField(blank=True, null=True)),
                ('stretch', models.IntegerField(blank=True, null=True)),
                ('end_stretch', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variable_fixed_price_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_fixed_price_interval_stretches', to='pricing.variablefixedpriceinterval')),
            ],
        ),
    ]
