# Generated by Django 5.0.8 on 2024-12-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0039_variablefixedpriceinterval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablefixedpriceintervalstretch',
            name='proporcional_price',
        ),
    ]
