# Generated by Django 5.0.8 on 2024-12-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0040_remove_variablefixedpriceintervalstretch_proporcional_price'),
        ('service', '0052_cluster_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinterval',
            name='demographic_coefficient',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='exploitation',
        ),
        migrations.RemoveField(
            model_name='variablefixedpriceinterval',
            name='demographic_coefficient',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='service.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='service.exploitation'),
        ),
    ]
