# Generated by Django 5.0.8 on 2024-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0041_remove_priceinterval_demographic_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('consum', 'Consum'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita')], default='consum'),
        ),
    ]
