# Generated by Django 5.0.8 on 2024-12-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0042_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(choices=[('aigua', 'Aigua'), ('contracte', 'Contracte'), ('lectura', 'Lectura'), ('altres', 'Altres')], default='aigua')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pricing.productorigin'),
        ),
    ]
