# Generated by Django 5.0.8 on 2024-12-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0043_productorigin_alter_product_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='percentage',
            new_name='percent',
        ),
    ]
