# Generated by Django 5.0.8 on 2024-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0044_rename_percentage_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
