# Generated by Django 5.0.8 on 2024-12-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0045_alter_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtype',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_types', to='pricing.variablecalculation'),
        ),
    ]
