# Generated by Django 5.0.8 on 2024-12-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0046_alter_lineitemtype_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemtype',
            old_name='variable_fixed_price',
            new_name='price_variable',
        ),
        migrations.AddField(
            model_name='priceintervalstretch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RenameModel(
            old_name='VariableFixedPriceInterval',
            new_name='PriceVariableInterval',
        ),
        migrations.CreateModel(
            name='PriceVariableIntervalStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('proportional_price', models.FloatField(blank=True, null=True)),
                ('stretch', models.IntegerField(blank=True, null=True)),
                ('end_stretch', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_variable_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_variable_interval_stretches', to='pricing.pricevariableinterval')),
            ],
        ),
        migrations.DeleteModel(
            name='VariableFixedPriceIntervalStretch',
        ),
    ]
