# Generated by Django 5.0.8 on 2024-12-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0047_rename_variable_fixed_price_lineitemtype_price_variable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceintervalstretch',
            old_name='name',
            new_name='name_stretch',
        ),
        migrations.RenameField(
            model_name='pricevariableintervalstretch',
            old_name='name',
            new_name='name_stretch',
        ),
    ]
