# Generated by Django 5.0.8 on 2024-12-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0048_rename_name_priceintervalstretch_name_stretch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemtype',
            name='adjustments',
        ),
        migrations.AddField(
            model_name='adjustment',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.lineitemtype'),
        ),
        migrations.AddField(
            model_name='adjustmentinterval',
            name='price_variable_stretch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.pricevariableintervalstretch'),
        ),
    ]
