# Generated by Django 5.0.8 on 2024-12-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0049_remove_lineitemtype_adjustments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceintervalstretch',
            name='units',
        ),
        migrations.AddField(
            model_name='priceinterval',
            name='units',
            field=models.CharField(choices=[('m3', 'm3'), ('dm', 'diametre')], default='m3'),
        ),
    ]
