# Generated by Django 5.0.8 on 2024-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0050_remove_priceintervalstretch_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricevariableinterval',
            name='units',
            field=models.CharField(choices=[('m3', 'm3'), ('dm', 'diametre')], default='m3'),
        ),
    ]
