# Generated by Django 5.0.8 on 2024-12-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0051_pricevariableinterval_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdjustmentInterval',
            new_name='AdjustmentIntervalStretch',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='adjustment_interval',
            new_name='adjustment_interval_stretch',
        ),
    ]
