# Generated by Django 5.0.8 on 2024-12-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0052_rename_adjustmentinterval_adjustmentintervalstretch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='variable_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='pricing.variablecalculation'),
        ),
    ]
