# Generated by Django 5.0.8 on 2024-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0053_adjustment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='proration',
            field=models.BooleanField(default=False),
        ),
    ]
