# Generated by Django 5.0.8 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0054_lineitemtype_proration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiod',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
