# Generated by Django 5.0.8 on 2024-12-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0055_billingperiod_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemtype',
            old_name='proration',
            new_name='is_prorated',
        ),
    ]
