# Generated by Django 5.0.8 on 2024-12-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0056_rename_proration_lineitemtype_is_prorated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='adjustment_interval_stretch',
        ),
        migrations.AddField(
            model_name='adjustmentintervalstretch',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.adjustment'),
        ),
    ]
