# Generated by Django 5.0.8 on 2024-12-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0057_remove_adjustment_adjustment_interval_stretch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemtype',
            old_name='proporcional_price',
            new_name='proportional_price',
        ),
        migrations.RenameField(
            model_name='priceintervalstretch',
            old_name='proporcional_price',
            new_name='proportional_price',
        ),
        migrations.AlterField(
            model_name='adjustmentintervalstretch',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_interval_stretches', to='pricing.adjustment'),
        ),
    ]
