# Generated by Django 5.0.8 on 2025-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0058_rename_proporcional_price_lineitemtype_proportional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
