# Generated by Django 5.0.8 on 2025-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0059_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentoperation',
            name='token',
            field=models.CharField(choices=[('min', 'Minim'), ('max', 'Màxim'), ('ptg', 'Percentatge'), ('ext', 'Ampliació de Tram')], default='ptg'),
        ),
    ]
