# Generated by Django 5.0.8 on 2025-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0060_alter_adjustmentoperation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
