# Generated by Django 5.0.8 on 2025-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0061_adjustment_end_at_adjustment_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinterval',
            name='units',
            field=models.CharField(choices=[('m3', 'm3'), ('dm_met', 'diametre_met'), ('dm_con', 'diametre_conn')], default='m3'),
        ),
    ]
