# Generated by Django 5.0.8 on 2025-01-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0062_alter_priceinterval_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='pricing.adjustment')),
            ],
        ),
    ]
