# Generated by Django 5.0.8 on 2025-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0063_adjustmentcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentcondition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
