# Generated by Django 5.0.8 on 2025-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0064_adjustmentcondition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentcondition',
            name='operation',
            field=models.CharField(choices=[('eq', 'Equal'), ('ne', 'Not Equal'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('ge', 'Greater or Equal'), ('le', 'Less or Equal'), ('in', 'In'), ('ni', 'Not In'), ('is_true', 'Is True'), ('is_false', 'Is False'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], default='eq'),
        ),
        migrations.AddField(
            model_name='adjustmentcondition',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
