# Generated by Django 5.0.8 on 2025-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0065_adjustmentcondition_operation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjustmentcondition',
            old_name='quantity',
            new_name='quantity_key',
        ),
        migrations.AddField(
            model_name='adjustmentcondition',
            name='quantity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
