# Generated by Django 5.0.8 on 2025-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0066_rename_quantity_adjustmentcondition_quantity_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentcondition',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
