# Generated by Django 5.0.8 on 2025-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0067_adjustmentcondition_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentcondition',
            name='quantity_key',
        ),
        migrations.RemoveField(
            model_name='adjustmentcondition',
            name='quantity_name',
        ),
        migrations.AddField(
            model_name='adjustmentcondition',
            name='quantity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
