# Generated by Django 5.0.8 on 2025-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0068_remove_adjustmentcondition_quantity_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='variable_contract',
        ),
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita')], default='consum'),
        ),
    ]
