# Generated by Django 5.0.8 on 2025-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0069_remove_adjustment_variable_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentintervalstretch',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
