# Generated by Django 5.0.8 on 2025-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0070_adjustmentintervalstretch_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='preference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
