# Generated by Django 5.0.8 on 2025-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0071_adjustment_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
