# Generated by Django 5.0.8 on 2025-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0072_adjustment_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='formula',
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
