# Generated by Django 5.0.8 on 2025-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0073_remove_adjustment_formula_lineitemtype_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricevariableinterval',
            name='units',
            field=models.CharField(choices=[('m3', 'm3'), ('dm_met', 'diametre_met'), ('dm_con', 'diametre_conn')], default='m3'),
        ),
    ]
