# Generated by Django 5.0.8 on 2025-02-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0074_alter_pricevariableinterval_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjustment',
            old_name='preference',
            new_name='position',
        ),
    ]
