# Generated by Django 5.0.8 on 2025-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0075_rename_preference_adjustment_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorigin',
            name='token',
            field=models.CharField(choices=[('aigua', 'Aigua'), ('contracte', 'Contracte'), ('altres', 'Altres'), ('escomesa', 'Escomesa'), ('subministrament', 'Subministrament')], default='aigua'),
        ),
    ]
