# Generated by Django 5.0.8 on 2025-03-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0076_alter_productorigin_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='price',
        ),
    ]
