# Generated by Django 5.0.8 on 2025-07-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0077_remove_pricerate_calculation_remove_pricerate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='active_choice',
            field=models.CharField(blank=True, choices=[('DAYS', 'Correcció per dies'), ('MONTHS', 'Correcció per mesos'), ('NOADJ', 'Sense correcció')], default='NOADJ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='deactive_choice',
            field=models.CharField(blank=True, choices=[('DAYS', 'Correcció per dies'), ('MONTHS', 'Correcció per mesos'), ('NOADJ', 'Sense correcció')], default='NOADJ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='billing_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='billing_deactive',
            field=models.BooleanField(default=True),
        ),
    ]
