# Generated by Django 5.0.8 on 2025-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0078_lineitemtype_active_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemtype',
            old_name='deactive_choice',
            new_name='inactive_choice',
        ),
        migrations.RenameField(
            model_name='pricerate',
            old_name='billing_deactive',
            new_name='billing_inactive',
        ),
    ]
