# Generated by Django 5.0.8 on 2025-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0079_rename_deactive_choice_lineitemtype_inactive_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='billing_active',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='billing_inactive',
        ),
        migrations.AddField(
            model_name='product',
            name='billing_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='billing_inactive',
            field=models.BooleanField(default=True),
        ),
    ]
