# Generated by Django 5.0.8 on 2025-07-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0080_remove_pricerate_billing_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRangeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('has_billed', models.BooleanField(default=False)),
                ('billing_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_range_changes', to='pricing.billingrange')),
            ],
        ),
        migrations.AddField(
            model_name='pricerate',
            name='prev_billing_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rates', to='pricing.billingrangechange'),
        ),
    ]
