# Generated by Django 5.0.8 on 2025-07-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0081_billingrangechange_pricerate_prev_billing_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='prev_billing_range',
        ),
        migrations.DeleteModel(
            name='BillingRangeChange',
        ),
    ]
