# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0082_remove_pricerate_prev_billing_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerate',
            options={'verbose_name': 'Price Rate', 'verbose_name_plural': 'Price Rates'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
