# Generated by Django 5.0.8 on 2025-08-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0190_contractterminationrequest_termination_file'),
        ('pricing', '0084_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='variable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='contract.variabletype'),
        ),
        migrations.AlterField(
            model_name='adjustmentoperation',
            name='token',
            field=models.CharField(choices=[('min', 'Minim'), ('max', 'Màxim'), ('ptg', 'Percentatge'), ('ext', 'Ampliació de Tram'), ('var', 'Variable')], default='ptg'),
        ),
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita'), ('price', 'Preu')], default='consum'),
        ),
    ]
