# Generated by Django 5.0.8 on 2025-09-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0085_adjustment_variable_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita'), ('total_persons', 'Total de Personas')], default='consum'),
        ),
    ]
