# Generated by Django 5.0.8 on 2025-09-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0086_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita')], default='consum'),
        ),
    ]
