# Generated by Django 5.0.8 on 2025-09-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0087_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='pricing.lineitemtype'),
        ),
    ]
