# Generated by Django 5.0.8 on 2025-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0088_alter_adjustment_line_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='is_bail',
            field=models.BooleanField(default=False),
        ),
    ]
