# Generated by Django 5.0.8 on 2025-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0089_lineitemtype_is_bail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemtype',
            name='is_bail',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='is_bail',
            field=models.BooleanField(default=False),
        ),
    ]
