# Generated by Django 5.0.8 on 2025-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0090_remove_lineitemtype_is_bail_pricerate_is_bail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
