# Generated by Django 5.0.8 on 2025-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0092_articlecode_lineitemtype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
