# Generated by Django 5.0.8 on 2025-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0093_adjustment_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='always_show',
            field=models.BooleanField(default=True),
        ),
    ]
