# Generated by Django 5.0.8 on 2026-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0094_lineitemtype_always_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('prev_consum', 'Consum Anterior'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita')], default='consum'),
        ),
    ]
