# Generated by Django 5.0.8 on 2026-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0095_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
