# Generated by Django 5.0.8 on 2026-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0099_create_variablecalculation_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecalculation',
            name='token',
            field=models.CharField(choices=[('price', 'Preu'), ('consum', 'Consum'), ('prev_consum', 'Consum Anterior'), ('dies_consum', 'Dies Consum'), ('diferencia_fuita', 'Diferencia de Fuita'), ('diferencia_fuita_consum', 'Diferencia de Fuita i Consum'), ('units', 'Unitats')], default='consum'),
        ),
    ]
