# Generated by Django 5.0.8 on 2026-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0100_alter_variablecalculation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='name_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='name_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='name_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
