# Generated by Django 5.0.8 on 2026-07-29 11:51

import django.db.models.deletion
from django.db import migrations, models


def copy_name_translations_to_i18n_tables(apps, schema_editor):
    model_map = [
        ('Product', 'ProductI18n', 'product'),
        ('PriceRate', 'PriceRateI18n', 'price_rate'),
        ('LineItemType', 'LineItemTypeI18n', 'line_item_type'),
    ]
    for source_model_name, i18n_model_name, fk_name in model_map:
        SourceModel = apps.get_model('pricing', source_model_name)
        I18nModel = apps.get_model('pricing', i18n_model_name)
        rows = []
        for instance in SourceModel.objects.exclude(name_translations={}).only('id', 'name_translations'):
            for language, name in (instance.name_translations or {}).items():
                if name:
                    rows.append(I18nModel(**{fk_name + '_id': instance.id, 'language': language, 'name': name}))
        if rows:
            I18nModel.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0101_add_name_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemTypeI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('line_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.lineitemtype')),
            ],
            options={
                'unique_together': {('line_item_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PriceIntervalStretchI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2)),
                ('name_stretch', models.CharField(max_length=255)),
                ('price_interval_stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.priceintervalstretch')),
            ],
            options={
                'unique_together': {('price_interval_stretch', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PriceRateI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('price_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.pricerate')),
            ],
            options={
                'unique_together': {('price_rate', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ProductI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.product')),
            ],
            options={
                'unique_together': {('product', 'language')},
            },
        ),
        migrations.RunPython(copy_name_translations_to_i18n_tables, noop_reverse),
        migrations.RemoveField(
            model_name='lineitemtype',
            name='name_translations',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='name_translations',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_translations',
        ),
    ]
