# Generated by Django 5.0.8 on 2026-09-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0103_accountingaccount_accountingcenter_accountingconcept_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountingCenter',
            new_name='AccountingType',
        ),
        migrations.RemoveField(
            model_name='accountingpricing',
            name='accounting_account',
        ),
        migrations.RemoveField(
            model_name='accountingpricing',
            name='accounting_provider',
        ),
        migrations.RemoveField(
            model_name='accountingpricing',
            name='accounting_center',
        ),
        migrations.RemoveField(
            model_name='accountingpricing',
            name='accounting_concept',
        ),
        migrations.AddField(
            model_name='accountingconcept',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_concepts', to='pricing.accountingtype'),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='accounting_concepts',
            field=models.ManyToManyField(related_name='accounting_pricings', to='pricing.accountingconcept'),
        ),
        migrations.DeleteModel(
            name='AccountingAccount',
        ),
        migrations.DeleteModel(
            name='AccountingProvider',
        ),
    ]
