# Generated by Django 5.0.8 on 2026-09-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0105_accountingpricing_exploitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingconcept',
            old_name='code',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='accountingpricing',
            old_name='code',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='accountingtype',
            old_name='code',
            new_name='token',
        ),
    ]
