# Generated by Django 5.0.8 on 2026-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0106_rename_code_accountingconcept_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtype',
            name='add_subtotals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingtype',
            name='add_taxes',
            field=models.BooleanField(default=False),
        ),
    ]
