# Generated by Django 5.0.8 on 2026-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0107_accountingtype_add_subtotals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpricing',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
