# Generated by Django 5.0.8 on 2026-09-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0108_accountingpricing_is_default'),
        ('service', '0120_supplycut_exec_dates_and_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingpricing',
            name='accounting_concepts',
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='accounting_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_pricings', to='pricing.accountingconcept'),
        ),
        migrations.AlterField(
            model_name='accountingpricing',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_pricings', to='service.company'),
        ),
        migrations.AlterField(
            model_name='accountingpricing',
            name='exploitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_pricings', to='service.exploitation'),
        ),
    ]
