# Generated by Django 5.0.8 on 2026-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0109_remove_accountingpricing_accounting_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('lineitem', 'Line Item'), ('invoice', 'Invoice'), ('payment', 'Payment')], default='invoice'),
        ),
    ]
