# Generated by Django 5.0.8 on 2026-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0131_personlog'),
        ('pricing', '0110_accountingconcept_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpricing',
            name='banks',
            field=models.ManyToManyField(related_name='accounting_pricings', to='coredata.bank'),
        ),
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('payment', 'Payment'), ('lineitem', 'Line Item'), ('invoice', 'Invoice')], default='invoice'),
        ),
    ]
