# Generated by Django 5.0.8 on 2026-09-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0107_pricerate_is_return_fee'),
        ('pricing', '0111_accountingpricing_banks_and_more'),
    ]

    operations = [
    ]
