# Generated by Django 5.0.8 on 2026-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0112_merge_20260922_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpricing',
            name='foreign_iban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='return_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('lineitem', 'Line Item'), ('payment', 'Payment'), ('invoice', 'Invoice')], default='invoice'),
        ),
    ]
