# Generated by Django 5.0.8 on 2026-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0113_accountingpricing_foreign_iban_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingpricing',
            old_name='return_payments',
            new_name='incoming_payments',
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='native_iban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='outgoing_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('payment', 'Payment'), ('invoice', 'Invoice'), ('lineitem', 'Line Item')], default='invoice'),
        ),
    ]
