# Generated by Django 5.0.8 on 2026-10-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0114_rename_return_payments_accountingpricing_incoming_payments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='declared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='grouped_lines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='origins',
            field=models.ManyToManyField(related_name='accounting_pricings', to='pricing.productorigin'),
        ),
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('lineitem', 'Line Item'), ('payment', 'Payment'), ('invoice', 'Invoice')], default='invoice'),
        ),
        migrations.AddField(
            model_name='accountingpricing',
            name='accounting_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_pricings', to='pricing.accountingcostcenter'),
        ),
    ]
