# Generated by Django 5.0.8 on 2026-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0115_accountingcostcenter_accountingpricing_declared_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpricing',
            name='undeclare_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('lineitem', 'Line Item')], default='invoice'),
        ),
    ]
