# Generated by Django 5.0.8 on 2026-10-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0116_accountingpricing_undeclare_previous_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingpricing',
            old_name='declared_by',
            new_name='invoice_category',
        ),
    ]
