# Generated by Django 5.0.8 on 2026-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0117_rename_declared_by_accountingpricing_invoice_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingpricing',
            old_name='native_iban',
            new_name='national_iban',
        ),
    ]
