# Generated by Django 5.0.8 on 2026-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0118_rename_native_iban_accountingpricing_national_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingconcept',
            name='category',
            field=models.CharField(choices=[('lineitem', 'Line Item'), ('payment', 'Payment'), ('invoice', 'Invoice')], default='invoice'),
        ),
    ]
