# Generated by Django 5.0.4 on 2024-07-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='token',
            field=models.CharField(default='082080', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.country'),
        ),
    ]
