# Generated by Django 5.0.8 on 2024-10-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_city_token_province_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonContact',
        ),
    ]
