# Generated by Django 5.0.8 on 2024-10-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_cnae_paymenttype_personcnae_personpayment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaddress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='personcontact',
            unique_together={('person', 'is_default')},
        ),
        migrations.AddField(
            model_name='personaddress',
            name='attention_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='is_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='contact_type',
        ),
    ]
