# Generated by Django 5.0.8 on 2024-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_alter_personaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaddress',
            unique_together={('person', 'is_billing')},
        ),
    ]
