# Generated by Django 5.0.8 on 2024-10-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0006_alter_personaddress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coredata.address'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='coredata.person'),
        ),
    ]
