# Generated by Django 5.0.8 on 2024-10-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0007_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streetnumbertype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='streetnumbertype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='streettype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='streettype',
            name='updated_at',
        ),
    ]
