# Generated by Django 5.0.8 on 2024-10-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0007_address_created_at_address_updated_at_and_more'),
        ('coredata', '0007_alter_personaddress_address_and_more'),
    ]

    operations = [
    ]
