# Generated by Django 5.0.8 on 2024-10-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0008_merge_20241003_1415'),
        ('coredata', '0008_remove_streetnumbertype_created_at_and_more'),
    ]

    operations = [
    ]
