# Generated by Django 5.0.8 on 2024-10-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0009_merge_20241003_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaddress',
            unique_together=set(),
        ),
    ]
