# Generated by Django 5.0.8 on 2024-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0010_alter_personaddress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personcontact',
            unique_together=set(),
        ),
    ]
