# Generated by Django 5.0.8 on 2024-10-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0011_alter_personcontact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='coredata.person'),
        ),
    ]
