# Generated by Django 5.0.8 on 2024-10-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0012_alter_personcontact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='personpayment',
            name='person',
        ),
        migrations.CreateModel(
            name='PersonBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('iban_country', models.CharField(blank=True, max_length=2, null=True)),
                ('iban_country_control', models.CharField(blank=True, max_length=2, null=True)),
                ('iban_entity', models.CharField(blank=True, max_length=4, null=True)),
                ('iban_agency', models.CharField(blank=True, max_length=4, null=True)),
                ('iban_dc', models.CharField(blank=True, max_length=2, null=True)),
                ('iban_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coredata.person')),
            ],
        ),
    ]
