# Generated by Django 5.0.8 on 2024-10-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_contractpayment_person_bank_alter_contract_payment_and_more'),
        ('coredata', '0013_remove_personpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonPayment',
        ),
    ]
