# Generated by Django 5.0.8 on 2024-10-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0014_delete_personpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
