# Generated by Django 5.0.8 on 2024-10-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0015_delete_paymenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbank',
            name='bank',
        ),
    ]
