# Generated by Django 5.0.8 on 2024-10-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0016_remove_personbank_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personbank',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='coredata.person'),
        ),
    ]
