# Generated by Django 5.0.8 on 2024-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0017_personbank_is_default_alter_personbank_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnae',
            name='codi',
        ),
    ]
