# Generated by Django 5.0.8 on 2024-10-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0018_remove_cnae_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcnae',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnaes', to='coredata.person'),
        ),
    ]
