# Generated by Django 5.0.8 on 2024-10-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0019_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='coredata.bank'),
        ),
    ]
