# Generated by Django 5.0.8 on 2024-10-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0019_alter_personcnae_person'),
        ('coredata', '0021_alter_bank_active'),
    ]

    operations = [
    ]
