# Generated by Django 5.0.8 on 2024-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='dni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personbank',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
