# Generated by Django 5.0.8 on 2024-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0023_personbank_dni_personbank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='has_iban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='in_europe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='is_sepa',
            field=models.BooleanField(default=False),
        ),
    ]
