# Generated by Django 5.0.8 on 2024-10-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_country_has_iban_country_in_europe_country_is_sepa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='coredata.country'),
        ),
        migrations.AddField(
            model_name='personbank',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
