# Generated by Django 5.0.8 on 2024-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0025_personbank_country_personbank_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
