# Generated by Django 5.0.8 on 2024-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0026_personbank_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbank',
            name='iban_agency',
        ),
        migrations.RemoveField(
            model_name='personbank',
            name='iban_country',
        ),
        migrations.RemoveField(
            model_name='personbank',
            name='iban_country_control',
        ),
        migrations.RemoveField(
            model_name='personbank',
            name='iban_dc',
        ),
        migrations.RemoveField(
            model_name='personbank',
            name='iban_entity',
        ),
        migrations.RemoveField(
            model_name='personbank',
            name='iban_number',
        ),
        migrations.AddField(
            model_name='personbank',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
