# Generated by Django 5.0.8 on 2024-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0027_remove_personbank_iban_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
