# Generated by Django 5.0.8 on 2024-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0028_alter_country_created_at_alter_country_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='swift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
