# Generated by Django 5.0.8 on 2024-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0029_personbank_swift'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
