# Generated by Django 5.0.8 on 2024-10-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0030_country_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=2),
        ),
    ]
