# Generated by Django 5.0.8 on 2024-10-31 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0031_alter_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.address'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='coredata.person'),
        ),
    ]
