# Generated by Django 5.0.8 on 2024-11-05 09:14

import coredata.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0032_alter_personaddress_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBankSepaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True)),
                ('person_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepa_documents', to='coredata.personbank')),
            ],
        ),
    ]
