# Generated by Django 5.0.8 on 2024-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0033_personbanksepadocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbanksepadocument',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
