# Generated by Django 5.0.8 on 2024-11-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0034_personbanksepadocument_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='person_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepa_document', to='coredata.personbank'),
        ),
    ]
