# Generated by Django 5.0.8 on 2024-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0035_alter_personbanksepadocument_person_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
