# Generated by Django 5.0.8 on 2024-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0036_alter_personbanksepadocument_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='province',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
