# Generated by Django 5.0.8 on 2024-11-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0037_city_is_default_province_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbanksepadocument',
            name='person_bank',
        ),
        migrations.AddField(
            model_name='personbank',
            name='sepa_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbanksepadocument'),
        ),
    ]
