# Generated by Django 5.0.8 on 2024-11-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0038_remove_personbanksepadocument_person_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbank',
            name='sepa_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='coredata.personbanksepadocument'),
        ),
    ]
