# Generated by Django 5.0.8 on 2024-11-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0039_alter_personbank_sepa_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbank',
            name='sepa_document',
        ),
        migrations.AddField(
            model_name='personbanksepadocument',
            name='person_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepa_documents', to='coredata.personbank'),
        ),
    ]
