# Generated by Django 5.0.8 on 2024-11-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0040_remove_personbank_sepa_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbank',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_banks', to='coredata.bank'),
        ),
    ]
