# Generated by Django 5.0.8 on 2024-11-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0041_alter_personbank_bank'),
        ('coredata', '0041_personbanksepadocument_template_and_more'),
    ]

    operations = [
    ]
