# Generated by Django 5.0.8 on 2024-11-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0042_merge_20241121_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='person_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepa_document', to='coredata.personbank'),
        ),
    ]
