# Generated by Django 5.0.8 on 2024-11-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0043_alter_personbanksepadocument_person_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='person_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coredata.personbank'),
        ),
    ]
