# Generated by Django 5.0.8 on 2024-11-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0044_alter_personbanksepadocument_person_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='sepa_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_person_bank', to='coredata.personbanksepadocument'),
        ),
    ]
