# Generated by Django 5.0.8 on 2024-11-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0045_personbank_sepa_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbank',
            name='sepa_document',
        ),
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='person_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepa_document', to='coredata.personbank'),
        ),
    ]
