# Generated by Django 5.0.8 on 2025-01-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
        ('documentmanager', '0004_rename_entity_name_document_folder_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbanksepadocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document'),
        ),
    ]
