# Generated by Django 5.0.8 on 2025-01-30 14:28

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0047_alter_personbanksepadocument_file'),
    ]

    operations = [
        UnaccentExtension()
    ]
