# Generated by Django 5.0.8 on 2025-01-30 14:46

from django.db import migrations

def enable_pg_trgm(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0048_auto_20250130_1428'),
    ]

    operations = [
    ]
