# Generated by Django 5.0.8 on 2025-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0049_auto_20250130_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetnumber',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
