# Generated by Django 5.0.8 on 2025-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0049_auto_20250130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=3),
        ),
    ]
