# Generated by Django 5.0.8 on 2025-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0050_streetnumber_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
