# Generated by Django 5.0.8 on 2025-03-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0050_alter_country_iso_code'),
        ('coredata', '0053_personaddress_token'),
    ]

    operations = [
    ]
