# Generated by Django 5.0.8 on 2025-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0054_merge_20250310_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='person',
            name='is_debtor',
            field=models.BooleanField(default=False),
        ),
    ]
