# Generated by Django 5.0.8 on 2025-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0054_merge_20250310_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
