# Generated by Django 5.0.8 on 2025-03-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0055_person_debt_amount_person_is_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_debt_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
