# Generated by Django 5.0.8 on 2025-03-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0056_person_last_debt_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDeliquency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_debtor', models.BooleanField(default=False)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_debt_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='debt_amount',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_debtor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_debt_data',
        ),
        migrations.AddField(
            model_name='person',
            name='deliquency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='coredata.persondeliquency'),
        ),
    ]
