# Generated by Django 5.0.8 on 2025-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0055_province_token'),
        ('coredata', '0056_person_last_debt_data'),
    ]

    operations = [
    ]
