# Generated by Django 5.0.8 on 2025-03-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0057_persondeliquency_remove_person_debt_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deliquency',
        ),
        migrations.AddField(
            model_name='persondeliquency',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliquency', to='coredata.person'),
        ),
    ]
