# Generated by Django 5.0.8 on 2025-03-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0057_merge_0055_province_token_0056_person_last_debt_data'),
        ('coredata', '0058_remove_person_deliquency_persondeliquency_person'),
    ]

    operations = [
    ]
