# Generated by Django 5.0.8 on 2025-03-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0059_merge_20250319_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondeliquency',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='deliquency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='coredata.persondeliquency'),
        ),
    ]
