# Generated by Django 5.0.8 on 2025-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0060_remove_persondeliquency_person_person_deliquency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
