# Generated by Django 5.0.8 on 2025-04-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0140_remove_commitmentdeposit_holder'),
        ('coredata', '0061_alter_city_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='commitment_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='billing.commitmentdeposit'),
        ),
    ]
