# Generated by Django 5.0.8 on 2025-04-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0062_person_commitment_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='commitment_deposit',
        ),
    ]
