# Generated by Django 5.0.8 on 2025-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0063_remove_person_commitment_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
