# Generated by Django 5.0.8 on 2025-05-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0065_person_vulnerability_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_vulnerable',
        ),
    ]
