# Generated by Django 5.0.8 on 2025-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0066_remove_person_is_vulnerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetnumber',
            name='number_end_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
