# Generated by Django 5.0.8 on 2025-06-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0068_personobservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonBankSepaDocument',
        ),
    ]
