# Generated by Django 5.0.8 on 2025-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0069_delete_personbanksepadocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='door',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='stair',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='streetnumber',
            name='number_end_suffix',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='streetnumber',
            name='number_suffix',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='streettype',
            name='abbreviation',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
