# Generated by Django 5.0.8 on 2025-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0070_alter_address_door_alter_address_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcontact',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
