# Generated by Django 5.0.8 on 2025-08-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0071_add_token_to_personcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('view_key', models.CharField(max_length=255)),
                ('change_key', models.CharField(max_length=255)),
                ('affected_models', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
