# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0072_mainpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='mainpermission',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
