# Generated by Django 5.0.8 on 2025-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0073_alter_person_options_mainpermission_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpermission',
            name='all_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
