# Generated by Django 5.0.8 on 2025-09-04 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0075_callregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callregister',
            name='person',
        ),
        migrations.AddField(
            model_name='callregister',
            name='person_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_registers', to='coredata.personcontact'),
        ),
    ]
