# Generated by Django 5.0.8 on 2025-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0076_remove_callregister_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbank',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
