# Generated by Django 5.0.8 on 2025-09-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0077_personbank_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streettype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
