# Generated by Django 5.0.8 on 2025-12-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0080_identificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='coredata.identificationtype'),
        ),
    ]
