# Generated by Django 5.0.8 on 2025-12-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0080_create_audit_triggers'),
        ('coredata', '0080_identificationtype'),
    ]

    operations = [
    ]
