# Generated by Django 5.0.8 on 2025-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0081_person_identification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtype',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
