# Generated by Django 5.0.8 on 2025-12-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0081_merge_20251201_1241'),
        ('coredata', '0082_identificationtype_position'),
    ]

    operations = [
    ]
