# Generated by Django 5.0.8 on 2026-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0083_merge_20251202_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='streettype',
            name='aca_abbreviation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
