# Generated by Django 5.0.8 on 2026-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0084_streettype_aca_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
