# Generated by Django 5.0.8 on 2026-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0086_returnreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
