# Generated by Django 5.0.8 on 2026-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0090_add_reference_suffix_barcode_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
