# Generated by Django 5.0.8 on 2026-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0091_alter_personcontact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='attention_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
