# Generated by Django 5.0.8 on 2026-04-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0093_add_stats_deviation_configs'),
        ('coredata', '0093_street_city'),
    ]

    operations = [
    ]
