# Generated by step execution
from django.db import migrations

def add_configs(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    # Use apps.get_model safely
    try:
        ContractUseType = apps.get_model('contract', 'ContractUseType')
        inc_type = ContractUseType.objects.filter(token='inc').first()
        if not inc_type:
            inc_type = ContractUseType.objects.filter(name__icontains='Incendis').first()
        val = str(inc_type.id) if inc_type else ""
    except (LookupError, AttributeError):
        val = ""

    ConfigProject.objects.get_or_create(
        token='fire_usage_type_token',
        defaults={
            'name': 'Token Tipus d\'ús Incendis',
            'value': 'inc'
        }
    )
    
    ConfigProject.objects.get_or_create(
        token='reading_estimation_default_days',
        defaults={
            'name': 'Dies per defecte estimació lectures',
            'value': '90'
        }
    )

def remove_configs(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    ConfigProject.objects.filter(token__in=['fire_usage_type_token', 'reading_estimation_default_days']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0094_merge_20260423_1410'),
        ('contract', '0001_initial'), # Ensure contract models are available
    ]

    operations = [
        migrations.RunPython(add_configs, remove_configs),
    ]
