# Generated by Django 5.0.8 on 2026-04-20 11:54

import django.db.models.deletion
from django.db import migrations, models

   
class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0096_personpiggybank_person_piggy_bank_and_more'),
    ]

    operations = [
    ]
