# Generated by Django 5.0.8 on 2026-05-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0097_add_clavegueram_product_config'),
        ('coredata', '0097_add_piggy_bank_to_persons'),
    ]

    operations = [
    ]
