# Generated by Django 5.0.8 on 2026-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0100_add_use_multiple_companies_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
