# Generated by Django 5.0.8 on 2026-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0102_add_comm_process_new_config'),
        ('coredata', '0105_create_administrador_group'),
    ]

    operations = [
    ]
