# Generated by Django 5.0.8 on 2026-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0106_merge_20260602_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='e_record',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
