# Generated by Django 5.0.8 on 2026-06-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0107_person_e_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='e_record',
        ),
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('e_record', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='coredata.person')),
            ],
        ),
    ]
