# Generated by Django 5.0.8 on 2026-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0108_remove_person_e_record_personrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
