# Generated by Django 5.0.8 on 2026-06-17 06:57

from django.db import migrations

def add_product_tokens_config(apps, schema_editor):
    ConfigProject = apps.get_model("coredata", "ConfigProject")
    ConfigProject.objects.get_or_create(
        token="product_water_token",
        defaults={
            "name": "Token Producte Aigua",
            "value": "1001",
        },
    )
    ConfigProject.objects.get_or_create(
        token="product_meter_token",
        defaults={
            "name": "Token Producte Cons. Comptador",
            "value": "1003",
        },
    )
    ConfigProject.objects.get_or_create(
        token="product_sewer_token",
        defaults={
            "name": "Token Producte Clavegueram",
            "value": "CLV",
        },
    )


def remove_product_tokens_config(apps, schema_editor):
    ConfigProject = apps.get_model("coredata", "ConfigProject")
    ConfigProject.objects.filter(token="product_water_token").delete()
    ConfigProject.objects.filter(token="product_meter_token").delete()
    ConfigProject.objects.filter(token="product_sewer_token").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0109_personrecord_year'),
    ]

    operations = [
        migrations.RunPython(add_product_tokens_config, remove_product_tokens_config),
    ]
