# Generated by Django 5.0.8 on 2026-06-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0110_add_allow_contract_date_edit_config'),
        ('coredata', '0110_add_product_tokens'),
    ]

    operations = [
    ]
