# Generated by Django 5.0.8 on 2026-06-23 09:06

from django.db import migrations


def add_smart_metering_authentication_token(apps, schema_editor):
    ConfigProject = apps.get_model("coredata", "ConfigProject")
    ConfigProject.objects.get_or_create(
        token="smart_metering_authentication_token",
        defaults={
            "name": "Smart Metering Token",
            "value": None,
        },
    )


def remove_smart_metering_authentication_token(apps, schema_editor):
    ConfigProject = apps.get_model("coredata", "ConfigProject")
    ConfigProject.objects.filter(token="smart_metering_authentication_token").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("coredata", "0111_merge_20260618_1051"),
    ]

    operations = [
        migrations.RunPython(
            add_smart_metering_authentication_token,
            remove_smart_metering_authentication_token,
        ),
    ]

