# Generated by Django 5.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0116_add_contract_token_generation_incremental_enabled_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
