# Generated by Django 5.0.8 on 2026-07-24 10:52

from django.db import migrations

def change_invoice_status_name(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    InvoiceStatus = apps.get_model('billing', 'InvoiceStatus')
    PaymentStatus = apps.get_model('billing', 'PaymentStatus')
    
    try:
        payment_status_token = ConfigProject.objects.get(token='payment_status_cancelled_token').value
        invoice_status_token = ConfigProject.objects.get(token='invoice_status_cancelled_token').value

        payment_status = PaymentStatus.objects.get(token=payment_status_token)
        invoice_status = InvoiceStatus.objects.get(token=invoice_status_token)

        payment_status.name = 'Abonat'
        payment_status.save()
        invoice_status.name = 'Abonada'
        invoice_status.save()
    except Exception as e:
        print(f"ERROR changing status names: {e}")
        return
    

class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0118_add_show_all_consumption_trams_config'),
    ]

    operations = [
        migrations.RunPython(change_invoice_status_name),
    ]
