# Generated by Django 5.0.8 on 2026-07-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0119_change_invoice_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='coredata.person'),
        ),
    ]
