# Generated by Django 5.0.8 on 2026-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0121_add_show_zero_percent_tax_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['app_label', 'name'],
                'unique_together': {('app_label', 'name')},
            },
        ),
    ]
