# Generated by Django 5.0.8 on 2026-08-27 11:44

from django.db import migrations


def add_cancelled_comm_process_config(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    ConfigProject.objects.get_or_create(
        token='communication_process_status_cancelled_token',
        name="Token de estat anul·lat d'un procés de comunicació",
        value='-1',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0129_add_invoice_legacy_concept_order_config'),
    ]

    operations = [
        migrations.RunPython(add_cancelled_comm_process_config),
    ]
