# Generated by Django 5.0.8 on 2026-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0133_add_invoice_return_price_rate_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dni_validated',
            field=models.BooleanField(default=False),
        ),
    ]
