# Generated by Django 5.0.8 on 2025-05-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraud',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
