# Generated by Django 5.0.8 on 2025-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_rename_create_at_fraud_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='detection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
