# Generated by Django 5.0.8 on 2025-05-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0004_remove_fraud_user_remove_frauddocumentation_fraud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraudimage',
            old_name='image',
            new_name='file',
        ),
    ]
