# Generated by Django 5.0.8 on 2025-06-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0005_rename_image_fraudimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
