# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0006_fraud_is_dismissed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraud',
            options={'verbose_name': 'Fraud', 'verbose_name_plural': 'Frauds'},
        ),
    ]
