# Generated by Django 5.0.8 on 2025-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimstep',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
