# Generated by Django 5.0.8 on 2025-04-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0002_claimstep_position'),
        ('order', '0016_merge_20250304_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='previous_step_date',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='previous_step_due_date',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='step',
        ),
        migrations.CreateModel(
            name='ClaimRequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('claim_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='claimrequest.claimrequest')),
            ],
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_claim_requests', to='claimrequest.claimrequeststep'),
        ),
        migrations.CreateModel(
            name='ClaimRequestStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('WORK', 'Hábils'), ('NATURAL', 'Naturals')], default='WORK', max_length=255, null=True)),
                ('action_date_at', models.DateField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimdocumenttype')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimrequeststeptemplate')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordertype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='claimrequest.claimrequesttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='step_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimrequeststeptemplate'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimrequesttemplate'),
        ),
    ]
