# Generated by Django 5.0.8 on 2025-04-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0003_claimrequesttemplate_and_more'),
        ('order', '0016_merge_20250304_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststep',
            name='action_date_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimdocumenttype'),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('WORK', 'Hábils'), ('NATURAL', 'Naturals')], default='WORK', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claimrequest.claimrequeststep'),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordertype'),
        ),
        migrations.AddField(
            model_name='claimrequeststep',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ClaimStep',
        ),
    ]
