# Generated by Django 5.0.8 on 2025-05-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0004_claimrequeststep_action_date_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequeststeptemplate',
            name='action_date_at',
        ),
    ]
