# Generated by Django 5.0.8 on 2025-05-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0012_vulnerabilityrequest_contract_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='check_without_debt',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='client_types',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='debt_managements',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='exploitation',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='use_types',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='zones',
        ),
    ]
