# Generated by Django 5.0.8 on 2025-05-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0013_remove_claimrequest_check_without_debt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequeststep',
            old_name='completed_at',
            new_name='end_step_date',
        ),
    ]
