# Generated by Django 5.0.8 on 2025-05-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0014_rename_completed_at_claimrequeststep_end_step_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequeststep',
            name='end_step_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
