# Generated by Django 5.0.8 on 2025-06-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0016_claimrequest_user'),
        ('communication', '0012_communication_always_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststep',
            name='communication_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationprocess'),
        ),
    ]
