# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0017_claimrequeststep_communication_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'verbose_name': 'Claim Request', 'verbose_name_plural': 'Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilityrequest',
            options={'verbose_name': 'Vulnerability Request', 'verbose_name_plural': 'Vulnerability Requests'},
        ),
    ]
