# Generated by Django 5.0.8 on 2025-10-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0018_alter_claimrequest_options_and_more'),
        ('contract', '0194_merge_20251007_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequestpayment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='contract.contract'),
        ),
    ]
