# Generated by Django 5.0.8 on 2026-06-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0021_rename_duration_type_vulnerabilityrequesttype_duration'),
        ('documentmanager', '0015_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequestStepDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim_request_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claimrequest.claimrequeststep')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_request_step_documents', to='documentmanager.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
