# Generated by Django 5.0.8 on 2026-06-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0022_claimrequeststepdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequeststepdocument',
            old_name='document',
            new_name='file',
        ),
    ]
