# Generated by Django 5.0.8 on 2026-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0023_rename_document_claimrequeststepdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
