# Generated by Django 5.0.8 on 2026-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0024_claimrequest_name'),
        ('pricing', '0102_remove_lineitemtype_name_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststep',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='claim_request_steps', to='pricing.pricerate'),
        ),
    ]
