# Generated by Django 5.0.8 on 2026-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0025_claimrequeststep_price_rates'),
        ('pricing', '0102_remove_lineitemtype_name_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststeptemplate',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='claim_request_step_templates', to='pricing.pricerate'),
        ),
    ]
