# Generated by Django 5.0.8 on 2026-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0026_claimrequeststeptemplate_price_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequestpayment',
            name='is_from_claim',
            field=models.BooleanField(default=False),
        ),
    ]
