# Generated by Django 5.0.8 on 2026-08-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0027_claimrequestpayment_is_from_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequestpayment',
            name='is_from_claim',
        ),
        migrations.AddField(
            model_name='claimrequestpayment',
            name='claim_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_request_payments', to='claimrequest.claimrequeststep'),
        ),
    ]
