# Generated by Django 5.0.8 on 2026-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0028_remove_claimrequestpayment_is_from_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststep',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
