# Generated by Django 5.0.8 on 2026-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0029_claimrequeststep_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststep',
            name='price_rate_billing_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('invoice', 'Invoice')], default='invoice', max_length=255, null=True),
        ),
    ]
