# Generated by Django 5.0.8 on 2026-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0030_claimrequeststep_price_rate_billing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequeststep',
            name='price_rate_billing_type',
        ),
        migrations.AddField(
            model_name='claimrequeststeptemplate',
            name='price_rate_billing_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('invoice', 'Invoice')], default='invoice', max_length=255, null=True),
        ),
    ]
