# Generated by Django 5.0.8 on 2026-09-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0031_remove_claimrequeststep_price_rate_billing_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequeststeptemplate',
            old_name='price_rate_billing_type',
            new_name='billing_type',
        ),
    ]
