# Generated by Django 5.0.8 on 2026-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0032_rename_price_rate_billing_type_claimrequeststeptemplate_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequeststeptemplate',
            name='group_payments',
            field=models.BooleanField(default=False),
        ),
    ]
