# Generated by Django 5.0.8 on 2025-04-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_calendartask'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartask',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendartask',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
