# Generated by Django 5.0.8 on 2025-05-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_incidentreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.incidentstatus'),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.incidenttype'),
        ),
    ]
