# Generated by Django 5.0.8 on 2025-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_incident_status_incident_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='tasks',
        ),
        migrations.AddField(
            model_name='incident',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='notification.calendartask'),
        ),
    ]
