# Generated by Django 5.0.8 on 2025-06-11 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_generalnotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralNotes',
            new_name='GeneralNote',
        ),
    ]
