# Generated by Django 5.0.8 on 2025-06-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_rename_generalnotes_generalnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalnote',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='generalnote',
            name='title',
        ),
    ]
