# Generated by Django 5.0.8 on 2025-06-13 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_rename_description_generalnote_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
