# Generated by Django 5.0.8 on 2025-06-13 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_notification_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
