# Generated by Django 5.0.8 on 2025-06-13 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_notification_archived_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnote',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_general_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
