# Generated by Django 5.0.8 on 2025-06-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0015_document_file'),
        ('notification', '0016_generalnote_read_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document')),
                ('incident_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_files', to='notification.incidentreport')),
            ],
        ),
    ]
