# Generated by Django 5.0.8 on 2025-06-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0174_remove_contract_debt_amount'),
        ('notification', '0017_incidentdocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartask',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_tasks', to='contract.contract'),
        ),
    ]
