# Generated by Django 5.0.8 on 2025-07-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0179_reading_billing'),
        ('notification', '0018_calendartask_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='commitment_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='billing.commitmentdeposit'),
        ),
    ]
