# Generated by Django 5.0.8 on 2025-07-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_incident_commitment_deposit'),
        ('order', '0023_order_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='order_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='order.order'),
        ),
    ]
