# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_incident_order_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendartask',
            options={'verbose_name': 'Calendar Task', 'verbose_name_plural': 'Calendar Tasks'},
        ),
        migrations.AlterModelOptions(
            name='generalnote',
            options={'verbose_name': 'General Note', 'verbose_name_plural': 'General Notes'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
