# Generated by Django 5.0.8 on 2025-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_alter_calendartask_options_alter_generalnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
