# Generated by Django 5.0.8 on 2026-08-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_incidenttype_latitude_incidenttype_longitude'),
        ('service', '0116_exploitation_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='supply_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='service.supplypoint'),
        ),
    ]
