# Generated by Django 5.0.8 on 2026-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_incident_supply_point'),
        ('service', '0130_exploitation_incasol_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='service.cluster'),
        ),
    ]
