# Generated by Django 5.0.8 on 2025-06-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('service', '0077_remove_companyconfig_company_company_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='company_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_config', to='service.company'),
        ),
    ]
