# Generated by Django 5.0.8 on 2025-06-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_communication_company_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='company',
        ),
    ]
