# Generated by Django 5.0.8 on 2025-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_communication_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='generation_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
