# Generated by Django 5.0.8 on 2025-06-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_communicationprocess_generation_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationprocess',
            name='generation_task_id',
        ),
    ]
