# Generated by Django 5.0.8 on 2025-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0167_remove_payment_bank_token'),
        ('communication', '0006_remove_communicationprocess_generation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='communications', to='billing.invoice'),
        ),
    ]
