# Generated by Django 5.0.8 on 2025-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_communication_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationfile',
            name='is_letter',
            field=models.BooleanField(default=False),
        ),
    ]
