# Generated by Django 5.0.8 on 2025-06-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_communicationfile_is_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='communicationprocess',
            name='message',
        ),
        migrations.AddField(
            model_name='communication',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='communications', to='communication.message'),
        ),
        migrations.AddField(
            model_name='communicationprocess',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='communication_processes', to='communication.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.messagetype'),
        ),
    ]
