# Generated by Django 5.0.8 on 2025-06-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_remove_communication_message_and_more'),
        ('contract', '0174_remove_contract_debt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='contract.contract'),
        ),
    ]
