# Generated by Django 5.0.8 on 2025-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_communication_contract'),
        ('contract', '0174_remove_contract_debt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='contract',
        ),
        migrations.AddField(
            model_name='communication',
            name='contracts',
            field=models.ManyToManyField(blank=True, related_name='communications', to='contract.contract'),
        ),
    ]
