# Generated by Django 5.0.8 on 2025-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_remove_communication_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='always_attach',
            field=models.BooleanField(default=False),
        ),
    ]
