# Generated by Django 5.0.8 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_communication_always_attach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
    ]
