# Generated by Django 5.0.8 on 2025-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_alter_communication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageorigin',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
