# Generated by Django 5.0.8 on 2025-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_messageorigin_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageorigin',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
