# Generated by Django 5.0.8 on 2025-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_messageorigin_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
