# Generated by Django 5.0.8 on 2025-11-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_communicationprocess_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='accounting_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='managing_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='processing_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
