# Generated by Django 5.0.8 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_communication_accounting_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='updating_messages_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
