# Generated by Django 5.0.8 on 2026-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_communicationprocess_updating_messages_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
