# Generated by Django 5.0.8 on 2026-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0020_add_config_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='download_einvoices_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationprocess',
            name='download_letters_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
