# Generated by Django 5.0.8 on 2026-04-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_communicationprocess_download_einvoices_task_id_and_more'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='documentmanager.document'),
        ),
    ]
