# Generated by Django 5.0.8 on 2026-05-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0289_fix_commitment_deposits_tokens'),
        ('communication', '0023_remove_message_document_messagetypetemplate_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationUseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='communications', to='billing.reading'),
        ),
        migrations.AddField(
            model_name='communicationfile',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='communicationprocess',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='communication_processes', to='billing.reading'),
        ),
        migrations.AddField(
            model_name='communication',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationusetype'),
        ),
        migrations.AddField(
            model_name='communicationprocess',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationusetype'),
        ),
    ]
