# Generated by Django 5.0.8 on 2026-06-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0291_rename_payment_origin_payment_payment_origin_choice'),
        ('communication', '0024_communicationusetype_communication_readings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='reading_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_processes', to='billing.readingbatch'),
        ),
    ]
