# Generated by Django 5.0.8 on 2026-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0025_communicationprocess_reading_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationprocess',
            name='reading_batch',
        ),
    ]
