# Generated by Django 5.0.8 on 2026-06-01 07:24

from django.db import migrations

def fix_finalized_processes_status(apps, schema_editor):
    try:
        CommunicationProcess = apps.get_model('communication', 'CommunicationProcess')
        CommunicationProcessStatus = apps.get_model('communication', 'CommunicationProcessStatus')
        ConfigProject = apps.get_model('coredata', 'ConfigProject')
        
        try:
            communication_status_sent_token = ConfigProject.objects.get(token='communication_status_sent_token').value
        except ConfigProject.DoesNotExist:
            ConfigProject.objects.create(
                token='communication_status_sent_token',
                name="Token d'estat enviat d'una comunicació",
                value='1'
            )
            communication_status_sent_token = ConfigProject.objects.get(token='communication_status_sent_token').value
        try:
            communication_process_status_current_token = ConfigProject.objects.get(token='communication_process_status_current_token').value
        except ConfigProject.DoesNotExist:
            ConfigProject.objects.create(
                token='communication_process_status_current_token',
                name="Token d'estat actual d'un procés de comunicació",
                value='2'
            )
            communication_process_status_current_token = ConfigProject.objects.get(token='communication_process_status_current_token').value
        
        processes = CommunicationProcess.objects.filter(
            status__token=communication_process_status_current_token
        ).distinct()
        
        for process in processes:
            if all(communication.status.token == communication_status_sent_token for communication in process.communications.all()):
                process.status = CommunicationProcessStatus.objects.get(token=ConfigProject.objects.get(token='communication_process_status_finalized_token').value)
                process.save()
    
    except Exception as e:
        print("Error fixing finalized processes status: ", e)
        return
    


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0026_remove_communicationprocess_reading_batch'),
    ]

    operations = [
        migrations.RunPython(fix_finalized_processes_status),
    ]
