# Generated by Django 5.0.8 on 2026-06-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0027_fix_finalized_processes_status'),
        ('service', '0108_move_companyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='company_config_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_config_email', to='service.companyconfigemail'),
        ),
    ]
