# Generated by Django 5.0.8 on 2026-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0028_communication_company_config_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationfile',
            name='attach_to_email',
            field=models.BooleanField(default=True),
        ),
    ]
