# Generated by Django 5.0.8 on 2026-08-21 10:00

from django.db import migrations

def create_returned_status(apps, schema_editor):
    CommunicationStatus = apps.get_model('communication', 'CommunicationStatus')
    CommunicationStatus.objects.get_or_create(
        token='-3',
        defaults={
            'name': 'Retornada',
            'color': 'purple',
            'description': 'Comunicació retornada',
            'position': 1,
            'is_default': False,
        }
    )

def reverse_create_returned_status(apps, schema_editor):
    CommunicationStatus = apps.get_model('communication', 'CommunicationStatus')
    CommunicationStatus.objects.filter(token='-3').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0029_communicationfile_attach_to_email'),
    ]

    operations = [
        migrations.RunPython(create_returned_status, reverse_create_returned_status),
    ]