# Generated by Django 5.0.8 on 2026-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0031_communicationfile_attach_to_letter'),
        ('service', '0128_supply_cut_status_planificat'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationprocess',
            name='run_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='communicationprocess',
            name='supply_cuts',
            field=models.ManyToManyField(blank=True, related_name='communication_processes', to='service.supplycut'),
        ),
    ]
