# Generated by Django 5.0.8 on 2024-10-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
