# Generated by Django 5.0.8 on 2024-10-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_variables_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_usage',
        ),
        migrations.DeleteModel(
            name='ContractUsage',
        ),
    ]
