# Generated by Django 5.0.8 on 2024-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_contract_usage_delete_contractusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='variables',
            field=models.ManyToManyField(related_name='contract_variables', to='contract.variable'),
        ),
    ]
