# Generated by Django 5.0.8 on 2024-10-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_bonificationrequestobservation_contractobservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='variables',
            new_name='variable',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contact',
        ),
    ]
