# Generated by Django 5.0.8 on 2024-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_rename_variables_contract_variable_and_more'),
        ('coredata', '0004_cnae_paymenttype_personcnae_personpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='propietary',
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_owner', to='coredata.person', verbose_name='Contract Owner'),
        ),
    ]
