# Generated by Django 5.0.8 on 2024-10-02 11:13

import contract.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contract_propietary_contract_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificationRequestDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contract.models.documentation_upload_to)),
                ('bonification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_files', to='contract.bonificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRequestDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contract.models.documentation_upload_to)),
                ('contract_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_files', to='contract.contractrequest')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractrequesttype', verbose_name='Contract Type')),
            ],
        ),
    ]
