# Generated by Django 5.0.8 on 2024-10-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_bonificationrequestdocumentation_and_more'),
        ('service', '0046_alter_supplypoint_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequesttype', verbose_name='Bail Contract Request Type'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='bail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_requests', to='contract.bail'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='supplyPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypoint', verbose_name='Contract Request SupplyPoint'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractrequesttype', verbose_name='Contract Request Type Documentation'),
        ),
    ]
