# Generated by Django 5.0.8 on 2024-10-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_bail_type_contractrequest_bail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='supplyPoint',
            new_name='supply_point',
        ),
    ]
