# Generated by Django 5.0.8 on 2024-10-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_bonificationtypedocumentationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='type',
        ),
    ]
