# Generated by Django 5.0.8 on 2024-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_remove_bail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificationtype',
            name='variable',
            field=models.ManyToManyField(null=True, related_name='bonification_type_variables', to='contract.variable'),
        ),
    ]
