# Generated by Django 5.0.8 on 2024-10-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_bonificationtype_variable'),
        ('coredata', '0009_merge_20241003_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ManyToManyField(null=True, related_name='representative_type_person', to='coredata.person')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_representative', to='contract.representativetype', verbose_name='Contract Representative'),
        ),
    ]
