# Generated by Django 5.0.8 on 2024-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_contractrepresentativerole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificationtype',
            name='variable',
            field=models.ManyToManyField(related_name='bonification_type_variables', to='contract.variable'),
        ),
    ]
