# Generated by Django 5.0.8 on 2024-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_bonificationtype_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrepresentative',
            name='role',
        ),
        migrations.AddField(
            model_name='contractrepresentative',
            name='role',
            field=models.ManyToManyField(related_name='contract_representative_roles', to='contract.contractrepresentativerole'),
        ),
    ]
