# Generated by Django 5.0.8 on 2024-10-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_remove_contractrepresentative_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bonificationrequestdocumentation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.bonificationtypedocumentationtype'),
        ),
        migrations.RemoveField(
            model_name='contractrepresentative',
            name='role',
        ),
        migrations.AddField(
            model_name='variable',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.variabletype', verbose_name='Variable Type'),
        ),
        migrations.AddField(
            model_name='contractrepresentative',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrepresentativerole'),
        ),
    ]
