# Generated by Django 5.0.8 on 2024-10-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_variabletype_bonificationrequestdocumentation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequestDocumentationType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='position',
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequesttype'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='variable',
            field=models.ManyToManyField(related_name='contract_requests', to='contract.variable'),
        ),
        migrations.AddField(
            model_name='contractrequesttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractrequesttype',
            name='variable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.variabletype', verbose_name='Variable Type'),
        ),
        migrations.AlterField(
            model_name='bonificationrequestdocumentation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonificationrequestdocumentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrepresentativerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrepresentativerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrequesttype',
            name='documentation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractrequestdocumentationtype'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractrequestdocumentationtype'),
        ),
    ]
