# Generated by Django 5.0.8 on 2024-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_contractrequestdocumentationtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonificationtype',
            old_name='variable',
            new_name='variables',
        ),
        migrations.RenameField(
            model_name='contractrequest',
            old_name='variable',
            new_name='variables',
        ),
        migrations.RemoveField(
            model_name='bonificationtype',
            name='documentation_type',
        ),
        migrations.AddField(
            model_name='bonificationtype',
            name='documentation_types',
            field=models.ManyToManyField(related_name='bonification_type_documentation_types', to='contract.bonificationtypedocumentationtype'),
        ),
    ]
