# Generated by Django 5.0.8 on 2024-10-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_rename_variable_bonificationtype_variables_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonificationrequest',
            old_name='bonification_type',
            new_name='bonification_types',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='variable',
            new_name='variables',
        ),
        migrations.RenameField(
            model_name='contractrequesttype',
            old_name='documentation_type',
            new_name='documentation_types',
        ),
    ]
