# Generated by Django 5.0.8 on 2024-10-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_contractpayment_contractpaymenttype'),
        ('coredata', '0013_remove_personpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayment',
            name='person_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personbank', verbose_name='Contract Payment Bank'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractpayment', verbose_name='Contract Payment'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractpaymenttype', verbose_name='Contract Payment Type'),
        ),
    ]
