# Generated by Django 5.0.8 on 2024-10-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_contractpayment_person_bank_alter_contract_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayment',
            name='type',
        ),
        migrations.RenameField(
            model_name='contractpayment',
            old_name='person_bank',
            new_name='IBAN',
        ),
        migrations.DeleteModel(
            name='ContractPaymentType',
        ),
    ]
