# Generated by Django 5.0.8 on 2024-10-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_remove_contractpayment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('CASH', 'Efectiu'), ('BANK_TRANSFER', 'Transferència bancària'), ('DIRECT_DEBIT', 'Domiciliació bancària'), ('CARD', 'Targeta')], unique=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.paymenttype', verbose_name='Contract Payment Type'),
        ),
    ]
