# Generated by Django 5.0.8 on 2024-10-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_paymenttype_contractpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificationtypedocumentationtype',
            name='bonification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonification_type_documentation_types', to='contract.bonificationtype'),
        ),
    ]
