# Generated by Django 5.0.8 on 2024-10-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_bonificationtypedocumentationtype_bonification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificationtype',
            name='documentation_types',
        ),
        migrations.RemoveField(
            model_name='bonificationtype',
            name='variables',
        ),
    ]
