# Generated by Django 5.0.8 on 2024-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0028_remove_bonificationtype_documentation_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificationtype',
            name='variable_types',
            field=models.ManyToManyField(blank=True, related_name='bonification_types', to='contract.variabletype'),
        ),
        migrations.AddField(
            model_name='variabletype',
            name='data_type',
            field=models.CharField(blank=True, choices=[('bool', 'Boolean'), ('int', 'Integer'), ('char', 'Character'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime')], unique=True),
        ),
    ]
