# Generated by Django 5.0.8 on 2024-10-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_bonificationtype_variable_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='documentation_types',
        ),
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='variable_type',
        ),
        migrations.RemoveField(
            model_name='variabletype',
            name='is_default',
        ),
        migrations.AddField(
            model_name='contractrequestdocumentationtype',
            name='contract_request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_request_documentation_type', to='contract.contractrequesttype'),
        ),
        migrations.AddField(
            model_name='contractrequesttype',
            name='variable_types',
            field=models.ManyToManyField(blank=True, related_name='bonification_types', to='contract.variabletype'),
        ),
        migrations.AlterField(
            model_name='bonificationtype',
            name='variable_types',
            field=models.ManyToManyField(blank=True, related_name='variable_types', to='contract.variabletype'),
        ),
    ]
