# Generated by Django 5.0.8 on 2024-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_remove_contractrequesttype_documentation_types_and_more'),
        ('order', '0002_order_contract_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='order_types',
            field=models.ManyToManyField(blank=True, to='order.ordertype', verbose_name='Contract Request Order Type'),
        ),
    ]
