# Generated by Django 5.0.8 on 2024-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_contractrequesttype_order_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletype',
            name='application',
            field=models.CharField(blank=True, choices=[('SP', 'SupplyPoint'), ('CT', 'Contract'), ('C', 'Cycle')], unique=True),
        ),
    ]
