# Generated by Django 5.0.8 on 2024-10-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_variabletype_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractRepresentativeRole',
            new_name='ContractRepresentativeType',
        ),
    ]
