# Generated by Django 5.0.8 on 2024-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_rename_contractrepresentativerole_contractrepresentativetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletype',
            name='application',
            field=models.CharField(blank=True, choices=[('SP', 'SupplyPoint'), ('CT', 'Contract'), ('C', 'Cycle')]),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='data_type',
            field=models.CharField(blank=True, choices=[('bool', 'Boolean'), ('int', 'Integer'), ('char', 'Character'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime')]),
        ),
    ]
