# Generated by Django 5.0.8 on 2024-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_alter_variabletype_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='type',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectiu'), ('BANK_TRANSFER', 'Transferència bancària'), ('DIRECT_DEBIT', 'Domiciliació bancària'), ('CARD', 'Targeta')], null=True),
        ),
    ]
