# Generated by Django 5.0.8 on 2024-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_alter_paymenttype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='type',
            field=models.CharField(choices=[('CASH', 'Efectiu'), ('BANK_TRANSFER', 'Transferència bancària'), ('DIRECT_DEBIT', 'Domiciliació bancària'), ('CARD', 'Targeta')], default='DIRECT_DEBIT'),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='application',
            field=models.CharField(choices=[('CT', 'Contract'), ('SP', 'SupplyPoint'), ('C', 'Cycle')], default='CT'),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='data_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('char', 'Character'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime')], default='char'),
        ),
    ]
