# Generated by Django 5.0.8 on 2024-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_alter_paymenttype_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
