# Generated by Django 5.0.8 on 2024-10-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_alter_paymenttype_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrepresentative',
            old_name='role',
            new_name='type',
        ),
    ]
