# Generated by Django 5.0.8 on 2024-10-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0037_contractrequesttype_is_default'),
        ('contract', '0037_rename_role_contractrepresentative_type'),
    ]

    operations = [
    ]
