# Generated by Django 5.0.8 on 2024-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_merge_20241009_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
