# Generated by Django 5.0.8 on 2024-10-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_merge_20241009_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequestdocumentationtype',
            name='contract_request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_types', to='contract.contractrequesttype'),
        ),
    ]
