# Generated by Django 5.0.8 on 2024-10-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0039_alter_contractrequestdocumentationtype_contract_request_type'),
        ('contract', '0039_rename_type_paymenttype_name_and_more'),
    ]

    operations = [
    ]
