# Generated by Django 5.0.8 on 2024-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0040_merge_20241009_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variabletype',
            name='color',
        ),
        migrations.AlterField(
            model_name='contract',
            name='variables',
            field=models.ManyToManyField(blank=True, related_name='contract_variables', to='contract.variable'),
        ),
    ]
