# Generated by Django 5.0.8 on 2024-10-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0040_merge_20241009_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract',
            new_name='contract_termination_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contract.contractrequest'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='contract_termination_lecture',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
