# Generated by Django 5.0.8 on 2024-10-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0042_contractsurrogationtype_contractterminationstatus_and_more'),
        ('coredata', '0021_alter_bank_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttermination',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contracttermination',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contracttermination',
            name='type',
        ),
        migrations.CreateModel(
            name='ContractSurrogationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_requests', to='coredata.person')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractsurrogationtype')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTerminationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_termination_requests', to='coredata.person')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractterminationstatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contractterminationtype')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractSurrogation',
        ),
        migrations.DeleteModel(
            name='ContractTermination',
        ),
    ]
