# Generated by Django 5.0.8 on 2024-10-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0043_remove_contracttermination_contract_and_more'),
        ('order', '0003_rename_cmms_orderobservation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
