# Generated by Django 5.0.8 on 2024-10-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0045_clausestemplate_contractclauses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='clauses',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='clauses',
        ),
        migrations.AddField(
            model_name='clausestemplate',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contractclauses',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
    ]
