# Generated by Django 5.0.8 on 2024-10-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0046_remove_contract_clauses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clausestemplate',
            name='contract',
        ),
        migrations.AddField(
            model_name='clausestemplate',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequest'),
        ),
    ]
