# Generated by Django 5.0.8 on 2024-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0047_remove_clausestemplate_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequest',
            name='variables',
            field=models.ManyToManyField(blank=True, null=True, related_name='contract_requests', to='contract.variable'),
        ),
    ]
