# Generated by Django 5.0.8 on 2024-10-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0048_alter_contractrequest_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='supplyPoint',
            new_name='supply_point',
        ),
    ]
