# Generated by Django 5.0.8 on 2024-10-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0049_rename_supplypoint_contractrequest_supply_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequest',
            name='variables',
            field=models.ManyToManyField(blank=True, related_name='contract_requests', to='contract.variable'),
        ),
    ]
