# Generated by Django 5.0.8 on 2024-10-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_remove_variabletype_color_alter_contract_variables'),
        ('contract', '0050_alter_contractrequest_variables'),
    ]

    operations = [
    ]
