# Generated by Django 5.0.8 on 2024-10-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0051_merge_20241011_1051'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_holder', to='coredata.person', verbose_name='Contract Holder'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_owner', to='coredata.person', verbose_name='Contract Owner'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_tenant', to='coredata.person', verbose_name='Contract Tenant'),
        ),
    ]
