# Generated by Django 5.0.8 on 2024-10-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0052_alter_contract_holder_alter_contract_owner_and_more'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_request_holder', to='coredata.person', verbose_name='Contract Holder'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_request_owner', to='coredata.person', verbose_name='Contract Owner'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_request_tenant', to='coredata.person', verbose_name='Contract Tenant'),
        ),
        migrations.CreateModel(
            name='ContractRequestRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='contract.contractrequest')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.person')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrepresentativetype')),
            ],
        ),
    ]
