# Generated by Django 5.0.8 on 2024-10-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_contractrequest_holder_contractrequest_owner_and_more'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsurrogationrequest',
            name='previous_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.person'),
        ),
    ]
