# Generated by Django 5.0.8 on 2024-10-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0053_contractrequest_holder_contractrequest_owner_and_more'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='address_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_billing', to='coredata.personaddress', verbose_name='Contract Billing Address'),
        ),
        migrations.AddField(
            model_name='contract',
            name='address_shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_shipping', to='coredata.personaddress', verbose_name='Contract Shipping Address'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='address_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_requests_billing', to='coredata.personaddress', verbose_name='Contract Billing Address'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='address_shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_requests_shipping', to='coredata.personaddress', verbose_name='Contract Shipping Address'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractpayment', verbose_name='Contract Payment'),
        ),
    ]
