# Generated by Django 5.0.8 on 2024-10-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0054_contractsurrogationrequest_previous_person'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsurrogationrequest',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_holder', to='coredata.person'),
        ),
        migrations.AlterField(
            model_name='contractsurrogationrequest',
            name='previous_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_prevoious_holder', to='coredata.person'),
        ),
    ]
