# Generated by Django 5.0.8 on 2024-10-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0054_contract_address_billing_contract_address_shipping_and_more'),
        ('coredata', '0022_merge_20241011_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='address_shipping',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='address_shipping',
        ),
        migrations.AddField(
            model_name='contract',
            name='address_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_contact', to='coredata.personaddress', verbose_name='Contract Contact Address'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='address_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_requests_contract', to='coredata.personaddress', verbose_name='Contract Contact Address'),
        ),
    ]
