# Generated by Django 5.0.8 on 2024-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0055_remove_contract_address_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='token',
            field=models.CharField(choices=[('CASH', 'Efectiu'), ('BANK_TRANSFER', 'Transferència bancària'), ('DIRECT_DEBIT', 'Domiciliació bancària'), ('CARD', 'Targeta')], default='DIRECT_DEBIT'),
        ),
    ]
