# Generated by Django 5.0.8 on 2024-10-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0055_alter_contractsurrogationrequest_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractsurrogationrequest',
            old_name='person',
            new_name='new_holder',
        ),
        migrations.RenameField(
            model_name='contractsurrogationrequest',
            old_name='previous_person',
            new_name='previous_holder',
        ),
    ]
