# Generated by Django 5.0.8 on 2024-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0056_alter_paymenttype_name_alter_paymenttype_token'),
        ('contract', '0056_rename_person_contractsurrogationrequest_new_holder_and_more'),
    ]

    operations = [
    ]
