# Generated by Django 5.0.8 on 2024-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0057_bailtype_bail_is_active_bail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailtype',
            name='bail_value',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
