# Generated by Django 5.0.8 on 2024-10-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0057_merge_20241016_1028'),
        ('contract', '0058_bailtype_bail_value'),
    ]

    operations = [
    ]
