# Generated by Django 5.0.8 on 2024-10-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0059_merge_20241016_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsurrogationrequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surrogations', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
