# Generated by Django 5.0.8 on 2024-10-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0060_alter_contractsurrogationrequest_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bailtype',
            old_name='bail_value',
            new_name='default_import',
        ),
    ]
