# Generated by Django 5.0.8 on 2024-10-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0061_rename_bail_value_bailtype_default_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailtype',
            name='is_default',
        ),
    ]
