# Generated by Django 5.0.8 on 2024-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0062_remove_bailtype_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract_termination_lecture',
            new_name='contract_termination_lecture_old',
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='contract_termination_lecture_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
