# Generated by Django 5.0.8 on 2024-10-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0063_rename_contract_termination_lecture_contractrequest_contract_termination_lecture_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract_termination_lecture_new',
            new_name='contract_termination_lecture',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='contract_termination_lecture_old',
        ),
    ]
