# Generated by Django 5.0.8 on 2024-10-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0064_rename_contract_termination_lecture_new_contractrequest_contract_termination_lecture_and_more'),
        ('coredata', '0023_personbank_dni_personbank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='person_contact_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_requests_contact_email', to='coredata.personcontact'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='person_contact_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_requests_contact_phone', to='coredata.personcontact'),
        ),
    ]
