# Generated by Django 5.0.8 on 2024-10-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0065_contractrequest_communication_type_and_more'),
        ('coredata', '0023_personbank_dni_personbank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequest',
            name='person_contact_phone',
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_contacts', to='coredata.personcontact'),
        ),
    ]
