# Generated by Django 5.0.8 on 2024-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0067_contractterminationrequestobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
