# Generated by Django 5.0.8 on 2024-10-23 06:13

import contract.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0067_contractterminationrequestobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSurrogationRequestDocumentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSurrogationRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=contract.models.documentation_upload_to)),
                ('contract_surrogation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contractsurrogationrequest')),
                ('contract_surrogation_request_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contractsurrogationrequestdocumenttype')),
            ],
        ),
    ]
