# Generated by Django 5.0.8 on 2024-10-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0068_contractsurrogationrequestdocumenttype_and_more'),
        ('coredata', '0029_personbank_swift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsurrogationrequestdocument',
            name='contract_surrogation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contractsurrogationrequest'),
        ),
        migrations.AlterField(
            model_name='contractsurrogationrequestdocument',
            name='contract_surrogation_request_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contractsurrogationrequestdocumenttype'),
        ),
        migrations.CreateModel(
            name='ContractTenantChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_changes', to='contract.contract')),
                ('new_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_tenant_change_holder', to='coredata.person')),
                ('previous_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_tenant_change_prevoious_holder', to='coredata.person')),
            ],
        ),
    ]
