# Generated by Django 5.0.8 on 2024-10-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0068_variable_end_at_variable_start_at_variable_value'),
        ('contract', '0069_alter_contractsurrogationrequestdocument_contract_surrogation_request_and_more'),
    ]

    operations = [
    ]
