# Generated by Django 5.0.8 on 2024-10-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0070_merge_20241024_0807'),
        ('service', '0050_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='supply_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='service.supplypoint', verbose_name='Contract SupplyPoint'),
        ),
    ]
