# Generated by Django 5.0.8 on 2024-10-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0070_merge_20241024_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificationrequest',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonification_requests', to='contract.contractrequest'),
        ),
        migrations.AlterField(
            model_name='bonificationrequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonification_requests', to='contract.contract'),
        ),
    ]
