# Generated by Django 5.0.8 on 2024-10-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0071_bonificationrequest_contract_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='variables',
        ),
        migrations.AddField(
            model_name='variable',
            name='bonification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='contract.bonificationrequest'),
        ),
        migrations.AddField(
            model_name='variable',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='variable',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='contract.contractrequest'),
        ),
    ]
