# Generated by Django 5.0.8 on 2024-10-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0072_remove_contract_variables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificationrequest',
            name='bonification_types',
        ),
        migrations.AddField(
            model_name='bonificationrequest',
            name='bonification_type',
            field=models.ManyToManyField(related_name='bonification_request_bonification_type', to='contract.bonificationtype'),
        ),
    ]
