# Generated by Django 5.0.8 on 2024-10-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0073_remove_bonificationrequest_bonification_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificationrequest',
            name='bonification_type',
        ),
        migrations.AddField(
            model_name='bonificationrequest',
            name='bonification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonification_requests', to='contract.bonificationtype'),
        ),
    ]
