# Generated by Django 5.0.8 on 2024-10-24 13:34

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0074_remove_bonificationrequest_bonification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificationrequestdocumentation',
            name='file',
            field=models.FileField(upload_to=contract.models.bonification_request_documentation_upload_to),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='file',
            field=models.FileField(upload_to=contract.models.contract_request_documentation_upload_to),
        ),
        migrations.AlterField(
            model_name='contractsurrogationrequestdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_surrogation_documentation_upload_to),
        ),
    ]
