# Generated by Django 5.0.8 on 2024-10-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0075_alter_bonificationrequestdocumentation_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonificationRequestObservation',
        ),
    ]
