# Generated by Django 5.0.8 on 2024-10-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0076_delete_bonificationrequestobservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificationrequest',
            name='status',
        ),
        migrations.DeleteModel(
            name='BonificationRequestStatus',
        ),
    ]
