# Generated by Django 5.0.8 on 2024-10-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0078_bonification_variable_bonification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonificationRequestDocumentation',
        ),
    ]
