# Generated by Django 5.0.8 on 2024-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0079_delete_bonificationrequestdocumentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='bonification_request',
        ),
        migrations.DeleteModel(
            name='BonificationRequest',
        ),
    ]
