# Generated by Django 5.0.8 on 2024-10-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0071_alter_contract_supply_point'),
        ('contract', '0080_remove_variable_bonification_request_and_more'),
    ]

    operations = [
    ]
