# Generated by Django 5.0.8 on 2024-10-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0081_merge_20241025_0932'),
        ('coredata', '0029_personbank_swift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractSurrogationRequest',
            new_name='ContractSurrogation',
        ),
        migrations.RenameModel(
            old_name='ContractSurrogationRequestDocument',
            new_name='ContractSurrogationDocument',
        ),
        migrations.RenameModel(
            old_name='ContractSurrogationRequestDocumentType',
            new_name='ContractSurrogationDocumentType',
        ),
        migrations.RenameField(
            model_name='contractsurrogationdocument',
            old_name='contract_surrogation_request',
            new_name='contract_surrogation',
        ),
        migrations.RenameField(
            model_name='contractsurrogationdocument',
            old_name='contract_surrogation_request_document_type',
            new_name='contract_surrogation_document_type',
        ),
    ]
