# Generated by Django 5.0.8 on 2024-10-25 10:57

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0082_rename_contractsurrogationrequest_contractsurrogation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificationdocumentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.bonification_documentation_upload_to),
        ),
    ]
