# Generated by Django 5.0.8 on 2024-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0083_alter_bonificationdocumentation_file'),
        ('order', '0009_alter_orderobservation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_orders', to='order.order'),
        ),
    ]
