# Generated by Django 5.0.8 on 2024-10-29 09:40

import contract.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0084_contractrequest_orders'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractcategory'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_request_documentation_upload_to),
        ),
    ]
