# Generated by Django 5.0.8 on 2024-10-29 08:57

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0084_contractrequest_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_request_documentation_upload_to),
        ),
    ]
