# Generated by Django 5.0.8 on 2024-10-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0085_contractrequest_contract_termination_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequest',
            name='contract_termination_id',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='contract_termination_lecture',
        ),
    ]
