# Generated by Django 5.0.8 on 2024-10-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0085_contractrequest_category_contractrequest_price_rate_and_more'),
        ('contract', '0086_remove_contractrequest_contract_termination_id_and_more'),
    ]

    operations = [
    ]
