# Generated by Django 5.0.8 on 2024-10-29 09:56

import contract.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0086_remove_contractrequest_contract_termination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequestdocumentation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_files', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_request_documentation_upload_to),
        ),
    ]
