# Generated by Django 5.0.8 on 2024-10-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0087_contractrequestdocumentation_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_files', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_files', to='contract.contractrequest'),
        ),
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequestdocumentationtype'),
        ),
    ]
