# Generated by Django 5.0.8 on 2024-10-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0087_merge_20241029_0946'),
        ('contract', '0088_alter_contractrequestdocumentation_contract_and_more'),
    ]

    operations = [
    ]
