# Generated by Django 5.0.8 on 2024-10-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0085_alter_contractrequestdocumentation_file'),
        ('contract', '0089_merge_20241029_0957'),
    ]

    operations = [
    ]
