# Generated by Django 5.0.8 on 2024-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0090_merge_20241029_1451'),
        ('order', '0009_alter_orderobservation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='order_types',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_order_types', to='order.ordertype'),
        ),
    ]
