# Generated by Django 5.0.8 on 2024-10-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0090_merge_20241029_1128'),
        ('contract', '0091_contractrequest_order_types'),
    ]

    operations = [
    ]
