# Generated by Django 5.0.8 on 2024-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0092_merge_20241029_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequest',
            name='bail',
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='bail_types',
            field=models.ManyToManyField(blank=True, related_name='contract_requests', to='contract.bailtype'),
        ),
    ]
