# Generated by Django 5.0.8 on 2024-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0093_remove_contractrequest_bail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequest',
            name='bail_types',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_bail_types', to='contract.bailtype'),
        ),
    ]
