# Generated by Django 5.0.8 on 2024-10-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0094_alter_contractrequest_bail_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clausestemplate',
            old_name='clauses',
            new_name='clause',
        ),
        migrations.RenameField(
            model_name='contractclauses',
            old_name='clauses',
            new_name='clause',
        ),
        migrations.AddField(
            model_name='contractclauses',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequest'),
        ),
        migrations.AddField(
            model_name='contractclauses',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.clausestemplate'),
        ),
    ]
