# Generated by Django 5.0.8 on 2024-10-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0095_rename_clauses_clausestemplate_clause_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractClauses',
            new_name='ContractClause',
        ),
    ]
