# Generated by Django 5.0.8 on 2024-10-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0096_rename_contractclauses_contractclause'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClausesTemplate',
            new_name='ClauseTemplate',
        ),
    ]
