# Generated by Django 5.0.8 on 2024-10-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0097_rename_clausestemplate_clausetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clausetemplate',
            name='contract_request',
        ),
    ]
