# Generated by Django 5.0.8 on 2024-11-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0100_alter_contractsurrogation_new_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsurrogation',
            name='new_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_new_payment', to='contract.contractpayment'),
        ),
        migrations.AlterField(
            model_name='contractsurrogation',
            name='previous_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_previous_payment', to='contract.contractpayment'),
        ),
    ]
