# Generated by Django 5.0.8 on 2024-11-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0101_alter_contractsurrogation_new_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequest',
            name='orders',
        ),
    ]
