# Generated by Django 5.0.8 on 2024-11-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0102_remove_contractrequest_orders'),
        ('coredata', '0037_city_is_default_province_is_default_and_more'),
        ('pricing', '0006_pricerateitem_billing_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.bail', verbose_name='Contract Bail'),
        ),
        migrations.AddField(
            model_name='contract',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contract_contacts', to='coredata.personcontact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='person_contact_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_contact_email', to='coredata.personcontact'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricerate', verbose_name='Contract Price Rate'),
        ),
    ]
