# Generated by Django 5.0.8 on 2024-11-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0103_contract_bail_contract_communication_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractclause',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractclause',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='contract.contractrequest'),
        ),
    ]
