# Generated by Django 5.0.8 on 2024-11-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0104_acadocument_alter_contractclause_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACADocumentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_NIF', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cityCode', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_code', models.CharField(blank=True, max_length=255, null=True)),
                ('aca_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_changes', to='contract.acadocument')),
            ],
        ),
    ]
