# Generated by Django 5.0.8 on 2024-11-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0105_acadocumentchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acadocumentchange',
            old_name='cityCode',
            new_name='city_code',
        ),
    ]
