# Generated by Django 5.0.8 on 2024-11-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0105_contractusetype_alter_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='contract_client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractclienttype'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='contract_use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractusetype'),
        ),
    ]
