# Generated by Django 5.0.8 on 2024-11-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0106_contractrequest_contract_client_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='type',
            new_name='use_type',
        ),
    ]
