# Generated by Django 5.0.8 on 2024-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0106_rename_citycode_acadocumentchange_city_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadocument',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acadocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acadocument',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acadocument',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acadocument',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acadocument',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
