# Generated by Django 5.0.8 on 2024-11-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0107_rename_type_contract_use_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='bail',
        ),
        migrations.AddField(
            model_name='contract',
            name='bails',
            field=models.ManyToManyField(blank=True, related_name='contract_bails', to='contract.bail'),
        ),
    ]
