# Generated by Django 5.0.8 on 2024-11-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0107_acadocument_date_acadocument_name_acadocument_number_and_more'),
        ('contract', '0108_remove_contract_bail_contract_bails'),
    ]

    operations = [
    ]
