# Generated by Django 5.0.8 on 2024-11-15 09:18

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0109_merge_20241115_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contract/contract_file/'),
        ),
        migrations.AlterField(
            model_name='acadocument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_request_upload_to),
        ),
    ]
