# Generated by Django 5.0.8 on 2024-11-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0110_contract_contract_file_alter_acadocument_date_and_more'),
        ('order', '0011_order_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractterminationrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
