# Generated by Django 5.0.8 on 2024-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0111_alter_contractterminationrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='last_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractterminationrequest',
            name='last_reading_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
