# Generated by Django 5.0.8 on 2024-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0112_contractterminationrequest_last_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='order',
        ),
    ]
