# Generated by Django 5.0.8 on 2024-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0113_remove_contractterminationrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='bail_types',
            field=models.ManyToManyField(blank=True, to='contract.bailtype', verbose_name='Bail Type'),
        ),
        migrations.AddField(
            model_name='contractrequesttype',
            name='clause_templates',
            field=models.ManyToManyField(blank=True, to='contract.clausetemplate', verbose_name='Clause Template'),
        ),
    ]
