# Generated by Django 5.0.8 on 2024-11-22 08:58

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0114_contractrequesttype_bail_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_upload_to),
        ),
    ]
