# Generated by Django 5.0.8 on 2024-11-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0115_alter_contract_contract_file'),
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDataChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_changes', to='contract.contract')),
                ('new_address_billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_billing_address', to='coredata.personaddress')),
                ('new_address_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_contact_address', to='coredata.personaddress')),
                ('new_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_payment', to='contract.contractpayment')),
                ('new_person_contact_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_contact_email', to='coredata.personcontact')),
                ('previous_address_billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_billing_address', to='coredata.personaddress')),
                ('previous_address_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_contact_address', to='coredata.personaddress')),
                ('previous_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_payment', to='contract.contractpayment')),
                ('previous_person_contact_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_contact_email', to='coredata.personcontact')),
            ],
        ),
    ]
