# Generated by Django 5.0.8 on 2024-11-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0117_alter_contractdatachange_new_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdatachange',
            name='new_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_payment', to='contract.contractpayment'),
        ),
        migrations.AlterField(
            model_name='contractdatachange',
            name='previous_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_payment', to='contract.contractpayment'),
        ),
    ]
