# Generated by Django 5.0.8 on 2024-11-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0118_alter_contractdatachange_new_payment_and_more'),
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdatachange',
            name='new_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_payment', to='contract.paymenttype'),
        ),
        migrations.AddField(
            model_name='contractdatachange',
            name='previous_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_payment', to='contract.paymenttype'),
        ),
        migrations.AlterField(
            model_name='contractdatachange',
            name='new_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_payment', to='coredata.personbank'),
        ),
        migrations.AlterField(
            model_name='contractdatachange',
            name='previous_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_data_change_previous_payment', to='coredata.personbank'),
        ),
    ]
