# Generated by Django 5.0.8 on 2024-11-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0118_acadocumentstatus'),
        ('contract', '0119_contractdatachange_new_payment_type_and_more'),
    ]

    operations = [
    ]
