# Generated by Django 5.0.8 on 2024-11-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0120_merge_20241126_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadocumentchange',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
