# Generated by Django 5.0.8 on 2024-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0121_acadocumentchange_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadocument',
            name='closing',
            field=models.BooleanField(default=False),
        ),
    ]
