# Generated by Django 5.0.8 on 2024-11-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0122_acadocument_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadocument',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.acadocumentstatus'),
        ),
    ]
