# Generated by Django 5.0.8 on 2024-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0123_acadocument_status'),
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='cnae',
        ),
        migrations.AddField(
            model_name='contract',
            name='cnaes',
            field=models.ManyToManyField(blank=True, null=True, related_name='contracts', to='coredata.personcnae'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='cnaes',
            field=models.ManyToManyField(blank=True, null=True, related_name='contract_requests', to='coredata.personcnae'),
        ),
    ]
