# Generated by Django 5.0.8 on 2024-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0124_remove_contract_cnae_contract_cnaes_and_more'),
        ('coredata', '0046_remove_personbank_sepa_document_and_more'),
        ('pricing', '0025_remove_billingperiod_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='price_rates',
            field=models.ManyToManyField(blank=True, to='pricing.pricerate', verbose_name='Price Rate'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cnaes',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='coredata.personcnae'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='cnaes',
            field=models.ManyToManyField(blank=True, related_name='contract_requests', to='coredata.personcnae'),
        ),
    ]
