# Generated by Django 5.0.8 on 2024-12-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0125_alter_contract_cnaes_alter_contractrequest_cnaes'),
        ('contract', '0125_contractrequesttype_price_rates_alter_contract_cnaes_and_more'),
    ]

    operations = [
    ]
