# Generated by Django 5.0.8 on 2024-12-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0126_merge_20241212_0839'),
        ('pricing', '0028_remove_priceintervalstretch_start_stretch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price_rate',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='price_rate',
        ),
        migrations.AddField(
            model_name='contract',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='pricing.pricerate'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests', to='pricing.pricerate'),
        ),
    ]
