# Generated by Django 5.0.8 on 2024-12-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0127_remove_contract_price_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractterminationrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractterminationstatus'),
        ),
        migrations.AlterField(
            model_name='contractterminationrequest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractterminationtype'),
        ),
    ]
