# Generated by Django 5.0.8 on 2025-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0128_alter_contractterminationrequest_status_and_more'),
        ('pricing', '0058_rename_proporcional_price_lineitemtype_proportional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_request_type_registration_price_rates', to='pricing.pricerate', verbose_name='Registration Price Rate'),
        ),
        migrations.AlterField(
            model_name='contractrequesttype',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_request_type_price_rates', to='pricing.pricerate', verbose_name='Price Rate'),
        ),
    ]
