# Generated by Django 5.0.8 on 2025-01-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0129_contractrequesttype_registration_price_rates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequesttype',
            name='bail_types',
        ),
    ]
