# Generated by Django 5.0.8 on 2025-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0130_remove_contractrequesttype_bail_types'),
        ('pricing', '0058_rename_proporcional_price_lineitemtype_proportional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_registration_price_rates', to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_price_rates', to='pricing.pricerate'),
        ),
    ]
