# Generated by Django 5.0.8 on 2025-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0131_contractrequest_registration_price_rates_and_more'),
        ('pricing', '0058_rename_proporcional_price_lineitemtype_proportional_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_registration', to='pricing.pricerate'),
        ),
    ]
