# Generated by Django 5.0.8 on 2025-01-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_merge_20250113_1207'),
        ('contract', '0132_contract_registration_price_rates'),
        ('pricing', '0058_rename_proporcional_price_lineitemtype_proportional_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='bail',
            name='type',
        ),
        migrations.AddField(
            model_name='bail',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bails_contract', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='bail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='bail',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bail',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricerate'),
        ),
        migrations.AddField(
            model_name='bail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.product'),
        ),
        migrations.AddField(
            model_name='bail',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bail',
            name='return_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_price_rates', to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_registration_price_rates', to='pricing.pricerate'),
        ),
        migrations.AddField(
            model_name='bail',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.bailstatus'),
        ),
    ]
