# Generated by Django 5.0.8 on 2025-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0133_bailstatus_remove_bail_type_bail_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
