# Generated by Django 5.0.8 on 2025-01-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0134_bail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
    ]
