# Generated by Django 5.0.8 on 2025-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0135_bail_is_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequesttype',
            name='has_persons',
            field=models.BooleanField(default=False),
        ),
    ]
