# Generated by Django 5.0.8 on 2025-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0136_contractrequesttype_has_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='total_persons',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='total_persons',
            field=models.IntegerField(default=3),
        ),
    ]
