# Generated by Django 5.0.8 on 2025-01-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0137_contract_total_persons_contractrequest_total_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractrequesttype', verbose_name='Contract Request Type'),
        ),
    ]
