# Generated by Django 5.0.8 on 2025-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0138_contract_contract_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonification',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonification',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonificationtype',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonificationtype',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
