# Generated by Django 5.0.8 on 2025-01-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0139_bonification_end_at_bonification_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
