# Generated by Django 5.0.8 on 2025-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0140_variable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
