# Generated by Django 5.0.8 on 2025-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0141_variabletype_is_active'),
        ('service', '0054_meter_is_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='supplypoint_contracts', to='service.supplypoint'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='supply_points_contract_request', to='service.supplypoint'),
        ),
    ]
