# Generated by Django 5.0.8 on 2025-01-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0142_contract_supply_points_contractrequest_supply_points'),
        ('service', '0054_meter_is_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='supply_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_contracts', to='service.supplypoint', verbose_name='Contract SupplyPoint'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supply_points',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='service.supplypoint'),
        ),
    ]
