# Generated by Django 5.0.8 on 2025-01-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0143_alter_contract_supply_point_and_more'),
        ('service', '0054_meter_is_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='supply_point',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='supply_point',
        ),
        migrations.AddField(
            model_name='contract',
            name='supply_point_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_contracts', to='service.supplypoint', verbose_name='Contract SupplyPoint'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='supply_point_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.supplypoint', verbose_name='Contract Request SupplyPoint Default'),
        ),
    ]
