# Generated by Django 5.0.8 on 2025-01-29 11:04

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0145_alter_contract_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='contract_file_template',
            field=models.FileField(blank=True, null=True, upload_to=contract.models.contract_request_upload_to),
        ),
    ]
