# Generated by Django 5.0.8 on 2025-02-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0146_contractrequest_contract_file_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remittance_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
