# Generated by Django 5.0.8 on 2025-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0148_remove_contract_remittance_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayment',
            name='remittance_data',
        ),
        migrations.AddField(
            model_name='contract',
            name='remittance_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='remittance_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
