# Generated by Django 5.0.8 on 2025-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0149_remove_contractpayment_remittance_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='remittance_data',
            new_name='remittance_date',
        ),
    ]
