# Generated by Django 5.0.8 on 2025-02-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0150_rename_remittance_data_contractrequest_remittance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='remittance_data',
            new_name='remittance_date',
        ),
    ]
