# Generated by Django 5.0.8 on 2025-02-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0151_rename_remittance_data_contract_remittance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='remittance_date',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='remittance_date',
        ),
    ]
