# Generated by Django 5.0.8 on 2025-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0152_remove_contract_remittance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remittance_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='remittance_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
