# Generated by Django 5.0.8 on 2025-03-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0082_invoice_payment_company_bank'),
        ('contract', '0153_contract_remittance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.generalpayment', verbose_name='Contract Payment'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.generalpayment', verbose_name='Contract Payment'),
        ),
    ]
