# Generated by Django 5.0.8 on 2025-03-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0082_invoice_payment_company_bank'),
        ('contract', '0154_alter_contract_payment_alter_contractrequest_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsurrogation',
            name='new_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_new_payment', to='billing.generalpayment'),
        ),
        migrations.AlterField(
            model_name='contractsurrogation',
            name='previous_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_surrogation_previous_payment', to='billing.generalpayment'),
        ),
    ]
