# Generated by Django 5.0.8 on 2025-03-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0155_alter_contractsurrogation_new_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract_client_type',
            new_name='client_type',
        ),
    ]
