# Generated by Django 5.0.8 on 2025-03-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0156_rename_contract_client_type_contractrequest_client_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract_use_type',
            new_name='use_type',
        ),
    ]
