# Generated by Django 5.0.8 on 2025-03-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0158_contractdebtmanagement_contract_debt_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='debt_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractdebtmanagement'),
        ),
    ]
