# Generated by Django 5.0.8 on 2025-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0159_contractrequest_debt_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='simplified_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
