# Generated by Django 5.0.8 on 2025-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0160_contract_simplified_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('PHYSICAL', 'Física'), ('DIGITAL', 'Digital')], default='DIGITAL', max_length=10),
        ),
    ]
