# Generated by Django 5.0.8 on 2025-05-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0005_remove_claimrequeststeptemplate_action_date_at'),
        ('contract', '0161_alter_contract_communication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='claim_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_termination_requests', to='claimrequest.claimrequest'),
        ),
    ]
