# Generated by Django 5.0.8 on 2025-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0162_contractterminationrequest_claim_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='block_billing',
            field=models.BooleanField(default=False),
        ),
    ]
