# Generated by Django 5.0.8 on 2025-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0164_contractlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractterminationrequest',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
