# Generated by Django 5.0.8 on 2025-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0165_bail_is_marked_contract_is_marked_and_more'),
        ('coredata', '0066_remove_person_is_vulnerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='person_contact_sms',
            field=models.ManyToManyField(blank=True, related_name='contract_contact_sms', to='coredata.personcontact'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='person_contact_sms',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_contact_sms', to='coredata.personcontact'),
        ),
    ]
