# Generated by Django 5.0.8 on 2025-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0166_contract_person_contact_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractterminationrequest',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
