# Generated by Django 5.0.8 on 2025-06-12 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0167_bail_is_checked_contract_is_checked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='is_marked',
        ),
        migrations.AddField(
            model_name='contract',
            name='user_pinned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
