# Generated by Django 5.0.8 on 2025-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0168_remove_bail_is_marked_remove_contract_is_marked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='contractrequest',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='contract',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_debt_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
