# Generated by Django 5.0.8 on 2025-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0169_remove_bail_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractobservation',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
