# Generated by Django 5.0.8 on 2025-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0170_contractobservation_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractobservation',
            name='extra_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
