# Generated by Django 5.0.8 on 2025-06-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0171_contractobservation_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractobservation',
            name='extra_info',
        ),
    ]
