# Generated by Django 5.0.8 on 2025-06-19 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0172_remove_contractobservation_extra_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='contract',
            name='user_checked',
            field=models.ManyToManyField(blank=True, related_name='checked_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
