# Generated by Django 5.0.8 on 2025-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0173_remove_contract_is_checked_contract_user_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='debt_amount',
        ),
    ]
