# Generated by Django 5.0.8 on 2025-07-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0174_remove_contract_debt_amount'),
        ('pricing', '0077_remove_pricerate_calculation_remove_pricerate_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPriceRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rate_histories', to='pricing.billingrange')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rate_histories', to='contract.contract')),
                ('price_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rate_histories', to='pricing.pricerate')),
            ],
        ),
    ]
