# Generated by Django 5.0.8 on 2025-07-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0179_reading_billing'),
        ('contract', '0175_contractpriceratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.reading'),
        ),
    ]
