# Generated by Django 5.0.8 on 2025-07-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0176_contractterminationrequest_reading'),
        ('pricing', '0077_remove_pricerate_calculation_remove_pricerate_price'),
        ('service', '0081_route_reading_batch_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPriceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_price_rates', to='pricing.pricerate')),
                ('supply_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_price_rates', to='service.supplypoint')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_price_rates', to='contract.contractpricerate'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_registration_price_rates', to='contract.contractpricerate'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_price_rates', to='contract.contractpricerate'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_registration_price_rates', to='contract.contractpricerate'),
        ),
    ]
