# Generated by Django 5.0.8 on 2025-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0177_contractpricerate_alter_contract_price_rates_and_more'),
        ('pricing', '0077_remove_pricerate_calculation_remove_pricerate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contracts_registration_price_rates', to='pricing.pricerate'),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='registration_price_rates',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_registration_price_rates', to='pricing.pricerate'),
        ),
    ]
