# Generated by Django 5.0.8 on 2025-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0178_alter_contract_registration_price_rates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrequest',
            name='contract_termination_request',
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='contract_termination_request',
            field=models.ManyToManyField(blank=True, related_name='contract_requests_termination_requests', to='contract.contractterminationrequest'),
        ),
    ]
