# Generated by Django 5.0.8 on 2025-07-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0179_remove_contractrequest_contract_termination_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrequest',
            old_name='contract_termination_request',
            new_name='contract_termination_requests',
        ),
    ]
