# Generated by Django 5.0.8 on 2025-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0184_merge_20250717_0928'),
        ('contract', '0180_rename_contract_termination_request_contractrequest_contract_termination_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='last_reading',
        ),
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='last_reading_at',
        ),
        migrations.RemoveField(
            model_name='contractterminationrequest',
            name='reading',
        ),
        migrations.AddField(
            model_name='contractterminationrequest',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='contract_termination_requests', to='billing.reading'),
        ),
    ]
