# Generated by Django 5.0.8 on 2025-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0181_remove_contractterminationrequest_last_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='use_general_price_rates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='use_general_price_rates',
            field=models.BooleanField(default=False),
        ),
    ]
