# Generated by Django 5.0.8 on 2025-07-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0186_alter_invoicelineitem_units'),
        ('contract', '0182_contract_use_general_price_rates_and_more'),
        ('coredata', '0069_delete_personbanksepadocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiggyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piggy_banks', to='coredata.person')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='piggy_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contract.piggybank'),
        ),
        migrations.CreateModel(
            name='PiggyBankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_positive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piggy_bank_movements', to='billing.payment')),
                ('piggy_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='contract.piggybank')),
            ],
        ),
    ]
