# Generated by Django 5.0.8 on 2025-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0183_piggybank_contract_piggy_bank_piggybankmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybankmovement',
            name='movement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
