# Generated by Django 5.0.8 on 2025-07-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0186_alter_invoicelineitem_units'),
        ('contract', '0184_piggybankmovement_movement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybankmovement',
            name='bail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piggy_bank_movements', to='contract.bail'),
        ),
        migrations.AlterField(
            model_name='piggybankmovement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piggy_bank_movements', to='billing.payment'),
        ),
    ]
