# Generated by Django 5.0.8 on 2025-07-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0186_piggybankmovementstatus_piggybankmovement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piggybankmovement',
            name='status',
        ),
        migrations.DeleteModel(
            name='PiggyBankMovementStatus',
        ),
    ]
