# Generated by Django 5.0.8 on 2025-08-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0187_remove_piggybankmovement_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractterminationrequest',
            options={'verbose_name': 'Contract Termination Request', 'verbose_name_plural': 'Contract Termination Requests'},
        ),
    ]
