# Generated by Django 5.0.8 on 2025-08-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0188_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acadocument',
            options={'verbose_name': 'ACA Document', 'verbose_name_plural': 'ACA Documents'},
        ),
        migrations.AlterModelOptions(
            name='bail',
            options={'verbose_name': 'Bail', 'verbose_name_plural': 'Bails'},
        ),
        migrations.AlterModelOptions(
            name='bonification',
            options={'verbose_name': 'Bonification', 'verbose_name_plural': 'Bonifications'},
        ),
        migrations.AlterModelOptions(
            name='contractrequest',
            options={'verbose_name': 'Contract Request', 'verbose_name_plural': 'Contract Requests'},
        ),
    ]
