# Generated by Django 5.0.8 on 2025-08-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0189_alter_acadocument_options_alter_bail_options_and_more'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='termination_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_termination_requests', to='documentmanager.document'),
        ),
    ]
