# Generated by Django 5.0.8 on 2025-10-07 08:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0215_merge_20251002_0921'),
        ('contract', '0191_contractrequesttype_exploitation'),
        ('coredata', '0079_alter_streettype_abbreviation'),
        ('documentmanager', '0015_document_file'),
        ('pricing', '0088_alter_adjustment_line_item_type'),
        ('service', '0088_company_barcode_ident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['token'], name='contract_co_token_9937f4_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['holder'], name='contract_co_holder__9bb741_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='contract_search_vector_gin'),
        ),
    ]
