# Generated by Django 5.0.8 on 2025-10-07 08:41
from django.db import migrations
from django.db import connection

def populate_search_vectors(apps, schema_editor):
    Contract = apps.get_model('contract', 'Contract')
    
    print("\nPopulating search vectors...")
    
    batch_size = 500
    offset = 0
    total = 0
    
    while True:
        
        contracts = list(
            Contract.objects
            .select_related(
                'holder',
                'supply_point_default',
                'supply_point_default__address',
                'supply_point_default__address__city',
                'supply_point_default__address__street',
                'supply_point_default__address__street_number'
            )
            .order_by('pk')[offset:offset + batch_size]
        )
        
        if not contracts:
            break
        
        # Build search text for each contract
        to_update = []
        for contract in contracts:
            parts = []
            
            # Token
            if contract.token:
                parts.append(contract.token)
            
            # Holder
            if contract.holder:
                if contract.holder.name:
                    parts.append(contract.holder.name)
                if contract.holder.surname:
                    parts.append(contract.holder.surname)
                if contract.holder.token:
                    parts.append(contract.holder.token)
            
            # Supply point
            if contract.supply_point_default:
                sp = contract.supply_point_default
                if sp.token:
                    parts.append(sp.token)
                if sp.name:
                    parts.append(sp.name)
                
                # Address
                if sp.address:
                    addr = sp.address
                    if addr.street and addr.street.name:
                        parts.append(addr.street.name)
                    if addr.street_number and addr.street_number.number:
                        parts.append(str(addr.street_number.number))
                    if addr.city and addr.city.name:
                        parts.append(addr.city.name)
            
            
            search_text = ' '.join(filter(None, parts))
            
            # Escape single quotes for SQL
            search_text = search_text.replace("'", "''")
            
            # Store contract ID and search text
            to_update.append((contract.pk, search_text))
        
        
        with connection.cursor() as cursor:
            for contract_id, search_text in to_update:
                cursor.execute(
                    """
                    UPDATE contract_contract 
                    SET search_vector = to_tsvector('spanish', %s)
                    WHERE id = %s
                    """,
                    [search_text, contract_id]
                )
        
        total += len(contracts)
        offset += batch_size
        print(f"Updated {total} contracts...")
    
    print(f"Finished! Total: {total} contracts")

def reverse_populate(apps, schema_editor):
    Contract = apps.get_model('contract', 'Contract')
    Contract.objects.all().update(search_vector=None)

class Migration(migrations.Migration):
    dependencies = [
        ('contract', '0192_contract_search_vector_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_search_vectors, reverse_populate),
    ]