# Generated by Django 5.0.8 on 2025-10-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0192_alter_paymenttype_token'),
        ('contract', '0193_populate_search_vector_correctly'),
    ]

    operations = [
    ]
