# Generated by Django 5.0.8 on 2025-10-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0195_alter_contract_contract_file_and_more'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequestdocumentation',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentmanager.document'),
        ),
    ]
