# Generated by Django 5.0.8 on 2025-10-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0221_invoice_is_general'),
        ('contract', '0197_contractdocumentationtype_and_more'),
        ('coredata', '0079_alter_streettype_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('accounting_office', models.CharField(blank=True, max_length=255, null=True)),
                ('managing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('record', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.personaddress', verbose_name='Address Send')),
                ('contracts', models.ManyToManyField(blank=True, related_name='general_invoices', to='contract.contract')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.generalpayment', verbose_name='General Payment')),
            ],
        ),
    ]
