# Generated by Django 5.0.8 on 2025-10-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0198_generalinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinvoice',
            name='contracts',
        ),
        migrations.AddField(
            model_name='contract',
            name='general_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contract.generalinvoice'),
        ),
    ]
