# Generated by Django 5.0.8 on 2025-10-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0199_remove_generalinvoice_contracts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinvoice',
            name='accounting_office',
        ),
        migrations.RemoveField(
            model_name='generalinvoice',
            name='command',
        ),
        migrations.RemoveField(
            model_name='generalinvoice',
            name='managing_body',
        ),
        migrations.RemoveField(
            model_name='generalinvoice',
            name='processing_unit',
        ),
        migrations.RemoveField(
            model_name='generalinvoice',
            name='record',
        ),
    ]
