# Generated by Django 5.0.8 on 2025-11-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0231_reading_is_close'),
        ('contract', '0201_recalculate_search_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybankmovement',
            name='commitment_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piggy_bank_movements', to='billing.commitmentdeposit'),
        ),
    ]
