# Generated by Django 5.0.8 on 2025-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0202_piggybankmovement_commitment_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='token',
            field=models.CharField(choices=[('CASH', 'Efectiu'), ('BANK_TRANSFER', 'Transferència bancària'), ('DIRECT_DEBIT', 'Domiciliació bancària (SEPA)'), ('CARD', 'Targeta (TPV Físic)'), ('BARCODE', 'Pagament bancari (Codi de barres)'), ('TPVV', 'TPV Virtual'), ('BALANCE', 'Saldo')], default='DIRECT_DEBIT'),
        ),
    ]
