# Generated by Django 5.0.8 on 2025-12-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0203_alter_paymenttype_token'),
        ('service', '0093_exploitation_accountant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='requested_meter_caliber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.metercaliber', verbose_name='Meter Caliber'),
        ),
    ]
