# Generated by Django 5.0.8 on 2025-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0204_contractrequest_requested_meter_caliber'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletype',
            name='is_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
