# Generated by Django 5.0.8 on 2026-01-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0205_variabletype_is_vulnerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='use_aca',
            field=models.CharField(choices=[('Q', 'USOS RAMADERS SENSE CÀNON'), ('D', 'DOMÈSTICS'), ('I', 'INDUSTRIALS'), ('A', 'MUNICIPAL'), ('E', 'EXEMPTS'), ('M', 'MÈSURES DIRECTES')], default='D', max_length=10),
        ),
    ]
