# Generated by Django 5.0.8 on 2026-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0206_contract_use_aca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='use_aca',
            field=models.CharField(blank=True, choices=[('Q', 'USOS RAMADERS SENSE CÀNON'), ('D', 'DOMÈSTICS'), ('I', 'INDUSTRIALS'), ('A', 'MUNICIPAL'), ('E', 'EXEMPTS'), ('M', 'MÈSURES DIRECTES')], default=None, max_length=10, null=True),
        ),
    ]
