# Generated by Django 5.0.8 on 2026-01-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0207_alter_contract_use_aca'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_search_vector_gin',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='search_vector',
        ),
    ]
