# Generated by Django 5.0.8 on 2026-03-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0208_remove_contract_contract_search_vector_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequestdocumentationtype',
            name='list_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
