# Generated by Django 5.0.8 on 2026-03-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0209_contractdatachange_user'),
        ('contract', '0209_contractrequestdocumentationtype_list_name'),
    ]

    operations = [
    ]
