# Generated by Django 5.0.8 on 2026-03-12 07:48

from django.db import migrations

def add_payment_type_balance_config(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    if not ConfigProject.objects.filter(token='payment_type_balance_token').exists():
        ConfigProject.objects.create(
            token='payment_type_balance_token',
            name='Tipus de pagament Saldo',
            value='BALANCE'
        )
 
def remove_payment_type_balance(apps, schema_editor):
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    ConfigProject.objects.filter(token='payment_type_balance_token').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0210_merge_20260312_0848'),
    ]

    operations = [
        migrations.RunPython(add_payment_type_balance_config, remove_payment_type_balance),
    ]
