# Generated by Django 5.0.8 on 2026-03-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0211_add_configproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contract.contractusetype', verbose_name='Contract Use Type'),
        ),
    ]
