# Generated by Django 5.0.8 on 2026-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0212_alter_contract_use_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='bill_cut_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractterminationrequest',
            name='bill_cut_reading',
            field=models.BooleanField(default=False),
        ),
    ]
