# Generated by Django 5.0.8 on 2026-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0213_contractrequest_bill_cut_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('PHYSICAL', 'Física'), ('DIGITAL', 'Digital'), ('BOTH', 'Ambdues')], default='DIGITAL', max_length=10),
        ),
    ]
