# Generated by Django 5.0.8 on 2026-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0215_piggybankmovement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
