# Generated by Django 5.0.8 on 2026-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0216_contract_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrequest',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('PHYSICAL', 'Física'), ('DIGITAL', 'Digital'), ('BOTH', 'Ambdues')], default='DIGITAL', max_length=10),
        ),
    ]
