# Generated by Django 5.0.8 on 2026-05-06 08:27

from django.db import migrations, models

from contract.management.commands.fill_contract_termination_date import (
    fill_contract_termination_date_logic,
)


def fill_termination_dates(apps, schema_editor):
    fill_contract_termination_date_logic(apps=apps, dry_run=False, messenger=None)

class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0217_alter_contractrequest_communication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(fill_termination_dates, reverse_code=migrations.RunPython.noop),
    ]
