# Generated by Django 5.0.8 on 2026-05-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0218_contract_termination_date'),
        ('coredata', '0098_merge_20260504_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinvoice',
            name='address_send',
        ),
        migrations.AddField(
            model_name='generalinvoice',
            name='address_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_invoices_billing', to='coredata.personaddress', verbose_name='Address Billing'),
        ),
        migrations.AddField(
            model_name='generalinvoice',
            name='address_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_invoices_contact', to='coredata.personaddress', verbose_name='Address Contact'),
        ),
    ]
