# Generated by Django 5.0.8 on 2026-05-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0219_remove_generalinvoice_address_send_and_more'),
        ('service', '0104_company_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='service.company'),
        ),
    ]
