# Generated by Django 5.0.8 on 2026-05-13

from django.db import migrations

def add_cancelled_bail_status(apps, schema_editor):
    BailStatus = apps.get_model('contract', 'BailStatus')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    status, _ = BailStatus.objects.update_or_create(
        token='-1',
        defaults={
            'name': 'Cancelled',
            'color': 'red',
            'position': 4,
            'is_default': False
        }
    )
    
    ConfigProject.objects.update_or_create(
        token='bail_status_cancelled_token',
        defaults={
            'name': 'Bail Status Cancelled Token',
            'value': '-1'
        }
    )

def remove_cancelled_bail_status(apps, schema_editor):
    BailStatus = apps.get_model('contract', 'BailStatus')
    ConfigProject = apps.get_model('coredata', 'ConfigProject')
    
    BailStatus.objects.filter(token='-1').delete()
    ConfigProject.objects.filter(token='bail_status_cancelled_token').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0219_remove_generalinvoice_address_send_and_more'),
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cancelled_bail_status, remove_cancelled_bail_status),
    ]
