# Generated by Django 5.0.8 on 2026-05-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0220_contract_company'),
        ('service', '0104_company_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_requests', to='service.company'),
        ),
    ]
