# Generated by Django 5.0.8 on 2026-05-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0220_add_cancelled_bail_status'),
        ('contract', '0221_contractrequest_company'),
    ]

    operations = [
    ]
