# Generated by Django 5.0.8 on 2026-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0222_merge_20260513_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractterminationrequest',
            name='ignore_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
