# Generated by Django 5.0.8 on 2026-05-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0223_contractterminationrequest_ignore_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
