# Generated by Django 5.0.8 on 2026-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0224_contract_mandate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
