# Generated by Django 5.0.8 on 2026-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0225_contractrequest_mandate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequestdocumentation',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
