# Generated by Django 5.0.8 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0226_add_text_to_contractrequestdocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='meter_mode',
            field=models.CharField(choices=[('real', 'Comptador real'), ('fictional', 'Comptador fictici'), ('none', 'Sense comptador')], default='real', max_length=10),
        ),
    ]
