# Generated by Django 5.0.8 on 2026-07-16 08:06

from django.db import migrations, models


def backfill_is_change_of_name(apps, schema_editor):
    ContractRequest = apps.get_model('contract', 'ContractRequest')
    ContractRequest.objects.filter(type__token='canvi_nom').update(is_change_of_name=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0227_contractrequest_meter_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrequest',
            name='is_change_of_name',
            field=models.BooleanField(default=False, verbose_name='Is Change Of Name'),
        ),
        migrations.RunPython(backfill_is_change_of_name, noop_reverse),
    ]
