# Generated by Django 5.0.8 on 2026-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0229_add_keep_same_code_to_contractrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bill_full_period',
            field=models.BooleanField(default=False, verbose_name='Facturar Període Complert'),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='bill_full_period',
            field=models.BooleanField(default=False, verbose_name='Facturar Període Complert'),
        ),
    ]
