# Generated by Django 5.0.8 on 2026-07-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0230_contract_bill_full_period_and_more'),
        ('statistics', '0033_create_vw_contract_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDebtView',
            fields=[
                ('contract_token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'vw_contract_debt',
                'managed': False,
            },
        ),
    ]
