# Generated by Django 5.0.8 on 2026-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0233_remove_contract_debt_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], default='ca', max_length=2),
        ),
        migrations.AddField(
            model_name='contractrequest',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], default='ca', max_length=2),
        ),
    ]
