# Generated by Django 5.0.8 on 2026-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0234_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdatachange',
            name='new_language',
            field=models.CharField(blank=True, choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contractdatachange',
            name='previous_language',
            field=models.CharField(blank=True, choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], max_length=2, null=True),
        ),
    ]
