# Generated by Django 5.0.8 on 2026-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0236_alter_contract_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], default='ca', max_length=2),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='language',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Español'), ('gl', 'Galego'), ('en', 'English')], default='ca', max_length=2),
        ),
    ]
