# Generated by Django 5.0.8 on 2026-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0237_alter_contract_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('PHYSICAL', 'Física'), ('DIGITAL', 'Digital'), ('BOTH', 'Ambdues'), ('NONE', 'Sense comunicació')], default='DIGITAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='communication_type',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('PHYSICAL', 'Física'), ('DIGITAL', 'Digital'), ('BOTH', 'Ambdues'), ('NONE', 'Sense comunicació')], default='DIGITAL', max_length=10),
        ),
    ]
