# Generated by Django 5.0.8 on 2026-08-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0238_add_none_communication_type_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACABonificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('num_persons_to_apply', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('authorizes_census_review', models.BooleanField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('aca_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aca_bonification_requests', to='contract.acadocument')),
                ('bonification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aca_request', to='contract.bonification')),
            ],
        ),
    ]
