# Generated by Django 5.0.8 on 2026-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0240_acabonificationrequest_aca_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpricerate',
            name='is_bop_reference',
            field=models.BooleanField(default=False, verbose_name='Referència per a tarifa BOP'),
        ),
    ]
