# Generated by Django 5.0.8 on 2026-09-17 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0242_contracttenantchangedocumenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_persons',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contractrequest',
            name='total_persons',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
