# Generated by Django 5.0.8 on 2026-10-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0243_alter_contract_total_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadocumentchange',
            name='aca_result',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='bonification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aca_document_changes', to='contract.bonification'),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='collective_report',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='num_persons',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acadocumentchange',
            name='social_collective',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
