# Generated by Django 5.0.8 on 2024-10-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_contract_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderobservation',
            old_name='cmms',
            new_name='order',
        ),
    ]
