# Generated by Django 5.0.8 on 2024-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_cmms_orderobservation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operator',
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ManyToManyField(blank=True, related_name='orders', to='order.operator'),
        ),
    ]
