# Generated by Django 5.0.8 on 2024-10-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_operator_order_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='operator',
            new_name='operators',
        ),
    ]
