# Generated by Django 5.0.8 on 2024-10-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_operator_order_operators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
