# Generated by Django 5.0.8 on 2024-10-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_operators_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='orders', to='order.operator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordertype', verbose_name='Order Type'),
        ),
    ]
