# Generated by Django 5.0.8 on 2024-10-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_operators_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='order.order'),
        ),
    ]
