# Generated by Django 5.0.8 on 2024-11-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0102_remove_contractrequest_orders'),
        ('order', '0009_alter_orderobservation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contract.contractrequest'),
        ),
    ]
