# Generated by Django 5.0.8 on 2024-11-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0113_remove_contractterminationrequest_order'),
        ('order', '0011_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_termination_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contract.contractterminationrequest'),
        ),
    ]
