# Generated by Django 5.0.8 on 2025-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_contract_termination_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('type', models.ManyToManyField(blank=True, related_name='reasons', to='order.ordertype')),
            ],
        ),
    ]
