# Generated by Django 5.0.8 on 2025-03-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_contract_termination_request'),
        ('service', '0065_connectionrequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='connection_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.connectionrequest'),
        ),
    ]
