# Generated by Django 5.0.8 on 2025-02-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderreason', verbose_name='Order Reason'),
        ),
    ]
