# Generated by Django 5.0.8 on 2025-03-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_connection_request'),
        ('order', '0015_alter_order_token'),
    ]

    operations = [
    ]
