# Generated by Django 5.0.8 on 2025-05-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimrequest', '0005_remove_claimrequeststeptemplate_action_date_at'),
        ('order', '0016_merge_20250304_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claim_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='claimrequest.claimrequest'),
        ),
    ]
