# Generated by Django 5.0.8 on 2025-05-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreport',
            name='dedicated_time',
        ),
        migrations.AddField(
            model_name='orderreport',
            name='time_dedicated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
