# Generated by Django 5.0.8 on 2025-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_orderreport_document_orderreportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
