# Generated by Django 5.0.8 on 2025-05-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_orderreport_end_at_orderreport_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
