# Generated by Django 5.0.8 on 2025-06-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_incidentdocumentation'),
        ('order', '0022_alter_orderreport_end_at_alter_orderreport_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='notification.incident'),
        ),
    ]
