# Generated by Django 5.0.8 on 2025-07-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturapp', '0001_initial'),
        ('order', '0023_order_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturapp.readingoperator'),
        ),
    ]
