# Generated by Django 5.0.8 on 2025-10-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_orderpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dueDateAt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderpriority', verbose_name='Order Priority'),
        ),
    ]
