# Generated by Django 5.0.8 on 2026-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
