# Generated by Django 5.0.8 on 2026-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_order_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobservation',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
