# Generated by Django 5.0.8 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_order_new_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='gmao_department_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
