# Generated by Django 5.0.8 on 2025-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('entity_id', models.IntegerField()),
                ('document_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_url', models.URLField()),
                ('service', models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('drive', 'Drive')], max_length=50)),
            ],
        ),
    ]
