# Generated by Django 5.0.8 on 2025-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0002_document_entity_name_alter_document_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
