# Generated by Django 5.0.8 on 2025-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0003_alter_document_location_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='entity_name',
            new_name='folder',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
