# Generated by Django 5.0.8 on 2025-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0004_rename_entity_name_document_folder_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entity_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
