# Generated by Django 5.0.8 on 2025-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0006_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('drive', 'Drive'), ('ftp', 'FTP')], max_length=50),
        ),
    ]
