# Generated by Django 5.0.8 on 2025-04-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0007_alter_document_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documentmanager.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
