# Generated by Django 5.0.8 on 2025-04-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0008_document_is_active_document_parent_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('drive', 'Drive'), ('ftp', 'FTP'), ('aws', 'AWS')], max_length=50),
        ),
    ]
