# Generated by Django 5.0.8 on 2025-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0009_alter_document_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
