# Generated by Django 5.0.8 on 2025-04-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0010_document_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signature',
        ),
    ]
