# Generated by Django 5.0.8 on 2025-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0011_remove_document_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('drive', 'Drive'), ('ftp', 'FTP'), ('aws', 'AWS'), ('alfresco', 'Alfresco')], max_length=50),
        ),
    ]
