# Generated by Django 5.0.8 on 2025-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0012_alter_document_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.CharField(choices=[('hdd', 'HDD'), ('azure', 'Azure'), ('cloud', 'Cloud'), ('ftp', 'FTP'), ('aws', 'AWS'), ('alfresco', 'Alfresco')], max_length=50),
        ),
    ]
