# Generated by Django 5.0.8 on 2025-05-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0013_alter_document_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
