# Generated by Django 5.0.8 on 2026-07-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0227_contractrequest_meter_mode'),
        ('documentmanager', '0015_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Sended'), (3, 'Signed'), (-1, 'Error')], default=1)),
                ('error_report', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs', to='contract.contract')),
                ('contract_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs_as_file', to='documentmanager.document')),
                ('contract_file_signed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs_as_signed_file', to='documentmanager.document')),
                ('contract_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signs', to='contract.contractrequest')),
            ],
            options={
                'verbose_name': 'Document Sign',
                'verbose_name_plural': 'Document Signs',
            },
        ),
    ]
