# Generated by Django 5.0.8 on 2026-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0016_documentsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsign',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Sended'), (3, 'Signed'), (4, 'Expired'), (-1, 'Error')], default=1),
        ),
    ]
