# Generated by Django 5.0.8 on 2025-12-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0027_order_duedateat_order_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('structure', models.JSONField()),
                ('order_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.ordertype', verbose_name='Order Type')),
            ],
        ),
    ]
