# Generated by Django 5.0.8 on 2025-12-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
        ('order', '0027_order_duedateat_order_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_form', models.JSONField()),
                ('order_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderreport', verbose_name='Order Report')),
            ],
        ),
    ]
