# Generated by Django 5.0.8 on 2025-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturapp', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
