# Generated by Django 5.0.8 on 2025-07-17 07:33

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def set_token_expiration_dates(apps, schema_editor):
    """Set expiration dates for existing tokens"""
    Token = apps.get_model('lecturapp', 'Token')
    
    # Get all tokens without expiration date
    tokens_without_expiration = Token.objects.filter(expiration_date__isnull=True)
    
    # Set expiration date to 60 days from now for each token
    for token in tokens_without_expiration:
        token.expiration_date = timezone.now() + timedelta(days=60)
        token.save(update_fields=['expiration_date'])


def reverse_set_token_expiration_dates(apps, schema_editor):
    """Reverse migration - set expiration dates back to None"""
    Token = apps.get_model('lecturapp', 'Token')
    
    # This is a destructive operation, so we'll just pass
    # In a real scenario, you might want to handle this differently
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lecturapp', '0003_token_expiration_date'),
    ]

    operations = [
        migrations.RunPython(
            set_token_expiration_dates,
            reverse_set_token_expiration_dates
        ),
    ]
