# Generated by Django 5.0.8 on 2025-04-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0074_alter_supplycut_supply_points'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplypointconsumption',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplypointconsumption',
            name='supply_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.supplypoint'),
            preserve_default=False,
        ),
    ]
