# Generated by Django 5.0.8 on 2025-05-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0015_document_file'),
        ('statistics', '0002_alter_supplypointconsumption_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document')),
            ],
        ),
    ]
