# Generated by Django 5.0.8 on 2025-05-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0015_document_file'),
        ('statistics', '0004_reporttype_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='GeneralReport',
        ),
    ]
