# Generated by Django 5.0.8 on 2025-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_rename_report_generalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
