# Generated by Django 5.0.8 on 2025-05-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0015_document_file'),
        ('statistics', '0006_reporttype_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalreport',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentmanager.document'),
        ),
    ]
