# Generated by Django 5.0.8 on 2025-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_alter_generalreport_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
