# Generated by Django 5.0.8 on 2025-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_generalreport_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
