# Generated by Django 5.0.8 on 2025-11-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_accountingcodes_accountingvalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountingCodes',
            new_name='AccountingCode',
        ),
        migrations.RenameModel(
            old_name='AccountingValues',
            new_name='AccountingValue',
        ),
    ]
