# Generated by Django 5.0.8 on 2025-11-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0011_rename_accountingcodes_accountingcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingcode',
            name='is_dynamic',
        ),
    ]
