# Generated by Django 5.0.8 on 2025-11-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_remove_accountingcode_is_dynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingcode',
            name='description',
        ),
    ]
