# Generated by Django 5.0.8 on 2025-11-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0013_remove_accountingcode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingvalue',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='statistics.accountingcode'),
        ),
    ]
