# Generated by Django 5.0.8 on 2026-03-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0258_billingbatch_due_date_billingbatch_issue_date_and_more'),
        ('contract', '0208_remove_contract_contract_search_vector_gin_and_more'),
        ('statistics', '0016_invoicestatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('consumption_days', models.IntegerField(blank=True, null=True)),
                ('consumption_daily_avg', models.FloatField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_consumption', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Billing Consumption',
                'verbose_name_plural': 'Billing Consumptions',
            },
        ),
        migrations.DeleteModel(
            name='InvoiceStatistics',
        ),
    ]
