# Generated by Django 5.0.8 on 2026-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0017_billingconsumption_delete_invoicestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconsumption',
            name='consumption_avg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
