# Generated by Django 5.0.8 on 2026-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0018_billingconsumption_consumption_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconsumption',
            name='total_amount_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
