# Generated by Django 5.0.8 on 2026-03-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0019_billingconsumption_total_amount_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconsumption',
            name='daily_consumption',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contractconsumption',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplypointconsumption',
            name='daily_consumption',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplypointconsumption',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
