# Generated by Django 5.0.8 on 2026-03-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0212_alter_contract_use_type'),
        ('statistics', '0020_contractconsumption_daily_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconsumption',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_stats', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='contractconsumption',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_stats', to='contract.contract'),
        ),
    ]
