# Generated by Django 5.0.8 on 2026-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0021_alter_billingconsumption_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBatchExportColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
