# Generated by Django 5.0.8 on 2026-05-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0022_readingbatchexportcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'informe")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Descripció de l'informe")),
                ('is_active', models.BooleanField(default=True, verbose_name='Està activat')),
                ('function_name', models.CharField(help_text="Clau que s'utilitza a run_report_task de Celery (ex. 'accounting_values_report')", max_length=255, verbose_name='Funció a cridar / Tasca Celery')),
                ('download_button_name', models.CharField(default='Descarregar Excel', max_length=255, verbose_name='Nom del botó de descàrrega')),
                ('has_custom_config', models.BooleanField(default=False, help_text='Si està actiu, el front-end pintarà un formulari dissenyat a mida per a aquest informe.', verbose_name='Té configuració personalitzada al front')),
                ('required_fields', models.JSONField(blank=True, default=list, help_text="Llista de camps que necessita el formulari genèric. Exemple: ['start_date', 'end_date', 'exploitation_id']", verbose_name='Camps requerits')),
                ('position', models.IntegerField(default=0, verbose_name='Posició')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_reports', to='statistics.reporttype', verbose_name='Secció a la qual correspon')),
            ],
            options={
                'verbose_name': 'Informe Disponible',
                'verbose_name_plural': 'Informes Disponibles',
                'ordering': ['section__position', 'position', 'name'],
            },
        ),
    ]
