# Generated by Django 5.0.8 on 2026-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0023_readingbatchimporttemplate_readingbatchimportcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatchimporttemplate',
            name='is_liters',
            field=models.BooleanField(default=False),
        ),
    ]
