# Generated by Django 5.0.8 on 2026-05-18 08:00

from django.db import migrations


def seed_reports(apps, schema_editor):
    ReportType = apps.get_model('statistics', 'ReportType')
    AvailableReport = apps.get_model('statistics', 'AvailableReport')

    # Creació o cerca de les seccions del sistema
    sections = {
        'billing': {
            'name': 'Facturació',
            'position': 1
        },
        'wallet': {
            'name': 'Cobraments',
            'position': 2
        },
        'contracts': {
            'name': 'Contractes',
            'position': 3
        },
        'orders': {
            'name': 'Ordres de Treball',
            'position': 4
        },
        'statistics': {
            'name': 'Estadístiques',
            'position': 5
        }
    }

    section_objects = {}
    for token, details in sections.items():
        obj, created = ReportType.objects.get_or_create(
            token=token,
            defaults={
                'name': details['name'],
                'position': details['position'],
                'is_active': True
            }
        )
        section_objects[token] = obj

    reports_data = [
        # Secció: Facturació
        {
            "name": "Resum de facturació",
            "description": "Resum global de facturació amb imports agregats per explotació i període.",
            "function_name": "get_report_billing_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 1
        },
        {
            "name": "Resum comptable",
            "description": "Resum d'assentaments i conceptes comptables facturats.",
            "function_name": "accounting_values_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 2
        },
        {
            "name": "Resum comptable (Factures)",
            "description": "Resum d'assentaments i conceptes comptables facturats (Factures).",
            "function_name": "accounting_values_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 3,
            "is_active": False
        },
        {
            "name": "Resum comptable (Compromís de pagament)",
            "description": "Resum d'assentaments i conceptes comptables facturats (Compromisos de pagament).",
            "function_name": "accounting_values_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 4,
            "is_active": False
        },
        {
            "name": "Remeses Aqua",
            "description": "Detall resumit de les remeses bancàries enviades per al cobrament.",
            "function_name": "aqua_remittance_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": True,
            "required_fields": ["remittance_id"],
            "position": 5
        },
        {
            "name": "Declaració ACA",
            "description": "Declaració oficial del cànon de l'aigua d'acord amb la normativa de l'ACA.",
            "function_name": "aca_summary_report",
            "section_token": "billing",
            "download_button_name": "Generar Cànon ACA",
            "has_custom_config": True,
            "required_fields": [],
            "position": 6
        },
        {
            "name": "Padró de facturació",
            "description": "Registre unificat de factures emeses.",
            "function_name": "register_billing_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Padró",
            "has_custom_config": True,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 7
        },
        {
            "name": "Resum de facturació detallat",
            "description": "Detall minuciós línia per línia del registre de facturació.",
            "function_name": "detailed_billing_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 8
        },
        {
            "name": "Resum de facturació per tipus de punt de subministrament",
            "description": "Detall d'imports facturats agregats per modalitat o tipus de subministrament.",
            "function_name": "billing_summary_by_supply_type",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 9
        },
        {
            "name": "Resum d'abonats per tarifa",
            "description": "Distribució dels imports facturats segmentats per les diferents tarifes actives.",
            "function_name": "billing_summary_by_rates",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 10
        },
        {
            "name": "Resum de facturació IVA",
            "description": "Agregació de bases imposables i quotes d'impostos aplicats (IVA).",
            "function_name": "billing_taxes_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 11
        },
        {
            "name": "Resum de facturació per integració NAVISION",
            "description": "Detall línia per línia d'impostos aplicats en el període.",
            "function_name": "billing_taxes_detailed_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 12
        },
        {
            "name": "Resum de consum",
            "description": "Detall de consums registrats i mitjanes del període liquidat.",
            "function_name": "billing_detailed_consumption_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 13
        },
        {
            "name": "Padró de facturació reduït",
            "description": "Versió compacta i resumida del registre de factures.",
            "function_name": "mini_register_billing_summary",
            "section_token": "billing",
            "download_button_name": "Descarregar Padró",
            "has_custom_config": True,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 14
        },
        {
            "name": "Informe de Recaptació",
            "description": "Resum de cobraments de factures i taxes segons el moviment de cartera.",
            "function_name": "recaptacio_excel_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 15
        },
        {
            "name": "Resum de pagaments cobrats",
            "description": "Informe de cobraments i devolucions amb prorrateig conceptual de costos.",
            "function_name": "cobraments_excel_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 16
        },
        {
            "name": "Informe de Recaptació per Conceptes",
            "description": "Informe de recaptació agregada per cadascun dels conceptes dinàmics.",
            "function_name": "recaptacio_conceptes_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 17
        },
        {
            "name": "Fiances INCASOL",
            "description": "Llistat de fiances gestionades, actives, retornades o cancel·lades.",
            "function_name": "bails_report",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 18
        },
        {
            "name": "Resum de facturació per persona",
            "description": "Resum de facturació acumulat i desglossat per persona/titular.",
            "function_name": "report_billing_total_by_person",
            "section_token": "billing",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 19
        },
        {
            "name": "Model 347",
            "description": "Declaració anual d'operacions amb terceres persones que superin el límit legal (Model 347).",
            "function_name": "report_billing_347",
            "section_token": "billing",
            "download_button_name": "Descarregar Model 347",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 20
        },

        # Secció: Cobraments
        {
            "name": "Resum de rebuts domiciliats",
            "description": "Situació i balances balances globals dels rebuts de cartera.",
            "function_name": "wallet_summary",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 1
        },
        {
            "name": "Llistat de rebuts domiciliats",
            "description": "Distribució i relació detallada per entitat bancària.",
            "function_name": "wallet_bank_list",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 2
        },
        {
            "name": "Llistat de rebuts domiciliats detallat",
            "description": "Detall individual de moviments bancaris per entitat.",
            "function_name": "wallet_bank_detailed_summary",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 3
        },
        {
            "name": "Resum de pagaments cobrats en efectiu",
            "description": "Registre dels moviments comptabilitzats per la caixa física/manual.",
            "function_name": "wallet_cash_detailed_summary",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 4
        },
        {
            "name": "Informe retorn SEPA",
            "description": "Llistat general de deutes vençuts i pendents de cobrament.",
            "function_name": "wallet_unpaid_summary",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 5
        },
        {
            "name": "Informe de tots els impagats (Global)",
            "description": "Informe global de tots els rebuts en estat impagat o vençut sense importar el mètode de pagament.",
            "function_name": "wallet_all_unpaid_summary",
            "section_token": "wallet",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 6
        },

        # Secció: Contractes
        {
            "name": "Exportació de contractes",
            "description": "Llistat complet de contractes amb les seves dades tècniques i d'abonats.",
            "function_name": "contracts_export_report",
            "section_token": "contracts",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 1
        },
        {
            "name": "Resum de lectures i factures per contracte",
            "description": "Traçabilitat històrica de lectures i factures associades a cada contracte.",
            "function_name": "contracts_invoice_reading_summary_report",
            "section_token": "contracts",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 2
        },
        {
            "name": "Exportació de tarifes",
            "description": "Relació de tarifes actives assignades als contractes.",
            "function_name": "contracts_tariffs_export_report",
            "section_token": "contracts",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 3
        },
        {
            "name": "Exportació de baixes",
            "description": "Resum històric dels contractes que han sol·licitat la baixa del servei.",
            "function_name": "contracts_termination_export_report",
            "section_token": "contracts",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 4
        },

        # Secció: Ordres de Treball
        {
            "name": "Resum temps destinat a ordres de treball",
            "description": "Estadístiques de resolució i temps de resposta d'ordres de treball de camp.",
            "function_name": "order_time_summary",
            "section_token": "orders",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range"],
            "position": 1
        },

        # Secció: Estadístiques / Avançats
        {
            "name": "Ingrés detallat per tipologia i periodicitat",
            "description": "Estadística del nombre d'abonats classificats per tipus d'ús i freqüència de lectura.",
            "function_name": "detailed_typology_periodicity_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 1
        },
        {
            "name": "Ingrés detallat per concepte",
            "description": "Ingressos de facturació segregats per concepte tarifari i període.",
            "function_name": "detailed_concept_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 2
        },
        {
            "name": "Detall ingressos no tarifaris",
            "description": "Relació d'ingressos especials o derivats d'actuacions no periòdiques.",
            "function_name": "non_tariff_income_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 3
        },
        {
            "name": "Evolució d'abonats, altes i baixes",
            "description": "Gràfics i ràtios històrics de noves altes i baixes netes.",
            "function_name": "subscriber_evolution_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 4
        },
        {
            "name": "Evolució de tarifa social i vulnerables",
            "description": "Estadístiques dels abonats beneficiaris de bonificacions i cànons socials.",
            "function_name": "social_tariff_evolution_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 5
        },
        {
            "name": "Temps de resposta a reclamacions",
            "description": "Informe d'auditoria sobre reclamacions rebudes i la seva data de tancament.",
            "function_name": "claim_response_time_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 6
        },
        {
            "name": "Volum i estadístiques de gestions",
            "description": "Mètriques agregades de l'activitat diària de l'oficina comercial.",
            "function_name": "management_volume_report",
            "section_token": "statistics",
            "download_button_name": "Descarregar Excel",
            "has_custom_config": False,
            "required_fields": ["date_range", "exploitation_id"],
            "position": 7
        }
    ]

    # Delete old report that we are renaming/refactoring
    AvailableReport.objects.filter(function_name='clavegueram_excel_report').delete()

    for data in reports_data:
        section_obj = section_objects.get(data['section_token'])
        AvailableReport.objects.update_or_create(
            name=data['name'],
            function_name=data['function_name'],
            defaults={
                'description': data['description'],
                'section': section_obj,
                'download_button_name': data['download_button_name'],
                'has_custom_config': data['has_custom_config'],
                'required_fields': data['required_fields'],
                'position': data['position'],
                'is_active': data.get('is_active', True)
            }
        )


def rollback_reports(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    AvailableReport.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0023_availablereport'),
    ]

    operations = [
        migrations.RunPython(seed_reports, reverse_code=rollback_reports),
    ]
