# Generated by Django 5.0.8 on 2026-05-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0024_readingbatchimporttemplate_is_liters'),
        ('statistics', '0024_seed_available_reports'),
    ]

    operations = [
    ]
