# Generated by Django 5.0.8 on 2026-05-21

from django.db import migrations

def update_accounting_reports(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    
    # Update ID 2
    try:
        report_2 = AvailableReport.objects.get(id=2)
        report_2.name = "Resum comptable (Factures)"
        report_2.function_name = "accounting_values_invoice_report"
        report_2.is_active = True
        report_2.save()
    except AvailableReport.DoesNotExist:
        pass
        
    # Update ID 3
    try:
        report_3 = AvailableReport.objects.get(id=3)
        report_3.name = "Resum comptable (Cobraments)"
        report_3.function_name = "accounting_values_payment_report"
        report_3.is_active = True
        report_3.save()
    except AvailableReport.DoesNotExist:
        pass
        
    # Update ID 4
    try:
        report_4 = AvailableReport.objects.get(id=4)
        report_4.name = "Resum comptable (Compromís de pagament)"
        report_4.function_name = "accounting_values_commitment_report"
        report_4.is_active = True
        report_4.save()
    except AvailableReport.DoesNotExist:
        pass

def rollback_accounting_reports(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    
    # Rollback ID 2
    try:
        report_2 = AvailableReport.objects.get(id=2)
        report_2.name = "Resum comptable"
        report_2.function_name = "accounting_values_report"
        report_2.is_active = True
        report_2.save()
    except AvailableReport.DoesNotExist:
        pass
        
    # Rollback ID 3
    try:
        report_3 = AvailableReport.objects.get(id=3)
        report_3.name = "Resum comptable (Factures)"
        report_3.function_name = "accounting_values_report"
        report_3.is_active = False
        report_3.save()
    except AvailableReport.DoesNotExist:
        pass
        
    # Rollback ID 4
    try:
        report_4 = AvailableReport.objects.get(id=4)
        report_4.name = "Resum comptable (Compromís de pagament)"
        report_4.function_name = "accounting_values_report"
        report_4.is_active = False
        report_4.save()
    except AvailableReport.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0025_merge_20260518_1528'),
    ]

    operations = [
        migrations.RunPython(update_accounting_reports, rollback_accounting_reports),
    ]
