# Generated by Django 5.0.8 on 2026-05-21

from django.db import migrations

def move_recaptacio_to_wallet(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    ReportType = apps.get_model('statistics', 'ReportType')
    
    try:
        wallet_section = ReportType.objects.get(token='wallet')
    except ReportType.DoesNotExist:
        return
        
    AvailableReport.objects.filter(function_name='recaptacio_excel_report').update(section=wallet_section)
    AvailableReport.objects.filter(function_name='recaptacio_conceptes_report').update(section=wallet_section)

    # Delete old report if substitute exists
    if AvailableReport.objects.filter(function_name='recaptacio_excel_report').exists():
        AvailableReport.objects.filter(function_name='clavegueram_excel_report').delete()

def rollback_move_recaptacio_to_wallet(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    ReportType = apps.get_model('statistics', 'ReportType')
    
    try:
        billing_section = ReportType.objects.get(token='billing')
    except ReportType.DoesNotExist:
        return
        
    AvailableReport.objects.filter(function_name='recaptacio_excel_report').update(section=billing_section)
    AvailableReport.objects.filter(function_name='recaptacio_conceptes_report').update(section=billing_section)

class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0026_update_accounting_reports'),
    ]

    operations = [
        migrations.RunPython(move_recaptacio_to_wallet, rollback_move_recaptacio_to_wallet),
    ]
