# Generated by Django 5.0.8 on 2026-06-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0015_document_file'),
        ('statistics', '0028_add_clavegueram_invoices_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentmanager.document')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='statistics.availablereport')),
            ],
            options={
                'verbose_name': 'Report Queue',
                'verbose_name_plural': 'Report Queues',
                'ordering': ['created_at'],
            },
        ),
    ]
