# Generated by Django 5.0.8 on 2026-07-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0033_create_vw_contract_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='filters_display',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportqueue',
            name='filters_display',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
