# Generated by Django 5.0.8 on 2026-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0035_add_incasol_liquidation_report'),
    ]

    operations = [

        # -----------------------------
        # vw_contract_debt: deute acumulat per contracte, precalculat.
        # Mateixa definicio que fa servir l'aplicatiu real
        # (contract/serializers/contract_serializer.py::get_debt_amount).
        # VIEW normal (no materialitzada): sempre actualitzada, sense cap procés
        # de refresc (ni Celery ni manual).
        # -----------------------------
        migrations.RunSQL(
            """
            -- Si encara existeix com a MATERIALIZED VIEW, CREATE OR REPLACE VIEW
            -- falla amb WrongObjectType. I si ja existeix com a VIEW normal,
            -- "DROP MATERIALIZED VIEW IF EXISTS" tambe falla amb WrongObjectType
            -- (IF EXISTS nomes evita l'error de "no existeix", no el de tipus
            -- incorrecte). Cal comprovar el tipus real a pg_class abans de fer
            -- el DROP.
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'vw_contract_debt' AND relkind = 'm') THEN
                    EXECUTE 'DROP MATERIALIZED VIEW vw_contract_debt CASCADE';
                ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'vw_contract_debt' AND relkind = 'v') THEN
                    EXECUTE 'DROP VIEW vw_contract_debt CASCADE';
                END IF;
            END $$;
            CREATE VIEW vw_contract_debt AS
            SELECT c.token AS contract_token, COALESCE(SUM(p.amount), 0) AS debt_amount
            FROM contract_contract c
            JOIN billing_invoice i ON i.contract_id = c.id
            JOIN billing_payment p ON p.invoice_id = i.id
            JOIN billing_paymentstatus ps ON ps.id = p.status_id
            WHERE ps.token NOT IN ('0','-4','-6', '-7', '-99')
            GROUP BY c.token;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'vw_contract_debt' AND relkind = 'm') THEN
                    EXECUTE 'DROP MATERIALIZED VIEW vw_contract_debt CASCADE';
                ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'vw_contract_debt' AND relkind = 'v') THEN
                    EXECUTE 'DROP VIEW vw_contract_debt CASCADE';
                END IF;
            END $$;
            """
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS contract_contract_token_idx ON contract_contract (token);",
            reverse_sql="DROP INDEX IF EXISTS contract_contract_token_idx;",
        ),
    ]
