# Generated by Django 5.0.8 on 2026-08-21 11:55

from django.db import migrations

def add_new_available_report(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    ReportType = apps.get_model('statistics', 'ReportType')

    contract_section = ReportType.objects.filter(token='contracts').first()

    AvailableReport.objects.get_or_create(
        function_name='pending_invoices_values_report',
        defaults={
            'name': 'Deute pendent',
            'description': (
                'Resum de deutes pendents per contracte i/o persona.'
            ),
            'is_active': True,
            'section': contract_section,
            'download_button_name': 'Descarregar Excel',
            'has_custom_config': False,
            'required_fields': ['date_range', 'exploitation_id'],
            'position': 22,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0036_update_vw_contract_debt'),
    ]

    operations = [
        migrations.RunPython(add_new_available_report),
    ]
