# Generated by Django 5.0.8 on 2026-09-09 08:10

from django.db import migrations

def add_new_available_report(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    ReportType = apps.get_model('statistics', 'ReportType')

    contract_section = ReportType.objects.filter(token='contracts').first()

    AvailableReport.objects.get_or_create(
        function_name='pending_invoices_values_report',
        defaults={
            'name': 'Deute pendent',
            'description': (
                'Resum de deutes pendents per contracte i/o persona.'
            ),
            'is_active': False,
            'section': contract_section,
            'download_button_name': 'Descarregar Excel',
            'has_custom_config': True,
            'required_fields': ['date_range'],
            'position': 24,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0037_new_available_report'),
    ]

    operations = [
    ]
