# Generated by Django 5.0.8 on 2026-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0039_dailydocumentstatus_dailydocumenttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailydocument',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
