# Generated by Django 5.0.8 on 2026-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0040_dailydocument_name_dailydocument_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydocument',
            name='creation_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
