# Generated by Django 5.0.8 on 2026-09-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0041_dailydocument_creation_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydocumentstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
