# Generated by Django 5.0.8 on 2026-09-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0039_vw_contract_debt_no_negative'),
        ('statistics', '0042_dailydocumentstatus_color'),
    ]

    operations = [
    ]
