# Generated by Django 5.0.8 on 2026-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0043_merge_20260914_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportqueue',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('skipped', 'Skipped'),
                    ('warning', 'Warning'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
