# Generated by Django 5.0.8 on 2026-09-15 07:13

from django.db import migrations

def add_new_available_report(apps, schema_editor):
    AvailableReport = apps.get_model('statistics', 'AvailableReport')
    ReportType = apps.get_model('statistics', 'ReportType')

    payment_section = ReportType.objects.filter(token='wallet').first()

    AvailableReport.objects.get_or_create(
        function_name='general_accounting_report',
        defaults={
            'name': 'Informe Comptable',
            'description': (
                'Informe comptable'
            ),
            'is_active': False,
            'section': payment_section,
            'download_button_name': 'Descarregar Fitxer',
            'has_custom_config': True,
            'required_fields': ['date_range'],
            'position': 26,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0043_merge_20260914_1409'),
    ]

    operations = [
        migrations.RunPython(add_new_available_report),
    ]
