# Generated by Django 5.0.8 on 2026-09-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0044_alter_reportqueue_status_warning'),
        ('statistics', '0044_new_available_report'),
    ]

    operations = [
    ]
